/**
 * pandas.i18n.js — Pandas translations (EN/TR/DE/ES)
 * Loaded after shared.i18n.js
 */
const T_LOCAL = {

  "pd.eyebrow": {
    en:"Tutorial · Pandas",
    tr:"Eğitim · Pandas",
    de:"Tutorial · Pandas",
    es:"Tutorial · Pandas"},
  "pd.desc": {
    en:"The <strong>backbone of data manipulation</strong> in Python. From loading CSVs to building complete NLP preprocessing pipelines — Pandas is where raw data becomes structured, clean, and ready for machine learning. Every data scientist's most-used library.",
    tr:"Python'da <strong>veri manipülasyonunun omurgası</strong>. CSV yüklemekten eksiksiz NLP ön işleme pipeline'ları oluşturmaya kadar — ham veriyi yapılandırılmış, temiz ve makine öğrenmesine hazır hale Pandas getirir.",
    de:"Das <strong>Rückgrat der Datenmanipulation</strong> in Python. Vom CSV-Laden bis zu vollständigen NLP-Preprocessing-Pipelines — Pandas verwandelt Rohdaten in strukturierte, saubere, ML-bereite Daten.",
    es:"La <strong>columna vertebral de la manipulación de datos</strong> en Python. Desde cargar CSVs hasta construir pipelines completos de preprocesamiento NLP — Pandas convierte datos crudos en datos limpios y listos para ML."},
  "pd.level": {
    en:"Beginner → Intermediate",
    tr:"Başlangıç → Orta",
    de:"Anfänger → Mittel",
    es:"Principiante → Intermedio"},

  "pd.l1.t":  {en:"DataFrame & Series Basics",tr:"DataFrame & Series Temelleri",de:"DataFrame- & Series-Grundlagen",es:"Fundamentos de DataFrame y Series"},
  "pd.l1.s":  {en:"pd.DataFrame · pd.Series · dtypes · shape · info() · describe() · head/tail · 8 min",tr:"pd.DataFrame · pd.Series · dtypes · shape · info() · describe() · head/tail · 8 dk",de:"pd.DataFrame · pd.Series · dtypes · shape · info() · describe() · head/tail · 8 Min.",es:"pd.DataFrame · pd.Series · dtypes · shape · info() · describe() · head/tail · 8 min"},
  "pd.l1.p1": {en:"A <strong>DataFrame</strong> is a 2D labeled table — think of it as a spreadsheet in Python. A <strong>Series</strong> is a single column. Together, they are the core data structures you'll use for every data task, from loading CSVs to feeding NLP models.",tr:"<strong>DataFrame</strong> 2B etiketli bir tablodur — Python'daki elektronik tablo gibi düşünün. <strong>Series</strong> tek bir sütundur. Birlikte, CSV yüklemekten NLP modellerini beslemeye kadar her veri görevi için kullanacağınız temel veri yapılarıdır.",de:"Ein <strong>DataFrame</strong> ist eine 2D-beschriftete Tabelle. Eine <strong>Series</strong> ist eine einzelne Spalte. Zusammen sind sie die Kerndatenstrukturen für jede Datenaufgabe.",es:"Un <strong>DataFrame</strong> es una tabla 2D etiquetada. Una <strong>Series</strong> es una sola columna. Juntos son las estructuras de datos principales para toda tarea de datos."},

  "pd.l2.t":  {en:"Indexing & Selection",tr:"İndeksleme & Seçim",de:"Indizierung & Auswahl",es:"Indexación y Selección"},
  "pd.l2.s":  {en:"loc · iloc · boolean indexing · query() · at/iat · MultiIndex · 10 min",tr:"loc · iloc · boolean indeksleme · query() · at/iat · MultiIndex · 10 dk",de:"loc · iloc · Boolesches Indizieren · query() · at/iat · MultiIndex · 10 Min.",es:"loc · iloc · indexación booleana · query() · at/iat · MultiIndex · 10 min"},
  "pd.l2.p1": {en:"Selecting the right rows and columns is the most frequent Pandas operation. <code>loc</code> uses labels, <code>iloc</code> uses integer positions, and <strong>boolean indexing</strong> lets you filter with conditions — essential for splitting datasets and extracting subsets.",tr:"Doğru satır ve sütunları seçmek en sık yapılan Pandas işlemidir. <code>loc</code> etiketleri, <code>iloc</code> tamsayı pozisyonlarını kullanır ve <strong>boolean indeksleme</strong> koşullarla filtrelemenizi sağlar.",de:"Die richtige Auswahl von Zeilen und Spalten ist die häufigste Pandas-Operation. <code>loc</code> verwendet Labels, <code>iloc</code> Integer-Positionen, und <strong>Boolesches Indizieren</strong> filtert nach Bedingungen.",es:"Seleccionar las filas y columnas correctas es la operación más frecuente en Pandas. <code>loc</code> usa etiquetas, <code>iloc</code> posiciones enteras, y la <strong>indexación booleana</strong> filtra con condiciones."},

  "pd.l3.t":  {en:"Data Cleaning",tr:"Veri Temizleme",de:"Datenbereinigung",es:"Limpieza de Datos"},
  "pd.l3.s":  {en:"dropna · fillna · duplicated · replace · astype · rename · string methods · 10 min",tr:"dropna · fillna · duplicated · replace · astype · rename · string yöntemleri · 10 dk",de:"dropna · fillna · duplicated · replace · astype · rename · String-Methoden · 10 Min.",es:"dropna · fillna · duplicated · replace · astype · rename · métodos string · 10 min"},
  "pd.l3.p1": {en:"<strong>80% of data science is cleaning data.</strong> Missing values, duplicates, wrong types, inconsistent strings — Pandas gives you the tools to handle all of it. In NLP, cleaning means the difference between a good model and garbage output.",tr:"<strong>Veri biliminin %80'i veri temizlemedir.</strong> Eksik değerler, tekrarlar, yanlış tipler, tutarsız string'ler — Pandas hepsini çözmek için araçlar sunar. NLP'de temizleme, iyi bir model ile çöp çıktı arasındaki farktır.",de:"<strong>80% der Datenwissenschaft ist Datenbereinigung.</strong> Fehlende Werte, Duplikate, falsche Typen — Pandas bietet die Werkzeuge. In NLP entscheidet die Bereinigung über gute Modelle oder Müll-Output.",es:"<strong>El 80% de la ciencia de datos es limpiar datos.</strong> Valores faltantes, duplicados, tipos incorrectos — Pandas da las herramientas. En NLP, la limpieza marca la diferencia entre un buen modelo y basura."},

  "pd.l4.t":  {en:"GroupBy & Aggregation",tr:"GroupBy & Toplama",de:"GroupBy & Aggregation",es:"GroupBy y Agregación"},
  "pd.l4.s":  {en:"groupby · agg · transform · apply · pivot_table · crosstab · 10 min",tr:"groupby · agg · transform · apply · pivot_table · crosstab · 10 dk",de:"groupby · agg · transform · apply · pivot_table · crosstab · 10 Min.",es:"groupby · agg · transform · apply · pivot_table · crosstab · 10 min"},
  "pd.l4.p1": {en:"<strong>GroupBy</strong> is the split-apply-combine pattern: split data into groups, apply a function, combine results. It's how you compute per-class statistics, per-category counts, and aggregate metrics — fundamental for EDA before training any model.",tr:"<strong>GroupBy</strong> böl-uygula-birleştir kalıbıdır: veriyi gruplara böl, fonksiyon uygula, sonuçları birleştir. Sınıf bazlı istatistikler, kategori sayımları ve toplu metrikler hesaplamak için temeldir.",de:"<strong>GroupBy</strong> ist das Split-Apply-Combine-Muster: Daten aufteilen, Funktion anwenden, Ergebnisse kombinieren. So berechnen Sie Statistiken pro Klasse und aggregierte Metriken.",es:"<strong>GroupBy</strong> es el patrón split-apply-combine: dividir datos en grupos, aplicar función, combinar resultados. Así calculas estadísticas por clase y métricas agregadas."},

  "pd.l5.t":  {en:"Merge, Join & Concat",tr:"Merge, Join & Concat",de:"Merge, Join & Concat",es:"Merge, Join y Concat"},
  "pd.l5.s":  {en:"merge (inner/outer/left) · join · concat · append · 8 min",tr:"merge (inner/outer/left) · join · concat · append · 8 dk",de:"merge (inner/outer/left) · join · concat · append · 8 Min.",es:"merge (inner/outer/left) · join · concat · append · 8 min"},
  "pd.l5.p1": {en:"Real-world data lives in multiple tables. <strong>merge</strong> combines DataFrames on shared keys (like SQL JOINs), <strong>concat</strong> stacks them vertically or horizontally. You'll use these constantly when combining scraped data from different sources or adding metadata to your corpus.",tr:"Gerçek dünya verileri birden fazla tabloda yaşar. <strong>merge</strong> DataFrame'leri ortak anahtarlar üzerinde birleştirir (SQL JOIN gibi), <strong>concat</strong> dikey veya yatay olarak yığar. Farklı kaynaklardan kazınan verileri birleştirirken sürekli kullanacaksınız.",de:"Reale Daten leben in mehreren Tabellen. <strong>merge</strong> kombiniert DataFrames über gemeinsame Schlüssel, <strong>concat</strong> stapelt sie vertikal oder horizontal.",es:"Los datos reales viven en múltiples tablas. <strong>merge</strong> combina DataFrames por claves compartidas, <strong>concat</strong> los apila vertical u horizontalmente."},

  "pd.l6.t":  {en:"String & Text Operations",tr:"String & Metin İşlemleri",de:"String- & Textoperationen",es:"Operaciones de String y Texto"},
  "pd.l6.s":  {en:"str accessor · regex with str.extract · NLP preprocessing with Pandas · 10 min",tr:"str erişimcisi · str.extract ile regex · Pandas ile NLP ön işleme · 10 dk",de:"str-Accessor · Regex mit str.extract · NLP-Preprocessing mit Pandas · 10 Min.",es:"accessor str · regex con str.extract · preprocesamiento NLP con Pandas · 10 min"},
  "pd.l6.p1": {en:"Pandas' <code>.str</code> accessor lets you apply string operations to <strong>entire columns at once</strong> — no loops needed. Combined with regex, it becomes a powerful vectorized text preprocessing engine for NLP.",tr:"Pandas'ın <code>.str</code> erişimcisi string işlemlerini <strong>tüm sütunlara aynı anda</strong> uygulamanızı sağlar — döngü gerekmez. Regex ile birleştiğinde NLP için güçlü bir vektörel metin ön işleme motoru olur.",de:"Pandas' <code>.str</code>-Accessor wendet String-Operationen auf <strong>ganze Spalten gleichzeitig</strong> an — keine Schleifen nötig. Kombiniert mit Regex wird es zu einer leistungsstarken vektorisierten NLP-Engine.",es:"El accessor <code>.str</code> de Pandas aplica operaciones de string a <strong>columnas enteras a la vez</strong> — sin bucles. Combinado con regex, se convierte en un potente motor de preprocesamiento NLP."},

  "pd.l7.t":  {en:"Date & Time",tr:"Tarih & Zaman",de:"Datum & Zeit",es:"Fecha y Hora"},
  "pd.l7.s":  {en:"pd.to_datetime · dt accessor · resample · time series basics · 8 min",tr:"pd.to_datetime · dt erişimcisi · resample · zaman serisi temelleri · 8 dk",de:"pd.to_datetime · dt-Accessor · resample · Zeitreihen-Grundlagen · 8 Min.",es:"pd.to_datetime · accessor dt · resample · fundamentos de series temporales · 8 min"},
  "pd.l7.p1": {en:"Time series data is everywhere — scraped articles have publication dates, model logs have timestamps, social media posts have creation times. Pandas' <code>datetime</code> tools let you parse, filter, and aggregate data by time periods.",tr:"Zaman serisi verileri her yerde — kazınan makalelerin yayın tarihleri, model loglarının zaman damgaları, sosyal medya paylaşımlarının oluşturma zamanları var. Pandas'ın <code>datetime</code> araçları zaman dilimlerine göre ayrıştırma, filtreleme ve toplama yapmanızı sağlar.",de:"Zeitreihendaten sind überall. Pandas' <code>datetime</code>-Tools ermöglichen das Parsen, Filtern und Aggregieren von Daten nach Zeiträumen.",es:"Los datos de series temporales están en todas partes. Las herramientas <code>datetime</code> de Pandas permiten parsear, filtrar y agregar datos por períodos."},

  "pd.l8.t":  {en:"Reading & Writing Data",tr:"Veri Okuma & Yazma",de:"Daten Lesen & Schreiben",es:"Lectura y Escritura de Datos"},
  "pd.l8.s":  {en:"read_csv · read_json · read_excel · to_csv · encoding · chunked reading · 8 min",tr:"read_csv · read_json · read_excel · to_csv · encoding · parçalı okuma · 8 dk",de:"read_csv · read_json · read_excel · to_csv · Encoding · Chunked Reading · 8 Min.",es:"read_csv · read_json · read_excel · to_csv · encoding · lectura por chunks · 8 min"},
  "pd.l8.p1": {en:"Pandas reads and writes almost every tabular format. The key parameters for NLP work are <strong>encoding</strong> (always UTF-8 for Turkish), <strong>separator</strong> (TSV is common in NLP datasets), and <strong>chunked reading</strong> for large files that don't fit in memory.",tr:"Pandas neredeyse her tablo formatını okur ve yazar. NLP çalışmaları için anahtar parametreler: <strong>encoding</strong> (Türkçe için her zaman UTF-8), <strong>ayırıcı</strong> (NLP veri setlerinde TSV yaygındır) ve belleğe sığmayan büyük dosyalar için <strong>parçalı okuma</strong>.",de:"Pandas liest und schreibt fast jedes Tabellenformat. Schlüsselparameter für NLP: <strong>Encoding</strong> (immer UTF-8 für Türkisch), <strong>Separator</strong> (TSV üblich in NLP) und <strong>Chunked Reading</strong> für große Dateien.",es:"Pandas lee y escribe casi todo formato tabular. Parámetros clave para NLP: <strong>encoding</strong> (siempre UTF-8 para turco), <strong>separador</strong> (TSV común en NLP) y <strong>lectura por chunks</strong> para archivos grandes."},

  "pd.l9.t":  {en:"Performance & Best Practices",tr:"Performans & En İyi Uygulamalar",de:"Performance & Best Practices",es:"Rendimiento y Mejores Prácticas"},
  "pd.l9.s":  {en:"vectorized ops vs loops · memory optimization · category dtype · eval/query · 8 min",tr:"vektörel işlemler vs döngüler · bellek optimizasyonu · category dtype · eval/query · 8 dk",de:"Vektorisierte Ops vs Schleifen · Speicheroptimierung · Category-Dtype · eval/query · 8 Min.",es:"ops vectorizadas vs bucles · optimización de memoria · category dtype · eval/query · 8 min"},
  "pd.l9.p1": {en:"Pandas can be slow if you use it wrong. The golden rule: <strong>never loop over rows</strong>. Use vectorized operations, choose the right dtypes, and learn when to use <code>eval()</code> and <code>query()</code> for large DataFrames.",tr:"Pandas yanlış kullanırsanız yavaş olabilir. Altın kural: <strong>asla satırlar üzerinde döngü yapmayın</strong>. Vektörel işlemler kullanın, doğru dtype'ları seçin ve büyük DataFrame'ler için <code>eval()</code> ve <code>query()</code>'yi öğrenin.",de:"Pandas kann langsam sein, wenn man es falsch benutzt. Die goldene Regel: <strong>Nie über Zeilen iterieren</strong>. Verwenden Sie vektorisierte Operationen und die richtigen Dtypes.",es:"Pandas puede ser lento si lo usas mal. La regla de oro: <strong>nunca iterar sobre filas</strong>. Usa operaciones vectorizadas y elige los dtypes correctos."},

  "pd.l10.t": {en:"NLP Data Pipeline with Pandas",tr:"Pandas ile NLP Veri Pipeline'ı",de:"NLP-Datenpipeline mit Pandas",es:"Pipeline de Datos NLP con Pandas"},
  "pd.l10.s": {en:"Complete pipeline: load → clean → label → split → export · 12 min",tr:"Eksiksiz pipeline: yükle → temizle → etiketle → böl → dışa aktar · 12 dk",de:"Komplette Pipeline: laden → bereinigen → labeln → aufteilen → exportieren · 12 Min.",es:"Pipeline completo: cargar → limpiar → etiquetar → dividir → exportar · 12 min"},
  "pd.l10.p1":{en:"This lesson brings everything together into a <strong>complete NLP data pipeline</strong> — the exact workflow you'd use to prepare a Turkish text classification dataset for BERT or LSTM training. From raw scraped data to train/val/test splits, ready for model input.",tr:"Bu ders her şeyi <strong>eksiksiz bir NLP veri pipeline'ında</strong> bir araya getirir — BERT veya LSTM eğitimi için Türkçe metin sınıflandırma veri seti hazırlamada kullanacağınız tam iş akışı. Ham kazınan veriden train/val/test bölmelerine.",de:"Diese Lektion bringt alles in einer <strong>kompletten NLP-Datenpipeline</strong> zusammen — der exakte Workflow zur Vorbereitung eines türkischen Textklassifikations-Datensatzes für BERT oder LSTM.",es:"Esta lección reúne todo en un <strong>pipeline completo de datos NLP</strong> — el flujo exacto para preparar un dataset de clasificación de texto turco para BERT o LSTM."},
};

Object.assign(T, T_LOCAL);
