var NUMPY_L1 = {

en: '<div class="math-prereq" style="background:rgba(245,158,11,0.07);border-left:3px solid #f59e0b;padding:0.95rem 1.2rem;margin:0 0 1.5rem 0;border-radius:0 8px 8px 0"><div style="font-size:0.74rem;font-weight:700;letter-spacing:0.1em;color:#f59e0b;margin-bottom:0.5rem">📐 MATH FOUNDATIONS</div><p style="margin:0 0 0.55rem 0;font-size:0.9rem;line-height:1.55;color:rgba(235,230,220,0.85)">New to the math used here? Refresh these first — each is a self-contained Mathematics lesson:</p><ul style="margin:0;padding-left:1.25rem;font-size:0.88rem;line-height:1.7;color:rgba(235,230,220,0.85);list-style:none"><li><a href="/tutorials/matematik/40" style="color:#f59e0b;text-decoration:none;border-bottom:1px dotted #f59e0b">Functions &amp; Notation</a> <span style="opacity:0.55;font-size:0.82em">(Math L40)</span></li><li><a href="/tutorials/matematik/72" style="color:#f59e0b;text-decoration:none;border-bottom:1px dotted #f59e0b">Matrices &amp; Operations</a> <span style="opacity:0.55;font-size:0.82em">(Math L72)</span></li><li><a href="/tutorials/matematik/91" style="color:#f59e0b;text-decoration:none;border-bottom:1px dotted #f59e0b">Geometric Vectors</a> <span style="opacity:0.55;font-size:0.82em">(Math L91)</span></li></ul></div><p class="l-text"><strong>NumPy is the bedrock of scientific computing in Python.</strong> Every machine learning library you will ever use -- scikit-learn, TensorFlow, PyTorch, Pandas -- is built on top of NumPy arrays. Understanding how to create, inspect, and manipulate these arrays is the single most important skill for any data scientist or ML engineer.</p>'

+ '<p class="l-text">This lesson takes you from zero to confident: why NumPy exists, how its core object (the <strong>ndarray</strong>) works, every creation function you will need, data types, reshaping, and real-world patterns you will use daily.</p>'
+ '<div class="lesson-outcomes" style="background:rgba(200,169,110,0.06);border-left:3px solid #c8a96e;padding:1rem 1.2rem;margin:1.5rem 0;border-radius:0 8px 8px 0"><div style="font-size:0.78rem;font-weight:700;letter-spacing:0.08em;color:#c8a96e;margin-bottom:0.6rem">📍 WHAT YOU\'LL LEARN</div><ul style="margin:0;padding-left:1.3rem;line-height:1.65;font-size:0.93rem;color:rgba(235,230,220,0.92)"><li>Explain why NumPy is 10–100x faster than Python lists for numeric work</li><li>Create ndarrays with zeros, ones, full, eye, arange, linspace, and logspace</li><li>Inspect array attributes: shape, dtype, ndim, size, itemsize, and nbytes</li><li>Pick the right dtype to balance precision and memory footprint</li><li>Reshape arrays and reason about 1D vectors, 2D matrices, and 3D+ tensors</li></ul></div>'


/* ============================================================
   SECTION 1: Why NumPy?
   ============================================================ */
+ '<h2 class="l-title">1. Why NumPy?</h2>'

+ '<div class="calc-highlight"><strong>The short answer:</strong> Python lists are slow. NumPy arrays are fast. For numerical work, NumPy is <strong>10x to 100x faster</strong> than pure Python because it delegates computation to optimized C/Fortran code and operates on contiguous blocks of memory.</div>'

+ '<p class="l-text">Consider adding two lists of 1 million numbers. In pure Python, you need a for-loop that iterates one million times, calling Python\'s interpreter at each step. NumPy replaces that entire loop with a <strong>single C-level operation</strong> called <strong>vectorization</strong>.</p>'

+ '<div class="calc-cards"><div class="calc-card"><div class="card-title">C Backend</div><div class="card-body">NumPy\'s core is written in C and Fortran. Your Python code calls fast compiled routines under the hood -- no interpreter overhead per element.</div></div><div class="calc-card"><div class="card-title">Vectorization</div><div class="card-body">Apply an operation to an entire array at once instead of looping element by element. One line of code replaces a for-loop.</div></div><div class="calc-card"><div class="card-title">Contiguous Memory</div><div class="card-body">All elements sit side-by-side in memory. This enables CPU cache efficiency and SIMD instructions -- hardware-level parallelism.</div></div><div class="calc-card"><div class="card-title">Fixed Types</div><div class="card-body">Every element has the same data type (e.g., float64). No type-checking per element means the CPU can blast through data.</div></div></div>'

+ '<div class="calc-compare"><div class="compare-col"><div class="compare-title">Python List</div><div class="compare-item">Each element is a full Python object (28+ bytes)</div><div class="compare-item">Type-checked at every operation</div><div class="compare-item">Elements scattered in memory</div><div class="compare-item">Must loop to apply operations</div><div class="compare-item">Flexible: can mix types [1, "hi", 3.14]</div></div><div class="compare-col"><div class="compare-title">NumPy Array</div><div class="compare-item">Each element is a raw number (4-8 bytes)</div><div class="compare-item">Single type -- no per-element checking</div><div class="compare-item">Contiguous memory block</div><div class="compare-item">Vectorized: one call processes all elements</div><div class="compare-item">Strict: all elements must be same type</div></div></div>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="kw">import</span> numpy <span class="kw">as</span> np\n<span class="kw">import</span> time\n\nsize = <span class="num">1_000_000</span>\n\n<span class="cm"># Python list approach</span>\npy_a = <span class="fn">list</span>(<span class="fn">range</span>(size))\npy_b = <span class="fn">list</span>(<span class="fn">range</span>(size))\n\nstart = time.<span class="fn">time</span>()\npy_c = [a + b <span class="kw">for</span> a, b <span class="kw">in</span> <span class="fn">zip</span>(py_a, py_b)]\npy_time = time.<span class="fn">time</span>() - start\n\n<span class="cm"># NumPy approach</span>\nnp_a = np.<span class="fn">arange</span>(size)\nnp_b = np.<span class="fn">arange</span>(size)\n\nstart = time.<span class="fn">time</span>()\nnp_c = np_a + np_b   <span class="cm"># vectorized -- no loop!</span>\nnp_time = time.<span class="fn">time</span>() - start\n\n<span class="fn">print</span>(<span class="str">f"Python list: {py_time:.4f}s"</span>)  <span class="cm"># ~0.15s</span>\n<span class="fn">print</span>(<span class="str">f"NumPy array: {np_time:.4f}s"</span>) <span class="cm"># ~0.002s</span>\n<span class="fn">print</span>(<span class="str">f"NumPy is {py_time/np_time:.0f}x faster"</span>)</code></pre></div>'

/* --- Plotly: Speed Comparison EN --- */
+ '<div id="plot-speed-en" class="plotly-graph"></div>'
+ '<script>setTimeout(function(){'
+ 'var data=[{x:["Python List Loop","NumPy Vectorized"],y:[150,2],type:"bar",marker:{color:["#f87171","#4de87a"],line:{color:"rgba(255,255,255,0.2)",width:1}},text:["~150 ms","~2 ms"],textposition:"outside",textfont:{color:"#ebe6dc",size:13}}];'
+ 'var layout={title:{text:"Adding 1M Numbers: Python List vs NumPy",font:{color:"#ebe6dc",size:14}},paper_bgcolor:"rgba(0,0,0,0)",plot_bgcolor:"rgba(0,0,0,0)",font:{color:"#ebe6dc"},yaxis:{title:"Time (ms)",gridcolor:"rgba(255,255,255,0.06)",zerolinecolor:"rgba(255,255,255,0.15)"},xaxis:{gridcolor:"rgba(255,255,255,0.06)"},margin:{t:50,r:30,b:50,l:60},showlegend:false};'
+ 'Plotly.newPlot("plot-speed-en",data,layout,{responsive:true,displayModeBar:false});'
+ '},200)</script>'

+ '<div class="calc-graph"><div class="graph-caption"><strong>What this graph shows:</strong> Adding one million numbers takes ~150 ms with a Python list comprehension but only ~2 ms with NumPy -- roughly 75x faster. The gap grows even larger for more complex operations like matrix multiplication.</div></div>'

+ '<div class="think-box"><div class="think-label">THINK ABOUT IT</div><div class="think-body">A neural network with 10 million parameters needs to compute gradients for every parameter at every training step. If each gradient computation took Python-loop time, training would take <em>weeks</em> instead of hours. This is why NumPy (and GPU libraries built on the same principle) matter.</div></div>'

/* ============================================================
   SECTION 2: ndarray Fundamentals
   ============================================================ */
+ '<h2 class="l-title">2. ndarray Fundamentals</h2>'

+ '<div class="calc-highlight"><strong>Core idea:</strong> The <code>ndarray</code> (n-dimensional array) is a <strong>grid of values, all of the same type</strong>, indexed by a tuple of non-negative integers. The number of dimensions is the <strong>rank</strong> of the array.</div>'

+ '<p class="l-text">Every ndarray has a set of attributes that describe its structure. Think of these as the array\'s "metadata" -- they tell you everything about the shape and memory layout without looking at the actual data.</p>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="kw">import</span> numpy <span class="kw">as</span> np\n\n<span class="cm"># Create a 2D array (matrix)</span>\narr = np.<span class="fn">array</span>([[<span class="num">1</span>, <span class="num">2</span>, <span class="num">3</span>],\n                [<span class="num">4</span>, <span class="num">5</span>, <span class="num">6</span>]])\n\n<span class="fn">print</span>(<span class="str">"Array:\\n"</span>, arr)\n<span class="fn">print</span>(<span class="str">"dtype   :"</span>, arr.dtype)      <span class="cm"># int64</span>\n<span class="fn">print</span>(<span class="str">"shape   :"</span>, arr.shape)      <span class="cm"># (2, 3) -- 2 rows, 3 columns</span>\n<span class="fn">print</span>(<span class="str">"ndim    :"</span>, arr.ndim)       <span class="cm"># 2 -- two dimensions</span>\n<span class="fn">print</span>(<span class="str">"size    :"</span>, arr.size)       <span class="cm"># 6 -- total elements</span>\n<span class="fn">print</span>(<span class="str">"itemsize:"</span>, arr.itemsize)   <span class="cm"># 8 -- bytes per element</span>\n<span class="fn">print</span>(<span class="str">"nbytes  :"</span>, arr.nbytes)     <span class="cm"># 48 -- total memory (6 x 8)</span></code></pre></div>'

+ '<div class="calc-cards"><div class="calc-card"><div class="card-title">Data Type</div><div class="card-body">The type of every element: int64, float32, bool, etc. All elements share one type -- this is what makes NumPy fast.</div></div><div class="calc-card"><div class="card-title">Shape</div><div class="card-body">A tuple giving the size of each dimension. (2, 3) means 2 rows and 3 columns. (4,) means a 1D array with 4 elements.</div></div><div class="calc-card"><div class="card-title">Number of Dimensions</div><div class="card-body">How many axes the array has. 1D = vector, 2D = matrix, 3D = tensor. Equal to len(shape).</div></div><div class="calc-card"><div class="card-title">Total Elements</div><div class="card-body">The product of all shape dimensions. A (2,3) array has 2 x 3 = 6 elements. A (3,4,5) array has 60.</div></div><div class="calc-card"><div class="card-title">Bytes per Element</div><div class="card-body">How many bytes one element occupies. int64 = 8 bytes, float32 = 4 bytes, int8 = 1 byte.</div></div><div class="calc-card"><div class="card-title">Total Memory</div><div class="card-body">Total bytes consumed: size x itemsize. A (1000, 1000) float64 array uses 8 MB.</div></div></div>'

+ '<p class="l-text">Understanding <strong>dimensionality terminology</strong> is essential for ML:</p>'

+ '<div class="calc-steps"><div class="calc-step"><div class="step-num">0D</div><div class="step-content"><div class="step-title">Scalar</div><div class="step-detail"><code>np.array(42)</code> -- shape: (), ndim: 0 -- a single number wrapped in an array</div></div></div><div class="calc-step"><div class="step-num">1D</div><div class="step-content"><div class="step-title">Vector</div><div class="step-detail"><code>np.array([1,2,3])</code> -- shape: (3,), ndim: 1 -- feature vector, word embedding, signal</div></div></div><div class="calc-step"><div class="step-num">2D</div><div class="step-content"><div class="step-title">Matrix</div><div class="step-detail"><code>np.array([[1,2],[3,4]])</code> -- shape: (2,2), ndim: 2 -- dataset, grayscale image, weight matrix</div></div></div><div class="calc-step"><div class="step-num">3D</div><div class="step-content"><div class="step-title">3D Tensor</div><div class="step-detail"><code>shape: (batch, rows, cols)</code> -- batch of sequences, RGB image, time series batch</div></div></div><div class="calc-step"><div class="step-num">4D</div><div class="step-content"><div class="step-title">4D Tensor</div><div class="step-detail"><code>shape: (batch, height, width, channels)</code> -- batch of color images in CNNs</div></div></div></div>'

/* --- Plotly: Memory Comparison EN --- */
+ '<div id="plot-memory-en" class="plotly-graph"></div>'
+ '<script>setTimeout(function(){'
+ 'var data=[{x:["Python list\\n(1M ints)","NumPy int64\\n(1M ints)","NumPy int32\\n(1M ints)","NumPy int8\\n(1M ints)"],y:[28,8,4,1],type:"bar",marker:{color:["#f87171","#c8a96e","#4ecdc4","#a78bfa"],line:{color:"rgba(255,255,255,0.2)",width:1}},text:["28 MB","8 MB","4 MB","1 MB"],textposition:"outside",textfont:{color:"#ebe6dc",size:12}}];'
+ 'var layout={title:{text:"Memory per 1M Elements: Python List vs NumPy dtypes",font:{color:"#ebe6dc",size:14}},paper_bgcolor:"rgba(0,0,0,0)",plot_bgcolor:"rgba(0,0,0,0)",font:{color:"#ebe6dc"},yaxis:{title:"Memory (MB)",gridcolor:"rgba(255,255,255,0.06)",zerolinecolor:"rgba(255,255,255,0.15)"},xaxis:{gridcolor:"rgba(255,255,255,0.06)"},margin:{t:50,r:30,b:70,l:60},showlegend:false};'
+ 'Plotly.newPlot("plot-memory-en",data,layout,{responsive:true,displayModeBar:false});'
+ '},200)</script>'

+ '<div class="calc-graph"><div class="graph-caption"><strong>What this graph shows:</strong> Storing 1 million integers in a Python list consumes ~28 MB (each int is a full Python object). NumPy with int64 uses 8 MB, int32 uses 4 MB, and int8 uses only 1 MB. Choosing the right dtype can reduce memory usage by 28x.</div></div>'

/* ============================================================
   SECTION 3: Array Creation Functions
   ============================================================ */
+ '<h2 class="l-title">3. Array Creation Functions</h2>'

+ '<div class="calc-highlight"><strong>Beyond np.array():</strong> NumPy provides dozens of factory functions to create arrays with specific patterns. You will use these constantly -- creating zero-initialized weight matrices, evenly-spaced evaluation points, random training data, and more.</div>'

+ '<p class="l-text"><strong>Filled arrays</strong> -- create arrays pre-loaded with a specific value:</p>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="kw">import</span> numpy <span class="kw">as</span> np\n\n<span class="cm"># zeros -- all elements are 0</span>\nz = np.<span class="fn">zeros</span>((<span class="num">3</span>, <span class="num">4</span>))          <span class="cm"># 3x4 matrix of zeros (float64 by default)</span>\nz32 = np.<span class="fn">zeros</span>((<span class="num">3</span>, <span class="num">4</span>), dtype=np.float32)  <span class="cm"># specify type</span>\n\n<span class="cm"># ones -- all elements are 1</span>\no = np.<span class="fn">ones</span>((<span class="num">2</span>, <span class="num">5</span>))            <span class="cm"># 2x5 matrix of ones</span>\n\n<span class="cm"># full -- all elements are your chosen value</span>\nf = np.<span class="fn">full</span>((<span class="num">3</span>, <span class="num">3</span>), <span class="num">7</span>)         <span class="cm"># 3x3 matrix filled with 7</span>\nf2 = np.<span class="fn">full</span>((<span class="num">2</span>, <span class="num">4</span>), np.pi)    <span class="cm"># filled with pi</span>\n\n<span class="cm"># empty -- allocates memory but does NOT initialize values</span>\ne = np.<span class="fn">empty</span>((<span class="num">2</span>, <span class="num">3</span>))           <span class="cm"># contains garbage values! fastest creation</span>\n\n<span class="cm"># eye -- identity matrix (1s on diagonal)</span>\ni4 = np.<span class="fn">eye</span>(<span class="num">4</span>)                 <span class="cm"># 4x4 identity matrix</span>\n<span class="fn">print</span>(i4)\n<span class="cm"># [[1. 0. 0. 0.]</span>\n<span class="cm">#  [0. 1. 0. 0.]</span>\n<span class="cm">#  [0. 0. 1. 0.]</span>\n<span class="cm">#  [0. 0. 0. 1.]]</span></code></pre></div>'

+ '<div class="l-note"><strong>When to use each:</strong> Use <code>zeros</code> for bias initialization, accumulator arrays, and placeholder tensors. Use <code>ones</code> for mask initialization. Use <code>full</code> for custom fill values. Use <code>empty</code> only when you know you will overwrite every element immediately (fastest but dangerous).</div>'

+ '<p class="l-text"><strong>Sequence arrays</strong> -- evenly spaced values:</p>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="cm"># arange -- like Python range() but returns ndarray</span>\na1 = np.<span class="fn">arange</span>(<span class="num">10</span>)             <span class="cm"># [0 1 2 3 4 5 6 7 8 9]</span>\na2 = np.<span class="fn">arange</span>(<span class="num">2</span>, <span class="num">10</span>)          <span class="cm"># [2 3 4 5 6 7 8 9]</span>\na3 = np.<span class="fn">arange</span>(<span class="num">0</span>, <span class="num">1</span>, <span class="num">0.2</span>)     <span class="cm"># [0.  0.2 0.4 0.6 0.8]</span>\na4 = np.<span class="fn">arange</span>(<span class="num">10</span>, <span class="num">0</span>, -<span class="num">2</span>)    <span class="cm"># [10  8  6  4  2]</span>\n\n<span class="cm"># linspace -- specify NUMBER of points (inclusive both ends)</span>\nl1 = np.<span class="fn">linspace</span>(<span class="num">0</span>, <span class="num">1</span>, <span class="num">5</span>)    <span class="cm"># [0.   0.25 0.5  0.75 1.  ]</span>\nl2 = np.<span class="fn">linspace</span>(<span class="num">0</span>, <span class="num">2</span>*np.pi, <span class="num">100</span>)  <span class="cm"># 100 points for plotting a sine wave</span>\n\n<span class="cm"># logspace -- log-spaced (10^start to 10^stop)</span>\nls = np.<span class="fn">logspace</span>(<span class="num">0</span>, <span class="num">3</span>, <span class="num">4</span>)    <span class="cm"># [1, 10, 100, 1000]</span>\nls2 = np.<span class="fn">logspace</span>(-<span class="num">3</span>, <span class="num">0</span>, <span class="num">4</span>)  <span class="cm"># [0.001, 0.01, 0.1, 1.0]  great for learning rates!</span></code></pre></div>'

+ '<div class="calc-compare"><div class="compare-col"><div class="compare-title">arange(start, stop, step)</div><div class="compare-item">Specify the step size between values</div><div class="compare-item">Stop value is excluded</div><div class="compare-item">Number of elements depends on step</div><div class="compare-item">Best for integer sequences</div></div><div class="compare-col"><div class="compare-title">linspace(start, stop, num)</div><div class="compare-item">Specify the number of points</div><div class="compare-item">Stop value is included</div><div class="compare-item">Step is automatically calculated</div><div class="compare-item">Best for plotting and evaluation</div></div></div>'

/* --- Plotly: linspace vs logspace EN --- */
+ '<div id="plot-spaces-en" class="plotly-graph"></div>'
+ '<script>setTimeout(function(){'
+ 'var lin={x:Array.from({length:10},function(_,i){return i}),y:Array.from({length:10},function(_,i){return i*111.1}),mode:"markers+lines",name:"linspace(0, 1000, 10)",marker:{color:"#4ecdc4",size:8},line:{color:"#4ecdc4",width:2}};'
+ 'var log={x:Array.from({length:10},function(_,i){return i}),y:[1,2.15,4.64,10,21.5,46.4,100,215,464,1000],mode:"markers+lines",name:"logspace(0, 3, 10)",marker:{color:"#c8a96e",size:8},line:{color:"#c8a96e",width:2}};'
+ 'var layout={title:{text:"linspace vs logspace: Even vs Logarithmic Spacing",font:{color:"#ebe6dc",size:14}},paper_bgcolor:"rgba(0,0,0,0)",plot_bgcolor:"rgba(0,0,0,0)",font:{color:"#ebe6dc"},yaxis:{title:"Value",gridcolor:"rgba(255,255,255,0.06)",zerolinecolor:"rgba(255,255,255,0.15)"},xaxis:{title:"Index",gridcolor:"rgba(255,255,255,0.06)"},margin:{t:50,r:30,b:50,l:60},showlegend:true,legend:{font:{color:"#ebe6dc"}}};'
+ 'Plotly.newPlot("plot-spaces-en",data=[lin,log],layout,{responsive:true,displayModeBar:false});'
+ '},200)</script>'

+ '<div class="calc-graph"><div class="graph-caption"><strong>What this graph shows:</strong> linspace produces evenly-spaced values (straight line), while logspace produces logarithmically-spaced values (exponential curve). logspace is essential for hyperparameter search -- learning rates span orders of magnitude (0.001 to 1.0).</div></div>'

+ '<p class="l-text"><strong>Random arrays</strong> -- essential for initialization and simulation:</p>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="cm"># Modern way: use np.random.default_rng()</span>\nrng = np.random.<span class="fn">default_rng</span>(seed=<span class="num">42</span>)  <span class="cm"># reproducible!</span>\n\n<span class="cm"># Uniform distribution [0, 1)</span>\nu = rng.<span class="fn">random</span>((<span class="num">3</span>, <span class="num">4</span>))           <span class="cm"># 3x4 matrix, values in [0, 1)</span>\n\n<span class="cm"># Normal (Gaussian) distribution, mean=0, std=1</span>\nn = rng.<span class="fn">standard_normal</span>((<span class="num">3</span>, <span class="num">4</span>))  <span class="cm"># 3x4, standard normal</span>\n\n<span class="cm"># Random integers</span>\ni = rng.<span class="fn">integers</span>(<span class="num">0</span>, <span class="num">10</span>, size=(<span class="num">3</span>, <span class="num">3</span>))  <span class="cm"># 3x3, integers in [0, 10)</span>\n\n<span class="cm"># Random choice from an array</span>\nc = rng.<span class="fn">choice</span>([<span class="str">"cat"</span>, <span class="str">"dog"</span>, <span class="str">"fish"</span>], size=<span class="num">5</span>)\n\n<span class="cm"># Legacy API (still commonly seen)</span>\nnp.random.<span class="fn">seed</span>(<span class="num">42</span>)\nnp.random.<span class="fn">rand</span>(<span class="num">3</span>, <span class="num">4</span>)       <span class="cm"># uniform [0, 1) -- note: no tuple!</span>\nnp.random.<span class="fn">randn</span>(<span class="num">3</span>, <span class="num">4</span>)      <span class="cm"># standard normal</span>\nnp.random.<span class="fn">randint</span>(<span class="num">0</span>, <span class="num">10</span>, (<span class="num">3</span>, <span class="num">3</span>))  <span class="cm"># random integers</span></code></pre></div>'

+ '<div class="l-note"><strong>Reproducibility:</strong> Always set a random seed when you need reproducible results! In ML experiments, this ensures your results can be replicated. Use the modern <code>default_rng(seed=42)</code> API -- it is faster and statistically better than the legacy <code>np.random.seed()</code> approach.</div>'

/* ============================================================
   SECTION 4: Data Types (dtype)
   ============================================================ */
+ '<h2 class="l-title">4. Data Types (dtype)</h2>'

+ '<div class="calc-highlight"><strong>Why dtype matters:</strong> The dtype determines (1) how much memory each element uses, (2) the range of values it can represent, and (3) the precision of computations. Choosing the right dtype is a key optimization in ML -- float32 is the sweet spot for most neural networks.</div>'

+ '<p class="l-text">NumPy supports many more data types than Python. Here is the complete reference:</p>'

+ '<div class="calc-cards"><div class="calc-card"><div class="card-title">int8</div><div class="card-body">1 byte, range: -128 to 127. Used for quantized models and small counters.</div></div><div class="calc-card"><div class="card-title">int16</div><div class="card-body">2 bytes, range: -32,768 to 32,767. Audio samples, small datasets.</div></div><div class="calc-card"><div class="card-title">int32</div><div class="card-body">4 bytes, range: ~-2.1B to ~2.1B. General integer work, indices.</div></div><div class="calc-card"><div class="card-title">int64</div><div class="card-body">8 bytes, range: ~-9.2 quintillion. Default for integers, timestamps.</div></div><div class="calc-card"><div class="card-title">float16</div><div class="card-body">2 bytes, ~3 decimal digits precision. Used in mixed-precision GPU training.</div></div><div class="calc-card"><div class="card-title">float32</div><div class="card-body">4 bytes, ~7 decimal digits. THE standard for ML/DL. Best speed/precision tradeoff.</div></div><div class="calc-card"><div class="card-title">float64</div><div class="card-body">8 bytes, ~15 decimal digits. Default for floats. Scientific computing, when precision matters.</div></div><div class="calc-card"><div class="card-title">bool_</div><div class="card-body">1 byte, True/False. Masks, boolean indexing, binary labels.</div></div></div>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="kw">import</span> numpy <span class="kw">as</span> np\n\n<span class="cm"># Automatic dtype inference</span>\na = np.<span class="fn">array</span>([<span class="num">1</span>, <span class="num">2</span>, <span class="num">3</span>])        <span class="cm"># int64 (integers)</span>\nb = np.<span class="fn">array</span>([<span class="num">1.0</span>, <span class="num">2.0</span>, <span class="num">3.0</span>])  <span class="cm"># float64 (has decimal)</span>\nc = np.<span class="fn">array</span>([<span class="num">1</span>, <span class="num">2</span>, <span class="num">3.0</span>])      <span class="cm"># float64 (mixed: upcasts to float)</span>\nd = np.<span class="fn">array</span>([<span class="kw">True</span>, <span class="kw">False</span>])    <span class="cm"># bool_</span>\n\n<span class="cm"># Explicit dtype</span>\ne = np.<span class="fn">array</span>([<span class="num">1</span>, <span class="num">2</span>, <span class="num">3</span>], dtype=np.float32)\n<span class="fn">print</span>(e)         <span class="cm"># [1. 2. 3.]</span>\n<span class="fn">print</span>(e.dtype)   <span class="cm"># float32</span>\n\n<span class="cm"># Type casting with astype()</span>\nf = e.<span class="fn">astype</span>(np.int8)\n<span class="fn">print</span>(f)         <span class="cm"># [1 2 3]</span>\n<span class="fn">print</span>(f.dtype)   <span class="cm"># int8</span>\n<span class="fn">print</span>(f.itemsize) <span class="cm"># 1 byte per element (was 4)</span>\n\n<span class="cm"># Memory comparison</span>\nbig = np.<span class="fn">ones</span>((<span class="num">1000</span>, <span class="num">1000</span>), dtype=np.float64)\nsmall = np.<span class="fn">ones</span>((<span class="num">1000</span>, <span class="num">1000</span>), dtype=np.float32)\n<span class="fn">print</span>(<span class="str">f"float64: {big.nbytes / 1e6:.1f} MB"</span>)   <span class="cm"># 8.0 MB</span>\n<span class="fn">print</span>(<span class="str">f"float32: {small.nbytes / 1e6:.1f} MB"</span>) <span class="cm"># 4.0 MB -- half!</span></code></pre></div>'

+ '<div class="calc-compare"><div class="compare-col"><div class="compare-title">Integer Types</div><div class="compare-item">int8: 1 byte, -128 to 127</div><div class="compare-item">int16: 2 bytes, -32K to 32K</div><div class="compare-item">int32: 4 bytes, -2.1B to 2.1B</div><div class="compare-item">int64: 8 bytes (default for ints)</div><div class="compare-item">uint8: 1 byte, 0 to 255 (images!)</div></div><div class="compare-col"><div class="compare-title">Float Types</div><div class="compare-item">float16: 2 bytes, ~3 digits precision</div><div class="compare-item">float32: 4 bytes, ~7 digits (ML standard)</div><div class="compare-item">float64: 8 bytes, ~15 digits (default)</div><div class="compare-item">complex64: 8 bytes (two float32)</div><div class="compare-item">complex128: 16 bytes (two float64)</div></div></div>'

+ '<div class="think-box"><div class="think-label">THINK ABOUT IT</div><div class="think-body">A GPT-2 model has ~124 million parameters. In float64, that requires 992 MB. In float32, it needs 496 MB. In float16, only 248 MB. Quantized to int8, just 124 MB. This is why <strong>model quantization</strong> is such a hot topic -- it makes large models fit on smaller devices.</div></div>'

/* ============================================================
   SECTION 5: Array Inspection & Reshaping
   ============================================================ */
+ '<h2 class="l-title">5. Array Inspection & Reshaping</h2>'

+ '<div class="calc-highlight"><strong>Reshaping is not just cosmetic:</strong> It changes how you access and process data. In ML, you constantly reshape arrays -- flattening images to feed into dense layers, adding batch dimensions, transposing weight matrices. Getting this wrong causes shape mismatch errors, the most common bug in deep learning.</div>'

+ '<p class="l-text"><strong>reshape()</strong> changes an array\'s shape without changing its data:</p>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="kw">import</span> numpy <span class="kw">as</span> np\n\na = np.<span class="fn">arange</span>(<span class="num">12</span>)   <span class="cm"># [ 0  1  2  3  4  5  6  7  8  9 10 11]</span>\n\n<span class="cm"># Reshape to different configurations</span>\nb = a.<span class="fn">reshape</span>(<span class="num">3</span>, <span class="num">4</span>)    <span class="cm"># 3 rows, 4 cols</span>\nc = a.<span class="fn">reshape</span>(<span class="num">4</span>, <span class="num">3</span>)    <span class="cm"># 4 rows, 3 cols</span>\nd = a.<span class="fn">reshape</span>(<span class="num">2</span>, <span class="num">2</span>, <span class="num">3</span>) <span class="cm"># 3D tensor: 2 matrices of 2x3</span>\n\n<span class="cm"># -1 means "calculate this dimension for me"</span>\ne = a.<span class="fn">reshape</span>(<span class="num">3</span>, -<span class="num">1</span>)   <span class="cm"># 3 x ? = 12, so ? = 4 --&gt; (3, 4)</span>\nf = a.<span class="fn">reshape</span>(-<span class="num">1</span>, <span class="num">1</span>)   <span class="cm"># ? x 1 = 12, so ? = 12 --&gt; (12, 1) column vector</span>\n\n<span class="cm"># Flatten: back to 1D</span>\ng = b.<span class="fn">ravel</span>()      <span class="cm"># returns a VIEW (shares memory with b)</span>\nh = b.<span class="fn">flatten</span>()    <span class="cm"># returns a COPY (independent from b)</span>\n\n<span class="cm"># Transpose: swap rows and columns</span>\n<span class="fn">print</span>(b.shape)     <span class="cm"># (3, 4)</span>\n<span class="fn">print</span>(b.T.shape)   <span class="cm"># (4, 3)</span></code></pre></div>'

+ '<div class="think-box"><div class="think-label">THINK ABOUT IT</div><div class="think-body"><strong>View vs Copy -- the critical distinction:</strong> A <strong>view</strong> shares memory with the original array. Modifying the view modifies the original. A <strong>copy</strong> is independent -- changes to the copy do not affect the original.<br><br><code>reshape()</code>, <code>ravel()</code>, <code>T</code>, and slicing return <strong>views</strong> (when possible).<br><code>flatten()</code>, <code>.copy()</code>, and fancy indexing return <strong>copies</strong>.<br><br>This matters enormously: views are memory-efficient (no duplication), but accidental mutation through a view is a common bug.</div></div>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="cm"># View vs Copy demonstration</span>\norig = np.<span class="fn">array</span>([<span class="num">1</span>, <span class="num">2</span>, <span class="num">3</span>, <span class="num">4</span>, <span class="num">5</span>, <span class="num">6</span>])\n\n<span class="cm"># reshape returns a VIEW</span>\nview = orig.<span class="fn">reshape</span>(<span class="num">2</span>, <span class="num">3</span>)\nview[<span class="num">0</span>, <span class="num">0</span>] = <span class="num">999</span>\n<span class="fn">print</span>(orig)  <span class="cm"># [999   2   3   4   5   6]  CHANGED!</span>\n\n<span class="cm"># .copy() creates independent copy</span>\norig2 = np.<span class="fn">array</span>([<span class="num">1</span>, <span class="num">2</span>, <span class="num">3</span>, <span class="num">4</span>, <span class="num">5</span>, <span class="num">6</span>])\ncopy = orig2.<span class="fn">reshape</span>(<span class="num">2</span>, <span class="num">3</span>).<span class="fn">copy</span>()\ncopy[<span class="num">0</span>, <span class="num">0</span>] = <span class="num">999</span>\n<span class="fn">print</span>(orig2) <span class="cm"># [1 2 3 4 5 6]  unchanged!</span>\n\n<span class="cm"># Check if something is a view</span>\n<span class="fn">print</span>(view.base <span class="kw">is</span> orig)   <span class="cm"># True -- view shares orig\'s memory</span>\n<span class="fn">print</span>(copy.base <span class="kw">is</span> orig2)  <span class="cm"># False -- copy is independent</span></code></pre></div>'

+ '<p class="l-text"><strong>Memory layout: C-order vs F-order</strong></p>'

+ '<div class="calc-compare"><div class="compare-col"><div class="compare-title">C-order (Row-major)</div><div class="compare-item">Default in NumPy</div><div class="compare-item">Rows are stored contiguously</div><div class="compare-item">Last index changes fastest</div><div class="compare-item">Best for row-wise operations</div></div><div class="compare-col"><div class="compare-title">F-order (Column-major)</div><div class="compare-item">Default in Fortran, MATLAB</div><div class="compare-item">Columns are stored contiguously</div><div class="compare-item">First index changes fastest</div><div class="compare-item">Best for column-wise operations</div></div></div>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="cm"># C-order (default) vs F-order</span>\na = np.<span class="fn">array</span>([[<span class="num">1</span>, <span class="num">2</span>, <span class="num">3</span>],\n              [<span class="num">4</span>, <span class="num">5</span>, <span class="num">6</span>]], order=<span class="str">"C"</span>)\n\n<span class="cm"># In memory (C-order): [1, 2, 3, 4, 5, 6] -- row by row</span>\n<span class="fn">print</span>(a.<span class="fn">ravel</span>(order=<span class="str">"C"</span>))  <span class="cm"># [1 2 3 4 5 6]</span>\n\n<span class="cm"># In memory (F-order): [1, 4, 2, 5, 3, 6] -- column by column</span>\n<span class="fn">print</span>(a.<span class="fn">ravel</span>(order=<span class="str">"F"</span>))  <span class="cm"># [1 4 2 5 3 6]</span>\n\n<span class="cm"># Check current order</span>\n<span class="fn">print</span>(a.flags[<span class="str">"C_CONTIGUOUS"</span>])  <span class="cm"># True</span>\n<span class="fn">print</span>(a.flags[<span class="str">"F_CONTIGUOUS"</span>])  <span class="cm"># False</span></code></pre></div>'

/* ============================================================
   SECTION 6: Practical Patterns
   ============================================================ */
+ '<h2 class="l-title">6. Practical Patterns</h2>'

+ '<div class="calc-highlight"><strong>Real-world usage:</strong> Now that you know the building blocks, let\'s see how they combine in practice. These patterns appear in virtually every ML project.</div>'

+ '<p class="l-text"><strong>Pattern 1: Creating synthetic ML datasets</strong></p>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="kw">import</span> numpy <span class="kw">as</span> np\nrng = np.random.<span class="fn">default_rng</span>(<span class="num">42</span>)\n\n<span class="cm"># Synthetic linear regression dataset</span>\nn_samples = <span class="num">100</span>\nn_features = <span class="num">3</span>\n\nX = rng.<span class="fn">standard_normal</span>((n_samples, n_features))  <span class="cm"># 100x3 feature matrix</span>\ntrue_weights = np.<span class="fn">array</span>([<span class="num">2.5</span>, -<span class="num">1.0</span>, <span class="num">0.5</span>])\nnoise = rng.<span class="fn">standard_normal</span>(n_samples) * <span class="num">0.1</span>\ny = X @ true_weights + noise  <span class="cm"># @ = matrix multiply</span>\n\n<span class="fn">print</span>(<span class="str">f"Features: {X.shape}"</span>)  <span class="cm"># (100, 3)</span>\n<span class="fn">print</span>(<span class="str">f"Labels:   {y.shape}"</span>)  <span class="cm"># (100,)</span></code></pre></div>'

+ '<p class="l-text"><strong>Pattern 2: meshgrid for 2D evaluation</strong></p>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="cm"># Create a 2D grid for plotting decision boundaries</span>\nx1 = np.<span class="fn">linspace</span>(-<span class="num">3</span>, <span class="num">3</span>, <span class="num">100</span>)\nx2 = np.<span class="fn">linspace</span>(-<span class="num">3</span>, <span class="num">3</span>, <span class="num">100</span>)\nX1, X2 = np.<span class="fn">meshgrid</span>(x1, x2)  <span class="cm"># two 100x100 grids</span>\n\n<span class="fn">print</span>(X1.shape)  <span class="cm"># (100, 100) -- x1 values repeated across rows</span>\n<span class="fn">print</span>(X2.shape)  <span class="cm"># (100, 100) -- x2 values repeated across columns</span>\n\n<span class="cm"># Evaluate a function at every grid point</span>\nZ = np.<span class="fn">sin</span>(X1) * np.<span class="fn">cos</span>(X2)  <span class="cm"># 100x100 result</span></code></pre></div>'

/* --- Plotly: Meshgrid 3D Surface EN --- */
+ '<div id="plot-meshgrid-en" class="plotly-graph"></div>'
+ '<script>setTimeout(function(){'
+ 'var N=40;var x=[];var y=[];for(var i=0;i<N;i++){x.push(-3+6*i/(N-1));y.push(-3+6*i/(N-1))}'
+ 'var z=[];for(var j=0;j<N;j++){var row=[];for(var i=0;i<N;i++){row.push(Math.sin(x[i])*Math.cos(y[j]))}z.push(row)}'
+ 'var data=[{z:z,x:x,y:y,type:"surface",colorscale:[[0,"#1a1a2e"],[0.25,"#4ecdc4"],[0.5,"#c8a96e"],[0.75,"#f87171"],[1,"#a78bfa"]],showscale:false}];'
+ 'var layout={title:{text:"meshgrid Surface: sin(x) * cos(y)",font:{color:"#ebe6dc",size:14}},paper_bgcolor:"rgba(0,0,0,0)",plot_bgcolor:"rgba(0,0,0,0)",font:{color:"#ebe6dc"},scene:{xaxis:{title:"x1",gridcolor:"rgba(255,255,255,0.1)"},yaxis:{title:"x2",gridcolor:"rgba(255,255,255,0.1)"},zaxis:{title:"f(x1,x2)",gridcolor:"rgba(255,255,255,0.1)"},bgcolor:"rgba(0,0,0,0)"},margin:{t:50,r:10,b:10,l:10}};'
+ 'Plotly.newPlot("plot-meshgrid-en",data,layout,{responsive:true,displayModeBar:false});'
+ '},200)</script>'

+ '<div class="calc-graph"><div class="graph-caption"><strong>What this graph shows:</strong> A 3D surface created by evaluating sin(x1) * cos(x2) on a meshgrid. This is exactly how decision boundary visualizations and loss surfaces are plotted in ML.</div></div>'

+ '<p class="l-text"><strong>Pattern 3: Stacking and splitting arrays</strong></p>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="cm"># Stacking arrays together</span>\na = np.<span class="fn">array</span>([<span class="num">1</span>, <span class="num">2</span>, <span class="num">3</span>])\nb = np.<span class="fn">array</span>([<span class="num">4</span>, <span class="num">5</span>, <span class="num">6</span>])\n\n<span class="cm"># Vertical stack (add rows)</span>\nv = np.<span class="fn">vstack</span>([a, b])     <span class="cm"># [[1,2,3], [4,5,6]]  shape: (2,3)</span>\n\n<span class="cm"># Horizontal stack (add columns)</span>\nh = np.<span class="fn">hstack</span>([a, b])     <span class="cm"># [1,2,3,4,5,6]  shape: (6,)</span>\n\n<span class="cm"># Column stack (1D arrays become columns)</span>\nc = np.<span class="fn">column_stack</span>([a, b])  <span class="cm"># [[1,4], [2,5], [3,6]]  shape: (3,2)</span>\n\n<span class="cm"># Concatenate along any axis</span>\nm1 = np.<span class="fn">ones</span>((<span class="num">2</span>, <span class="num">3</span>))\nm2 = np.<span class="fn">zeros</span>((<span class="num">2</span>, <span class="num">3</span>))\nnp.<span class="fn">concatenate</span>([m1, m2], axis=<span class="num">0</span>)  <span class="cm"># (4,3) -- stack vertically</span>\nnp.<span class="fn">concatenate</span>([m1, m2], axis=<span class="num">1</span>)  <span class="cm"># (2,6) -- stack horizontally</span>\n\n<span class="cm"># Splitting arrays apart</span>\nbig = np.<span class="fn">arange</span>(<span class="num">12</span>).<span class="fn">reshape</span>(<span class="num">3</span>, <span class="num">4</span>)\nrows = np.<span class="fn">vsplit</span>(big, <span class="num">3</span>)     <span class="cm"># list of 3 arrays, each (1,4)</span>\ncols = np.<span class="fn">hsplit</span>(big, <span class="num">2</span>)     <span class="cm"># list of 2 arrays, each (3,2)</span></code></pre></div>'

+ '<p class="l-text"><strong>Pattern 4: Saving and loading arrays</strong></p>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="cm"># Save single array (.npy format -- binary, fast)</span>\narr = np.<span class="fn">arange</span>(<span class="num">1000</span>)\nnp.<span class="fn">save</span>(<span class="str">"my_array.npy"</span>, arr)\nloaded = np.<span class="fn">load</span>(<span class="str">"my_array.npy"</span>)\n\n<span class="cm"># Save multiple arrays (.npz format)</span>\nnp.<span class="fn">savez</span>(<span class="str">"data.npz"</span>, features=X, labels=y)\ndata = np.<span class="fn">load</span>(<span class="str">"data.npz"</span>)\n<span class="fn">print</span>(data[<span class="str">"features"</span>].shape)  <span class="cm"># access by name</span>\n\n<span class="cm"># Save compressed (smaller file)</span>\nnp.<span class="fn">savez_compressed</span>(<span class="str">"data_compressed.npz"</span>, features=X, labels=y)\n\n<span class="cm"># Save as human-readable text</span>\nnp.<span class="fn">savetxt</span>(<span class="str">"data.csv"</span>, arr.<span class="fn">reshape</span>(<span class="num">10</span>, <span class="num">100</span>), delimiter=<span class="str">","</span>)\nloaded_csv = np.<span class="fn">loadtxt</span>(<span class="str">"data.csv"</span>, delimiter=<span class="str">","</span>)</code></pre></div>'

+ '<div class="l-note"><strong>Best practice:</strong> Use <code>.npy/.npz</code> for intermediate results (fast, preserves dtypes). Use <code>.csv</code> only when you need human-readable output or interoperability with other tools like Excel or Pandas.</div>'

+ '<div class="calc-example"><div class="example-label">COMPLETE EXAMPLE: Image as Array</div><div class="example-body">A 28x28 grayscale image (like MNIST digits) is a 2D array of shape (28, 28) with uint8 values (0-255).<br><br><strong>Step 1:</strong> Load as 2D: shape (28, 28), 784 pixels<br><strong>Step 2:</strong> Flatten for dense layer: <code>img.reshape(-1)</code> gives shape (784,)<br><strong>Step 3:</strong> Add batch dimension: <code>img.reshape(1, 28, 28)</code> gives shape (1, 28, 28)<br><strong>Step 4:</strong> Normalize: <code>img.astype(np.float32) / 255.0</code> scales to [0, 1]<br><strong>Step 5:</strong> For CNN: <code>img.reshape(1, 1, 28, 28)</code> gives (batch, channels, height, width)</div></div>'

+ '<div class="think-box"><div class="think-label">KEY TAKEAWAYS</div><div class="think-body"><strong>1.</strong> NumPy is 10-100x faster than Python lists because of C backend, vectorization, and contiguous memory.<br><strong>2.</strong> The ndarray has key attributes: dtype, shape, ndim, size, itemsize, nbytes.<br><strong>3.</strong> Use zeros/ones/full/arange/linspace/random to create arrays for any purpose.<br><strong>4.</strong> Choose your dtype wisely: float32 for ML, int8 for quantization, float64 for scientific precision.<br><strong>5.</strong> reshape/ravel/T return views (shared memory). flatten/.copy() return independent copies.<br><strong>6.</strong> Master stacking, splitting, meshgrid, and save/load for real-world data pipelines.</div></div>',


/* ============================================================
   TURKISH TRANSLATION
   ============================================================ */

tr: '<div class="math-prereq" style="background:rgba(245,158,11,0.07);border-left:3px solid #f59e0b;padding:0.95rem 1.2rem;margin:0 0 1.5rem 0;border-radius:0 8px 8px 0"><div style="font-size:0.74rem;font-weight:700;letter-spacing:0.1em;color:#f59e0b;margin-bottom:0.5rem">📐 MATEMATİK TEMELLERİ</div><p style="margin:0 0 0.55rem 0;font-size:0.9rem;line-height:1.55;color:rgba(235,230,220,0.85)">Burada kullanılan matematiğe yeni misin? Önce şu temelleri tazele — her biri bağımsız bir Matematik dersi:</p><ul style="margin:0;padding-left:1.25rem;font-size:0.88rem;line-height:1.7;color:rgba(235,230,220,0.85);list-style:none"><li><a href="/tutorials/matematik/40" style="color:#f59e0b;text-decoration:none;border-bottom:1px dotted #f59e0b">Fonksiyon Tanımı</a> <span style="opacity:0.55;font-size:0.82em">(Matematik L40)</span></li><li><a href="/tutorials/matematik/72" style="color:#f59e0b;text-decoration:none;border-bottom:1px dotted #f59e0b">Matris &amp; İşlemler</a> <span style="opacity:0.55;font-size:0.82em">(Matematik L72)</span></li><li><a href="/tutorials/matematik/91" style="color:#f59e0b;text-decoration:none;border-bottom:1px dotted #f59e0b">Vektörler</a> <span style="opacity:0.55;font-size:0.82em">(Matematik L91)</span></li></ul></div><p class="l-text"><strong>NumPy, Python\'da bilimsel hesaplamanın temel taşıdır.</strong> Kullanacağınız her makine öğrenmesi kütüphanesi -- scikit-learn, TensorFlow, PyTorch, Pandas -- NumPy dizileri üzerine inşa edilmiştir. Bu dizileri oluşturmayı, incelemeyi ve manipüle etmeyi anlamak, her veri bilimci ve ML mühendisi için en önemli beceridir.</p>'

+ '<p class="l-text">Bu ders sizi sıfırdan başlatıp güvenli bir seviyeye taşır: NumPy neden var, temel nesnesi (<strong>ndarray</strong>) nasıl çalışır, ihtiyaç duyacağınız her oluşturma fonksiyonu, veri tipleri, yeniden şekillendirme ve her gün kullanacağınız gerçek dünya kalıpları.</p>'
+ '<div class="lesson-outcomes" style="background:rgba(200,169,110,0.06);border-left:3px solid #c8a96e;padding:1rem 1.2rem;margin:1.5rem 0;border-radius:0 8px 8px 0"><div style="font-size:0.78rem;font-weight:700;letter-spacing:0.08em;color:#c8a96e;margin-bottom:0.6rem">📍 BU DERSTE ÖĞRENECEKSİN</div><ul style="margin:0;padding-left:1.3rem;line-height:1.65;font-size:0.93rem;color:rgba(235,230,220,0.92)"><li>NumPy\'nin Python listelerinden neden 10–100 kat hızlı olduğunu açıkla</li><li>zeros, ones, full, eye, arange, linspace ve logspace ile ndarray oluştur</li><li>shape, dtype, ndim, size, itemsize ve nbytes niteliklerini incele</li><li>Hassasiyet ve bellek dengesi için doğru dtype\'ı seç</li><li>Dizileri yeniden şekillendir ve 1B vektör, 2B matris, 3B+ tensör mantığını kavra</li></ul></div>'


/* ============================================================
   BÖLÜM 1: Neden NumPy?
   ============================================================ */
+ '<h2 class="l-title">1. Neden NumPy?</h2>'

+ '<div class="calc-highlight"><strong>Kısa cevap:</strong> Python listeleri yavaştır. NumPy dizileri hızlıdır. Sayısal çalışmalar için NumPy, saf Python\'dan <strong>10 ila 100 kat daha hızlıdır</strong> çünkü hesaplamayı optimize edilmiş C/Fortran koduna devreder ve ardışık bellek blokları üzerinde çalışır.</div>'

+ '<p class="l-text">1 milyon sayıdan oluşan iki listeyi toplamayı düşünün. Saf Python\'da, her adımda Python yorumlayıcısını çağıran bir milyon iterasyonluk bir for döngüsü gerekir. NumPy bu döngünün tamamını <strong>vektörizasyon</strong> adı verilen <strong>tek bir C seviyesi işlemle</strong> değiştirir.</p>'

+ '<div class="calc-cards"><div class="calc-card"><div class="card-title">C Altyapısı</div><div class="card-body">NumPy\'ın çekirdeği C ve Fortran ile yazılmıştır. Python kodunuz arka planda hızlı derlenmiş rutinleri çağırır -- eleman başına yorumlayıcı yükü yoktur.</div></div><div class="calc-card"><div class="card-title">Vektörizasyon</div><div class="card-body">Eleman eleman döngü yerine bir işlemi tüm diziye aynı anda uygulayın. Bir satır kod bir for döngüsünün yerini alır.</div></div><div class="calc-card"><div class="card-title">Ardışık Bellek</div><div class="card-body">Tüm elemanlar bellekte yan yana oturur. Bu, CPU önbellek verimliliği ve SIMD komutlarını mümkün kılar -- donanım seviyesinde paralellik.</div></div><div class="calc-card"><div class="card-title">Sabit Tipler</div><div class="card-body">Her eleman aynı veri tipindedir (ör: float64). Eleman başına tip kontrolü yoktur, CPU verileri hızla işleyebilir.</div></div></div>'

+ '<div class="calc-compare"><div class="compare-col"><div class="compare-title">Python Listesi</div><div class="compare-item">Her eleman tam bir Python nesnesidir (28+ byte)</div><div class="compare-item">Her işlemde tip kontrolü yapılır</div><div class="compare-item">Elemanlar bellekte dağınıktır</div><div class="compare-item">İşlem uygulamak için döngü gerekir</div><div class="compare-item">Esnek: tipler karışabilir [1, "merhaba", 3.14]</div></div><div class="compare-col"><div class="compare-title">NumPy Dizisi</div><div class="compare-item">Her eleman ham sayıdır (4-8 byte)</div><div class="compare-item">Tek tip -- eleman başına kontrol yok</div><div class="compare-item">Ardışık bellek bloğu</div><div class="compare-item">Vektörize: tek çağrı tüm elemanları işler</div><div class="compare-item">Katı: tüm elemanlar aynı tipte olmalı</div></div></div>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="kw">import</span> numpy <span class="kw">as</span> np\n<span class="kw">import</span> time\n\nsize = <span class="num">1_000_000</span>\n\n<span class="cm"># Python listesi yaklaşımı</span>\npy_a = <span class="fn">list</span>(<span class="fn">range</span>(size))\npy_b = <span class="fn">list</span>(<span class="fn">range</span>(size))\n\nstart = time.<span class="fn">time</span>()\npy_c = [a + b <span class="kw">for</span> a, b <span class="kw">in</span> <span class="fn">zip</span>(py_a, py_b)]\npy_time = time.<span class="fn">time</span>() - start\n\n<span class="cm"># NumPy yaklaşımı</span>\nnp_a = np.<span class="fn">arange</span>(size)\nnp_b = np.<span class="fn">arange</span>(size)\n\nstart = time.<span class="fn">time</span>()\nnp_c = np_a + np_b   <span class="cm"># vektörize -- döngü yok!</span>\nnp_time = time.<span class="fn">time</span>() - start\n\n<span class="fn">print</span>(<span class="str">f"Python listesi: {py_time:.4f}s"</span>)  <span class="cm"># ~0.15s</span>\n<span class="fn">print</span>(<span class="str">f"NumPy dizisi:  {np_time:.4f}s"</span>)  <span class="cm"># ~0.002s</span>\n<span class="fn">print</span>(<span class="str">f"NumPy {py_time/np_time:.0f}x daha hızlı"</span>)</code></pre></div>'

/* --- Plotly: Hız Karşılaştırması TR --- */
+ '<div id="plot-speed-tr" class="plotly-graph"></div>'
+ '<script>setTimeout(function(){'
+ 'var data=[{x:["Python Liste Döngüsü","NumPy Vektörize"],y:[150,2],type:"bar",marker:{color:["#f87171","#4de87a"],line:{color:"rgba(255,255,255,0.2)",width:1}},text:["~150 ms","~2 ms"],textposition:"outside",textfont:{color:"#ebe6dc",size:13}}];'
+ 'var layout={title:{text:"1M Sayı Toplama: Python Liste vs NumPy",font:{color:"#ebe6dc",size:14}},paper_bgcolor:"rgba(0,0,0,0)",plot_bgcolor:"rgba(0,0,0,0)",font:{color:"#ebe6dc"},yaxis:{title:"Süre (ms)",gridcolor:"rgba(255,255,255,0.06)",zerolinecolor:"rgba(255,255,255,0.15)"},xaxis:{gridcolor:"rgba(255,255,255,0.06)"},margin:{t:50,r:30,b:50,l:60},showlegend:false};'
+ 'Plotly.newPlot("plot-speed-tr",data,layout,{responsive:true,displayModeBar:false});'
+ '},200)</script>'

+ '<div class="calc-graph"><div class="graph-caption"><strong>Grafiğin özü:</strong> Bir milyon sayıyı toplamak Python liste kavramasıyla ~150 ms sürerken, NumPy ile yalnızca ~2 ms sürer -- yaklaşık 75 kat daha hızlı. Matris çarpımı gibi daha karmaşık işlemlerde fark daha da büyür.</div></div>'

+ '<div class="think-box"><div class="think-label">DÜŞÜNÜN</div><div class="think-body">10 milyon parametreli bir sinir ağı, her eğitim adımında her parametre için gradyan hesaplaması gerektirir. Her gradyan hesaplaması Python döngüsü hızında olsaydı, eğitim saatler yerine <em>haftalar</em> sürerdi. NumPy\'ın (ve aynı prensipte inşa edilen GPU kütüphanelerinin) önemi budur.</div></div>'

/* ============================================================
   BÖLÜM 2: ndarray Temelleri
   ============================================================ */
+ '<h2 class="l-title">2. ndarray Temelleri</h2>'

+ '<div class="calc-highlight"><strong>Temel fikir:</strong> <code>ndarray</code> (n-boyutlu dizi), <strong>hepsi aynı tipte değerlerden oluşan</strong>, negatif olmayan tamsayılardan oluşan bir demet (tuple) ile indekslenen bir değerler ızgarasıdır. Boyut sayısı dizinin <strong>derecesidir</strong> (rank).</div>'

+ '<p class="l-text">Her ndarray\'in yapısını tanımlayan bir dizi niteliği vardır. Bunları dizinin "üst verisi" olarak düşünün -- gerçek verilere bakmadan şekil ve bellek düzeni hakkında her şeyi söylerler.</p>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="kw">import</span> numpy <span class="kw">as</span> np\n\n<span class="cm"># 2B dizi (matris) oluştur</span>\narr = np.<span class="fn">array</span>([[<span class="num">1</span>, <span class="num">2</span>, <span class="num">3</span>],\n                [<span class="num">4</span>, <span class="num">5</span>, <span class="num">6</span>]])\n\n<span class="fn">print</span>(<span class="str">"Dizi:\\n"</span>, arr)\n<span class="fn">print</span>(<span class="str">"dtype   :"</span>, arr.dtype)      <span class="cm"># int64</span>\n<span class="fn">print</span>(<span class="str">"shape   :"</span>, arr.shape)      <span class="cm"># (2, 3) -- 2 satır, 3 sütun</span>\n<span class="fn">print</span>(<span class="str">"ndim    :"</span>, arr.ndim)       <span class="cm"># 2 -- iki boyut</span>\n<span class="fn">print</span>(<span class="str">"size    :"</span>, arr.size)       <span class="cm"># 6 -- toplam eleman</span>\n<span class="fn">print</span>(<span class="str">"itemsize:"</span>, arr.itemsize)   <span class="cm"># 8 -- eleman başına byte</span>\n<span class="fn">print</span>(<span class="str">"nbytes  :"</span>, arr.nbytes)     <span class="cm"># 48 -- toplam bellek (6 x 8)</span></code></pre></div>'

+ '<div class="calc-cards"><div class="calc-card"><div class="card-title">Veri Tipi</div><div class="card-body">Her elemanın tipi: int64, float32, bool, vb. Tüm elemanlar aynı tipi paylaşır -- NumPy\'ı hızlı yapan budur.</div></div><div class="calc-card"><div class="card-title">Şekil</div><div class="card-body">Her boyutun büyüklüğünü veren bir demet. (2, 3) = 2 satır ve 3 sütun. (4,) = 4 elemanlı 1B dizi.</div></div><div class="calc-card"><div class="card-title">Boyut Sayısı</div><div class="card-body">Dizinin kaç eksenine sahip olduğu. 1B = vektör, 2B = matris, 3B = tensör. len(shape)\'e eşittir.</div></div><div class="calc-card"><div class="card-title">Toplam Eleman</div><div class="card-body">Tüm şekil boyutlarının çarpımı. (2,3) dizisi 2 x 3 = 6 elemana sahiptir. (3,4,5) dizisi 60.</div></div><div class="calc-card"><div class="card-title">Eleman Başına Byte</div><div class="card-body">Bir elemanın kapladığı byte sayısı. int64 = 8 byte, float32 = 4 byte, int8 = 1 byte.</div></div><div class="calc-card"><div class="card-title">Toplam Bellek</div><div class="card-body">Toplam tüketilen byte: size x itemsize. (1000, 1000) float64 dizisi 8 MB kullanır.</div></div></div>'

+ '<p class="l-text">ML için <strong>boyutluluk terminolojisini</strong> anlamak çok önemlidir:</p>'

+ '<div class="calc-steps"><div class="calc-step"><div class="step-num">0B</div><div class="step-content"><div class="step-title">Skaler</div><div class="step-detail"><code>np.array(42)</code> -- şekil: (), ndim: 0 -- bir diziye sarılmış tek sayı</div></div></div><div class="calc-step"><div class="step-num">1B</div><div class="step-content"><div class="step-title">Vektör</div><div class="step-detail"><code>np.array([1,2,3])</code> -- şekil: (3,), ndim: 1 -- öznitelik vektörü, kelime gömme, sinyal</div></div></div><div class="calc-step"><div class="step-num">2B</div><div class="step-content"><div class="step-title">Matris</div><div class="step-detail"><code>np.array([[1,2],[3,4]])</code> -- şekil: (2,2), ndim: 2 -- veri seti, gri tonlamalı görüntü, ağırlık matrisi</div></div></div><div class="calc-step"><div class="step-num">3B</div><div class="step-content"><div class="step-title">3B Tensör</div><div class="step-detail"><code>şekil: (batch, satır, sütun)</code> -- dizi partisi, RGB görüntü, zaman serisi partisi</div></div></div><div class="calc-step"><div class="step-num">4B</div><div class="step-content"><div class="step-title">4B Tensör</div><div class="step-detail"><code>şekil: (batch, yükseklik, genişlik, kanal)</code> -- CNN\'lerde renkli görüntü partisi</div></div></div></div>'

/* --- Plotly: Bellek Karşılaştırması TR --- */
+ '<div id="plot-memory-tr" class="plotly-graph"></div>'
+ '<script>setTimeout(function(){'
+ 'var data=[{x:["Python listesi\\n(1M int)","NumPy int64\\n(1M int)","NumPy int32\\n(1M int)","NumPy int8\\n(1M int)"],y:[28,8,4,1],type:"bar",marker:{color:["#f87171","#c8a96e","#4ecdc4","#a78bfa"],line:{color:"rgba(255,255,255,0.2)",width:1}},text:["28 MB","8 MB","4 MB","1 MB"],textposition:"outside",textfont:{color:"#ebe6dc",size:12}}];'
+ 'var layout={title:{text:"1M Eleman Başına Bellek: Python Liste vs NumPy dtype\'ları",font:{color:"#ebe6dc",size:14}},paper_bgcolor:"rgba(0,0,0,0)",plot_bgcolor:"rgba(0,0,0,0)",font:{color:"#ebe6dc"},yaxis:{title:"Bellek (MB)",gridcolor:"rgba(255,255,255,0.06)",zerolinecolor:"rgba(255,255,255,0.15)"},xaxis:{gridcolor:"rgba(255,255,255,0.06)"},margin:{t:50,r:30,b:70,l:60},showlegend:false};'
+ 'Plotly.newPlot("plot-memory-tr",data,layout,{responsive:true,displayModeBar:false});'
+ '},200)</script>'

+ '<div class="calc-graph"><div class="graph-caption"><strong>Buradaki resim:</strong> 1 milyon tamsayıyı Python listesinde saklamak ~28 MB tüketir (her int tam Python nesnesidir). NumPy int64 ile 8 MB, int32 ile 4 MB, int8 ile yalnızca 1 MB kullanılır. Doğru dtype seçmek bellek kullanımını 28 kata kadar azaltabilir.</div></div>'

/* ============================================================
   BÖLÜM 3: Dizi Oluşturma Fonksiyonları
   ============================================================ */
+ '<h2 class="l-title">3. Dizi Oluşturma Fonksiyonları</h2>'

+ '<div class="calc-highlight"><strong>np.array() ötesinde:</strong> NumPy, belirli kalıplarda diziler oluşturmak için düzinelerce fabrika fonksiyonu sağlar. Bunları sürekli kullanacaksınız -- sıfır başlatılmış ağırlık matrisleri, eşit aralıklı değerlendirme noktaları, rastgele eğitim verisi ve daha fazlası.</div>'

+ '<p class="l-text"><strong>Doldurulmuş diziler</strong> -- belirli bir değerle önceden yüklenmiş diziler oluşturun:</p>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="kw">import</span> numpy <span class="kw">as</span> np\n\n<span class="cm"># zeros -- tüm elemanlar 0</span>\nz = np.<span class="fn">zeros</span>((<span class="num">3</span>, <span class="num">4</span>))          <span class="cm"># 3x4 sıfır matrisi (varsayılan float64)</span>\nz32 = np.<span class="fn">zeros</span>((<span class="num">3</span>, <span class="num">4</span>), dtype=np.float32)  <span class="cm"># tip belirt</span>\n\n<span class="cm"># ones -- tüm elemanlar 1</span>\no = np.<span class="fn">ones</span>((<span class="num">2</span>, <span class="num">5</span>))            <span class="cm"># 2x5 birler matrisi</span>\n\n<span class="cm"># full -- tüm elemanlar seçtiğiniz değer</span>\nf = np.<span class="fn">full</span>((<span class="num">3</span>, <span class="num">3</span>), <span class="num">7</span>)         <span class="cm"># 3x3 matris 7 ile doldurulmuş</span>\nf2 = np.<span class="fn">full</span>((<span class="num">2</span>, <span class="num">4</span>), np.pi)    <span class="cm"># pi ile doldurulmuş</span>\n\n<span class="cm"># empty -- bellek ayırır ama değerleri başlatmaz</span>\ne = np.<span class="fn">empty</span>((<span class="num">2</span>, <span class="num">3</span>))           <span class="cm"># çöp değerler içerir! en hızlı oluşturma</span>\n\n<span class="cm"># eye -- birim matris (köşegende 1\'ler)</span>\ni4 = np.<span class="fn">eye</span>(<span class="num">4</span>)                 <span class="cm"># 4x4 birim matris</span>\n<span class="fn">print</span>(i4)\n<span class="cm"># [[1. 0. 0. 0.]</span>\n<span class="cm">#  [0. 1. 0. 0.]</span>\n<span class="cm">#  [0. 0. 1. 0.]</span>\n<span class="cm">#  [0. 0. 0. 1.]]</span></code></pre></div>'

+ '<div class="l-note"><strong>Ne zaman hangisini kullanmalı:</strong> Bias başlatma, toplayıcı diziler ve yer tutucu tensörler için <code>zeros</code> kullanın. Maske başlatma için <code>ones</code> kullanın. Özel dolgu değerleri için <code>full</code> kullanın. <code>empty</code>\'yi yalnızca her elemanı hemen üzerine yazacağınızı bildiğinizde kullanın (en hızlı ama tehlikeli).</div>'

+ '<p class="l-text"><strong>Dizi dizileri</strong> -- eşit aralıklı değerler:</p>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="cm"># arange -- Python range() gibi ama ndarray döndürür</span>\na1 = np.<span class="fn">arange</span>(<span class="num">10</span>)             <span class="cm"># [0 1 2 3 4 5 6 7 8 9]</span>\na2 = np.<span class="fn">arange</span>(<span class="num">2</span>, <span class="num">10</span>)          <span class="cm"># [2 3 4 5 6 7 8 9]</span>\na3 = np.<span class="fn">arange</span>(<span class="num">0</span>, <span class="num">1</span>, <span class="num">0.2</span>)     <span class="cm"># [0.  0.2 0.4 0.6 0.8]</span>\na4 = np.<span class="fn">arange</span>(<span class="num">10</span>, <span class="num">0</span>, -<span class="num">2</span>)    <span class="cm"># [10  8  6  4  2]</span>\n\n<span class="cm"># linspace -- nokta SAYISINI belirtin (her iki uç dahil)</span>\nl1 = np.<span class="fn">linspace</span>(<span class="num">0</span>, <span class="num">1</span>, <span class="num">5</span>)    <span class="cm"># [0.   0.25 0.5  0.75 1.  ]</span>\nl2 = np.<span class="fn">linspace</span>(<span class="num">0</span>, <span class="num">2</span>*np.pi, <span class="num">100</span>)  <span class="cm"># sinüs dalgası çizmek için 100 nokta</span>\n\n<span class="cm"># logspace -- log aralıklı (10^başlangıç\'tan 10^bitiş\'e)</span>\nls = np.<span class="fn">logspace</span>(<span class="num">0</span>, <span class="num">3</span>, <span class="num">4</span>)    <span class="cm"># [1, 10, 100, 1000]</span>\nls2 = np.<span class="fn">logspace</span>(-<span class="num">3</span>, <span class="num">0</span>, <span class="num">4</span>)  <span class="cm"># [0.001, 0.01, 0.1, 1.0]  öğrenme oranı için harika!</span></code></pre></div>'

+ '<div class="calc-compare"><div class="compare-col"><div class="compare-title">arange(başlangıç, bitiş, adım)</div><div class="compare-item">Değerler arasındaki adım boyutunu belirtin</div><div class="compare-item">Bitiş değeri hariçtir</div><div class="compare-item">Eleman sayısı adıma bağlıdır</div><div class="compare-item">Tamsayı dizileri için en iyisi</div></div><div class="compare-col"><div class="compare-title">linspace(başlangıç, bitiş, sayı)</div><div class="compare-item">Nokta sayısını belirtin</div><div class="compare-item">Bitiş değeri dahildir</div><div class="compare-item">Adım otomatik hesaplanır</div><div class="compare-item">Grafik çizimi ve değerlendirme için en iyisi</div></div></div>'

/* --- Plotly: linspace vs logspace TR --- */
+ '<div id="plot-spaces-tr" class="plotly-graph"></div>'
+ '<script>setTimeout(function(){'
+ 'var lin={x:Array.from({length:10},function(_,i){return i}),y:Array.from({length:10},function(_,i){return i*111.1}),mode:"markers+lines",name:"linspace(0, 1000, 10)",marker:{color:"#4ecdc4",size:8},line:{color:"#4ecdc4",width:2}};'
+ 'var log={x:Array.from({length:10},function(_,i){return i}),y:[1,2.15,4.64,10,21.5,46.4,100,215,464,1000],mode:"markers+lines",name:"logspace(0, 3, 10)",marker:{color:"#c8a96e",size:8},line:{color:"#c8a96e",width:2}};'
+ 'var layout={title:{text:"linspace vs logspace: Eşit vs Logaritmik Aralık",font:{color:"#ebe6dc",size:14}},paper_bgcolor:"rgba(0,0,0,0)",plot_bgcolor:"rgba(0,0,0,0)",font:{color:"#ebe6dc"},yaxis:{title:"Değer",gridcolor:"rgba(255,255,255,0.06)",zerolinecolor:"rgba(255,255,255,0.15)"},xaxis:{title:"İndeks",gridcolor:"rgba(255,255,255,0.06)"},margin:{t:50,r:30,b:50,l:60},showlegend:true,legend:{font:{color:"#ebe6dc"}}};'
+ 'Plotly.newPlot("plot-spaces-tr",[lin,log],layout,{responsive:true,displayModeBar:false});'
+ '},200)</script>'

+ '<div class="calc-graph"><div class="graph-caption"><strong>Bu görselin söylediği:</strong> linspace eşit aralıklı değerler üretir (düz çizgi), logspace ise logaritmik aralıklı değerler üretir (üstel eğri). logspace hiperparametre araması için vazgeçilmezdir -- öğrenme oranları büyüklük sıralarını kapsar (0.001 ile 1.0 arası).</div></div>'

+ '<p class="l-text"><strong>Rastgele diziler</strong> -- başlatma ve simülasyon için vazgeçilmez:</p>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="cm"># Modern yol: np.random.default_rng() kullanın</span>\nrng = np.random.<span class="fn">default_rng</span>(seed=<span class="num">42</span>)  <span class="cm"># tekrarlanabilir!</span>\n\n<span class="cm"># Düzgün dağılım [0, 1)</span>\nu = rng.<span class="fn">random</span>((<span class="num">3</span>, <span class="num">4</span>))           <span class="cm"># 3x4 matris, [0, 1) aralığında</span>\n\n<span class="cm"># Normal (Gaussian) dağılım, ortalama=0, std=1</span>\nn = rng.<span class="fn">standard_normal</span>((<span class="num">3</span>, <span class="num">4</span>))  <span class="cm"># 3x4, standart normal</span>\n\n<span class="cm"># Rastgele tamsayılar</span>\ni = rng.<span class="fn">integers</span>(<span class="num">0</span>, <span class="num">10</span>, size=(<span class="num">3</span>, <span class="num">3</span>))  <span class="cm"># 3x3, [0, 10) arası tamsayılar</span>\n\n<span class="cm"># Diziden rastgele seçim</span>\nc = rng.<span class="fn">choice</span>([<span class="str">"kedi"</span>, <span class="str">"köpek"</span>, <span class="str">"balık"</span>], size=<span class="num">5</span>)\n\n<span class="cm"># Eski API (hala yaygın olarak görülür)</span>\nnp.random.<span class="fn">seed</span>(<span class="num">42</span>)\nnp.random.<span class="fn">rand</span>(<span class="num">3</span>, <span class="num">4</span>)       <span class="cm"># düzgün [0, 1) -- not: tuple yok!</span>\nnp.random.<span class="fn">randn</span>(<span class="num">3</span>, <span class="num">4</span>)      <span class="cm"># standart normal</span>\nnp.random.<span class="fn">randint</span>(<span class="num">0</span>, <span class="num">10</span>, (<span class="num">3</span>, <span class="num">3</span>))  <span class="cm"># rastgele tamsayılar</span></code></pre></div>'

+ '<div class="l-note"><strong>Tekrarlanabilirlik:</strong> Tekrarlanabilir sonuçlara ihtiyaç duyduğunuzda her zaman rastgele tohum (seed) ayarlayın! ML deneylerinde bu, sonuçlarınızın tekrarlanabilmesini sağlar. Modern <code>default_rng(seed=42)</code> API\'sini kullanın -- eski <code>np.random.seed()</code> yaklaşımından daha hızlı ve istatistiksel olarak daha iyidir.</div>'

/* ============================================================
   BÖLÜM 4: Veri Tipleri (dtype)
   ============================================================ */
+ '<h2 class="l-title">4. Veri Tipleri (dtype)</h2>'

+ '<div class="calc-highlight"><strong>dtype neden önemli:</strong> dtype (1) her elemanın ne kadar bellek kullandığını, (2) temsil edebileceği değer aralığını ve (3) hesaplamaların hassasiyetini belirler. Doğru dtype\'ı seçmek ML\'de önemli bir optimizasyondur -- float32 çoğu sinir ağı için en uygun noktadır.</div>'

+ '<p class="l-text">NumPy, Python\'dan çok daha fazla veri tipini destekler. İşte tam referans:</p>'

+ '<div class="calc-cards"><div class="calc-card"><div class="card-title">int8</div><div class="card-body">1 byte, aralık: -128 ile 127. Kuantize modeller ve küçük sayaçlar için kullanılır.</div></div><div class="calc-card"><div class="card-title">int16</div><div class="card-body">2 byte, aralık: -32.768 ile 32.767. Ses örnekleri, küçük veri setleri.</div></div><div class="calc-card"><div class="card-title">int32</div><div class="card-body">4 byte, aralık: ~-2.1 milyar ile ~2.1 milyar. Genel tamsayı işleri, indeksler.</div></div><div class="calc-card"><div class="card-title">int64</div><div class="card-body">8 byte, aralık: ~-9.2 kentilyon. Tamsayılar için varsayılan, zaman damgaları.</div></div><div class="calc-card"><div class="card-title">float16</div><div class="card-body">2 byte, ~3 ondalık basamak hassasiyet. Karışık hassasiyetli GPU eğitiminde kullanılır.</div></div><div class="calc-card"><div class="card-title">float32</div><div class="card-body">4 byte, ~7 ondalık basamak. ML/DL STANDARTI. Hız/hassasiyet dengesinde en iyi.</div></div><div class="calc-card"><div class="card-title">float64</div><div class="card-body">8 byte, ~15 ondalık basamak. Kayan nokta için varsayılan. Hassasiyetin önemli olduğu bilimsel hesaplama.</div></div><div class="calc-card"><div class="card-title">bool_</div><div class="card-body">1 byte, True/False. Maskeler, boolean indeksleme, ikili etiketler.</div></div></div>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="kw">import</span> numpy <span class="kw">as</span> np\n\n<span class="cm"># Otomatik dtype çıkarımı</span>\na = np.<span class="fn">array</span>([<span class="num">1</span>, <span class="num">2</span>, <span class="num">3</span>])        <span class="cm"># int64 (tamsayılar)</span>\nb = np.<span class="fn">array</span>([<span class="num">1.0</span>, <span class="num">2.0</span>, <span class="num">3.0</span>])  <span class="cm"># float64 (ondalık var)</span>\nc = np.<span class="fn">array</span>([<span class="num">1</span>, <span class="num">2</span>, <span class="num">3.0</span>])      <span class="cm"># float64 (karışık: float\'a yükseltir)</span>\nd = np.<span class="fn">array</span>([<span class="kw">True</span>, <span class="kw">False</span>])    <span class="cm"># bool_</span>\n\n<span class="cm"># Açık dtype</span>\ne = np.<span class="fn">array</span>([<span class="num">1</span>, <span class="num">2</span>, <span class="num">3</span>], dtype=np.float32)\n<span class="fn">print</span>(e)         <span class="cm"># [1. 2. 3.]</span>\n<span class="fn">print</span>(e.dtype)   <span class="cm"># float32</span>\n\n<span class="cm"># astype() ile tip dönüştürme</span>\nf = e.<span class="fn">astype</span>(np.int8)\n<span class="fn">print</span>(f)         <span class="cm"># [1 2 3]</span>\n<span class="fn">print</span>(f.dtype)   <span class="cm"># int8</span>\n<span class="fn">print</span>(f.itemsize) <span class="cm"># eleman başına 1 byte (önceden 4 idi)</span>\n\n<span class="cm"># Bellek karşılaştırması</span>\nbig = np.<span class="fn">ones</span>((<span class="num">1000</span>, <span class="num">1000</span>), dtype=np.float64)\nsmall = np.<span class="fn">ones</span>((<span class="num">1000</span>, <span class="num">1000</span>), dtype=np.float32)\n<span class="fn">print</span>(<span class="str">f"float64: {big.nbytes / 1e6:.1f} MB"</span>)   <span class="cm"># 8.0 MB</span>\n<span class="fn">print</span>(<span class="str">f"float32: {small.nbytes / 1e6:.1f} MB"</span>) <span class="cm"># 4.0 MB -- yarısı!</span></code></pre></div>'

+ '<div class="calc-compare"><div class="compare-col"><div class="compare-title">Tamsayı Tipleri</div><div class="compare-item">int8: 1 byte, -128 ile 127</div><div class="compare-item">int16: 2 byte, -32K ile 32K</div><div class="compare-item">int32: 4 byte, -2.1 milyar ile 2.1 milyar</div><div class="compare-item">int64: 8 byte (tamsayılar için varsayılan)</div><div class="compare-item">uint8: 1 byte, 0 ile 255 (görüntüler!)</div></div><div class="compare-col"><div class="compare-title">Kayan Nokta Tipleri</div><div class="compare-item">float16: 2 byte, ~3 basamak hassasiyet</div><div class="compare-item">float32: 4 byte, ~7 basamak (ML standardı)</div><div class="compare-item">float64: 8 byte, ~15 basamak (varsayılan)</div><div class="compare-item">complex64: 8 byte (iki float32)</div><div class="compare-item">complex128: 16 byte (iki float64)</div></div></div>'

+ '<div class="think-box"><div class="think-label">DÜŞÜNÜN</div><div class="think-body">GPT-2 modelinin ~124 milyon parametresi var. float64\'te 992 MB gerektirir. float32\'de 496 MB. float16\'da yalnızca 248 MB. int8\'e kuantize edildiğinde sadece 124 MB. <strong>Model kuantizasyonunun</strong> bu kadar popüler bir konu olmasının nedeni budur -- büyük modellerin daha küçük cihazlara sığmasını sağlar.</div></div>'

/* ============================================================
   BÖLÜM 5: Dizi İnceleme & Yeniden Şekillendirme
   ============================================================ */
+ '<h2 class="l-title">5. Dizi İnceleme & Yeniden Şekillendirme</h2>'

+ '<div class="calc-highlight"><strong>Yeniden şekillendirme sadece kozmetik değildir:</strong> Verilere nasıl eriştiğinizi ve işlediğinizi değiştirir. ML\'de sürekli dizileri yeniden şekillendirirsiniz -- yoğun katmanlara beslemek için görüntüleri düzleştirmek, batch boyutları eklemek, ağırlık matrislerini transpoze etmek. Bunu yanlış yapmak, derin öğrenmedeki en yaygın hata olan şekil uyumsuzluğu hatalarına neden olur.</div>'

+ '<p class="l-text"><strong>reshape()</strong> verilerini değiştirmeden dizinin şeklini değiştirir:</p>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="kw">import</span> numpy <span class="kw">as</span> np\n\na = np.<span class="fn">arange</span>(<span class="num">12</span>)   <span class="cm"># [ 0  1  2  3  4  5  6  7  8  9 10 11]</span>\n\n<span class="cm"># Farklı konfigürasyonlara yeniden şekillendir</span>\nb = a.<span class="fn">reshape</span>(<span class="num">3</span>, <span class="num">4</span>)    <span class="cm"># 3 satır, 4 sütun</span>\nc = a.<span class="fn">reshape</span>(<span class="num">4</span>, <span class="num">3</span>)    <span class="cm"># 4 satır, 3 sütun</span>\nd = a.<span class="fn">reshape</span>(<span class="num">2</span>, <span class="num">2</span>, <span class="num">3</span>) <span class="cm"># 3B tensör: 2x3\'lük 2 matris</span>\n\n<span class="cm"># -1 "bu boyutu benim için hesapla" demektir</span>\ne = a.<span class="fn">reshape</span>(<span class="num">3</span>, -<span class="num">1</span>)   <span class="cm"># 3 x ? = 12, yani ? = 4 --&gt; (3, 4)</span>\nf = a.<span class="fn">reshape</span>(-<span class="num">1</span>, <span class="num">1</span>)   <span class="cm"># ? x 1 = 12, yani ? = 12 --&gt; (12, 1) sütun vektörü</span>\n\n<span class="cm"># Düzleştir: tekrar 1B\'ye</span>\ng = b.<span class="fn">ravel</span>()      <span class="cm"># VIEW döndürür (b ile belleği paylaşır)</span>\nh = b.<span class="fn">flatten</span>()    <span class="cm"># KOPYA döndürür (b\'den bağımsız)</span>\n\n<span class="cm"># Transpoze: satır ve sütunları değiştir</span>\n<span class="fn">print</span>(b.shape)     <span class="cm"># (3, 4)</span>\n<span class="fn">print</span>(b.T.shape)   <span class="cm"># (4, 3)</span></code></pre></div>'

+ '<div class="think-box"><div class="think-label">DÜŞÜNÜN</div><div class="think-body"><strong>Görünüm (View) vs Kopya (Copy) -- kritik ayrım:</strong> Bir <strong>görünüm</strong> orijinal diziyle belleği paylaşır. Görünümü değiştirmek orijinali değiştirir. Bir <strong>kopya</strong> bağımsızdır -- kopyadaki değişiklikler orijinali etkilemez.<br><br><code>reshape()</code>, <code>ravel()</code>, <code>T</code> ve dilimleme <strong>görünüm</strong> döndürür (mümkün olduğunda).<br><code>flatten()</code>, <code>.copy()</code> ve süslü indeksleme <strong>kopya</strong> döndürür.<br><br>Bu çok önemlidir: görünümler bellek açısından verimlidir (çoğaltma yok), ancak bir görünüm üzerinden kazara değiştirme yaygın bir hatadır.</div></div>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="cm"># View vs Copy gösterimi</span>\norig = np.<span class="fn">array</span>([<span class="num">1</span>, <span class="num">2</span>, <span class="num">3</span>, <span class="num">4</span>, <span class="num">5</span>, <span class="num">6</span>])\n\n<span class="cm"># reshape VIEW döndürür</span>\nview = orig.<span class="fn">reshape</span>(<span class="num">2</span>, <span class="num">3</span>)\nview[<span class="num">0</span>, <span class="num">0</span>] = <span class="num">999</span>\n<span class="fn">print</span>(orig)  <span class="cm"># [999   2   3   4   5   6]  DEĞİŞTİ!</span>\n\n<span class="cm"># .copy() bağımsız kopya oluşturur</span>\norig2 = np.<span class="fn">array</span>([<span class="num">1</span>, <span class="num">2</span>, <span class="num">3</span>, <span class="num">4</span>, <span class="num">5</span>, <span class="num">6</span>])\ncopy = orig2.<span class="fn">reshape</span>(<span class="num">2</span>, <span class="num">3</span>).<span class="fn">copy</span>()\ncopy[<span class="num">0</span>, <span class="num">0</span>] = <span class="num">999</span>\n<span class="fn">print</span>(orig2) <span class="cm"># [1 2 3 4 5 6]  değişmedi!</span>\n\n<span class="cm"># Bir şeyin view olup olmadığını kontrol et</span>\n<span class="fn">print</span>(view.base <span class="kw">is</span> orig)   <span class="cm"># True -- view orig\'in belleğini paylaşır</span>\n<span class="fn">print</span>(copy.base <span class="kw">is</span> orig2)  <span class="cm"># False -- copy bağımsız</span></code></pre></div>'

+ '<p class="l-text"><strong>Bellek düzeni: C-sırası vs F-sırası</strong></p>'

+ '<div class="calc-compare"><div class="compare-col"><div class="compare-title">C-sırası (Satır-öncelikli)</div><div class="compare-item">NumPy\'da varsayılan</div><div class="compare-item">Satırlar ardışık saklanır</div><div class="compare-item">Son indeks en hızlı değişir</div><div class="compare-item">Satır bazlı işlemler için en iyisi</div></div><div class="compare-col"><div class="compare-title">F-sırası (Sütun-öncelikli)</div><div class="compare-item">Fortran ve MATLAB\'da varsayılan</div><div class="compare-item">Sütunlar ardışık saklanır</div><div class="compare-item">İlk indeks en hızlı değişir</div><div class="compare-item">Sütun bazlı işlemler için en iyisi</div></div></div>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="cm"># C-sırası (varsayılan) vs F-sırası</span>\na = np.<span class="fn">array</span>([[<span class="num">1</span>, <span class="num">2</span>, <span class="num">3</span>],\n              [<span class="num">4</span>, <span class="num">5</span>, <span class="num">6</span>]], order=<span class="str">"C"</span>)\n\n<span class="cm"># Bellekte (C-sırası): [1, 2, 3, 4, 5, 6] -- satır satır</span>\n<span class="fn">print</span>(a.<span class="fn">ravel</span>(order=<span class="str">"C"</span>))  <span class="cm"># [1 2 3 4 5 6]</span>\n\n<span class="cm"># Bellekte (F-sırası): [1, 4, 2, 5, 3, 6] -- sütun sütun</span>\n<span class="fn">print</span>(a.<span class="fn">ravel</span>(order=<span class="str">"F"</span>))  <span class="cm"># [1 4 2 5 3 6]</span>\n\n<span class="cm"># Mevcut sırayı kontrol et</span>\n<span class="fn">print</span>(a.flags[<span class="str">"C_CONTIGUOUS"</span>])  <span class="cm"># True</span>\n<span class="fn">print</span>(a.flags[<span class="str">"F_CONTIGUOUS"</span>])  <span class="cm"># False</span></code></pre></div>'

/* ============================================================
   BÖLÜM 6: Pratik Kalıplar
   ============================================================ */
+ '<h2 class="l-title">6. Pratik Kalıplar</h2>'

+ '<div class="calc-highlight"><strong>Gerçek dünya kullanımı:</strong> Artık yapı taşlarını bildiğinize göre, bunların pratikte nasıl birleştiğini görelim. Bu kalıplar neredeyse her ML projesinde karşınıza çıkar.</div>'

+ '<p class="l-text"><strong>Kalıp 1: Sentetik ML veri setleri oluşturma</strong></p>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="kw">import</span> numpy <span class="kw">as</span> np\nrng = np.random.<span class="fn">default_rng</span>(<span class="num">42</span>)\n\n<span class="cm"># Sentetik doğrusal regresyon veri seti</span>\nn_samples = <span class="num">100</span>\nn_features = <span class="num">3</span>\n\nX = rng.<span class="fn">standard_normal</span>((n_samples, n_features))  <span class="cm"># 100x3 öznitelik matrisi</span>\ntrue_weights = np.<span class="fn">array</span>([<span class="num">2.5</span>, -<span class="num">1.0</span>, <span class="num">0.5</span>])\nnoise = rng.<span class="fn">standard_normal</span>(n_samples) * <span class="num">0.1</span>\ny = X @ true_weights + noise  <span class="cm"># @ = matris çarpımı</span>\n\n<span class="fn">print</span>(<span class="str">f"Öznitelikler: {X.shape}"</span>)  <span class="cm"># (100, 3)</span>\n<span class="fn">print</span>(<span class="str">f"Etiketler:    {y.shape}"</span>)  <span class="cm"># (100,)</span></code></pre></div>'

+ '<p class="l-text"><strong>Kalıp 2: 2B değerlendirme için meshgrid</strong></p>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="cm"># Karar sınırlarını çizmek için 2B ızgara oluştur</span>\nx1 = np.<span class="fn">linspace</span>(-<span class="num">3</span>, <span class="num">3</span>, <span class="num">100</span>)\nx2 = np.<span class="fn">linspace</span>(-<span class="num">3</span>, <span class="num">3</span>, <span class="num">100</span>)\nX1, X2 = np.<span class="fn">meshgrid</span>(x1, x2)  <span class="cm"># iki 100x100 ızgara</span>\n\n<span class="fn">print</span>(X1.shape)  <span class="cm"># (100, 100) -- x1 değerleri satırlar boyunca tekrarlanır</span>\n<span class="fn">print</span>(X2.shape)  <span class="cm"># (100, 100) -- x2 değerleri sütunlar boyunca tekrarlanır</span>\n\n<span class="cm"># Her ızgara noktasında bir fonksiyon değerlendir</span>\nZ = np.<span class="fn">sin</span>(X1) * np.<span class="fn">cos</span>(X2)  <span class="cm"># 100x100 sonuç</span></code></pre></div>'

/* --- Plotly: Meshgrid 3D Yüzey TR --- */
+ '<div id="plot-meshgrid-tr" class="plotly-graph"></div>'
+ '<script>setTimeout(function(){'
+ 'var N=40;var x=[];var y=[];for(var i=0;i<N;i++){x.push(-3+6*i/(N-1));y.push(-3+6*i/(N-1))}'
+ 'var z=[];for(var j=0;j<N;j++){var row=[];for(var i=0;i<N;i++){row.push(Math.sin(x[i])*Math.cos(y[j]))}z.push(row)}'
+ 'var data=[{z:z,x:x,y:y,type:"surface",colorscale:[[0,"#1a1a2e"],[0.25,"#4ecdc4"],[0.5,"#c8a96e"],[0.75,"#f87171"],[1,"#a78bfa"]],showscale:false}];'
+ 'var layout={title:{text:"meshgrid Yüzeyi: sin(x) * cos(y)",font:{color:"#ebe6dc",size:14}},paper_bgcolor:"rgba(0,0,0,0)",plot_bgcolor:"rgba(0,0,0,0)",font:{color:"#ebe6dc"},scene:{xaxis:{title:"x1",gridcolor:"rgba(255,255,255,0.1)"},yaxis:{title:"x2",gridcolor:"rgba(255,255,255,0.1)"},zaxis:{title:"f(x1,x2)",gridcolor:"rgba(255,255,255,0.1)"},bgcolor:"rgba(0,0,0,0)"},margin:{t:50,r:10,b:10,l:10}};'
+ 'Plotly.newPlot("plot-meshgrid-tr",data,layout,{responsive:true,displayModeBar:false});'
+ '},200)</script>'

+ '<div class="calc-graph"><div class="graph-caption"><strong>Grafiğin özü:</strong> Bir meshgrid üzerinde sin(x1) * cos(x2) değerlendirilerek oluşturulan 3B yüzey. ML\'de karar sınırı görselleştirmeleri ve kayıp yüzeyleri tam olarak bu şekilde çizilir.</div></div>'

+ '<p class="l-text"><strong>Kalıp 3: Dizileri birleştirme ve ayırma</strong></p>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="cm"># Dizileri birleştirme</span>\na = np.<span class="fn">array</span>([<span class="num">1</span>, <span class="num">2</span>, <span class="num">3</span>])\nb = np.<span class="fn">array</span>([<span class="num">4</span>, <span class="num">5</span>, <span class="num">6</span>])\n\n<span class="cm"># Dikey yığınlama (satır ekleme)</span>\nv = np.<span class="fn">vstack</span>([a, b])     <span class="cm"># [[1,2,3], [4,5,6]]  şekil: (2,3)</span>\n\n<span class="cm"># Yatay yığınlama (sütun ekleme)</span>\nh = np.<span class="fn">hstack</span>([a, b])     <span class="cm"># [1,2,3,4,5,6]  şekil: (6,)</span>\n\n<span class="cm"># Sütun yığınlama (1B diziler sütun olur)</span>\nc = np.<span class="fn">column_stack</span>([a, b])  <span class="cm"># [[1,4], [2,5], [3,6]]  şekil: (3,2)</span>\n\n<span class="cm"># Herhangi bir eksen boyunca birleştir</span>\nm1 = np.<span class="fn">ones</span>((<span class="num">2</span>, <span class="num">3</span>))\nm2 = np.<span class="fn">zeros</span>((<span class="num">2</span>, <span class="num">3</span>))\nnp.<span class="fn">concatenate</span>([m1, m2], axis=<span class="num">0</span>)  <span class="cm"># (4,3) -- dikey yığınla</span>\nnp.<span class="fn">concatenate</span>([m1, m2], axis=<span class="num">1</span>)  <span class="cm"># (2,6) -- yatay yığınla</span>\n\n<span class="cm"># Dizileri ayırma</span>\nbig = np.<span class="fn">arange</span>(<span class="num">12</span>).<span class="fn">reshape</span>(<span class="num">3</span>, <span class="num">4</span>)\nrows = np.<span class="fn">vsplit</span>(big, <span class="num">3</span>)     <span class="cm"># 3 dizi listesi, her biri (1,4)</span>\ncols = np.<span class="fn">hsplit</span>(big, <span class="num">2</span>)     <span class="cm"># 2 dizi listesi, her biri (3,2)</span></code></pre></div>'

+ '<p class="l-text"><strong>Kalıp 4: Dizileri kaydetme ve yükleme</strong></p>'

+ '<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest(\'.code-wrap\').querySelector(\'code\').textContent)">COPY</button></div><pre class="code-block"><code><span class="cm"># Tek dizi kaydet (.npy formatı -- ikili, hızlı)</span>\narr = np.<span class="fn">arange</span>(<span class="num">1000</span>)\nnp.<span class="fn">save</span>(<span class="str">"dizim.npy"</span>, arr)\nloaded = np.<span class="fn">load</span>(<span class="str">"dizim.npy"</span>)\n\n<span class="cm"># Birden fazla dizi kaydet (.npz formatı)</span>\nnp.<span class="fn">savez</span>(<span class="str">"veri.npz"</span>, ozellikler=X, etiketler=y)\ndata = np.<span class="fn">load</span>(<span class="str">"veri.npz"</span>)\n<span class="fn">print</span>(data[<span class="str">"ozellikler"</span>].shape)  <span class="cm"># isme göre erişim</span>\n\n<span class="cm"># Sıkıştırılmış kaydet (daha küçük dosya)</span>\nnp.<span class="fn">savez_compressed</span>(<span class="str">"veri_sikistirilmis.npz"</span>, ozellikler=X, etiketler=y)\n\n<span class="cm"># İnsan okunabilir metin olarak kaydet</span>\nnp.<span class="fn">savetxt</span>(<span class="str">"veri.csv"</span>, arr.<span class="fn">reshape</span>(<span class="num">10</span>, <span class="num">100</span>), delimiter=<span class="str">","</span>)\nloaded_csv = np.<span class="fn">loadtxt</span>(<span class="str">"veri.csv"</span>, delimiter=<span class="str">","</span>)</code></pre></div>'

+ '<div class="l-note"><strong>En iyi uygulama:</strong> Ara sonuçlar için <code>.npy/.npz</code> kullanın (hızlı, dtype\'ları korur). <code>.csv</code>\'yi yalnızca insan okunabilir çıktıya veya Excel ya da Pandas gibi diğer araçlarla birlikte çalışabilirliğe ihtiyaç duyduğunuzda kullanın.</div>'

+ '<div class="calc-example"><div class="example-label">TAM ÖRNEK: Dizi Olarak Görüntü</div><div class="example-body">28x28 gri tonlamalı bir görüntü (MNIST rakamları gibi) uint8 değerli (0-255) (28, 28) şeklinde bir 2B dizidir.<br><br><strong>Adım 1:</strong> 2B olarak yükle: şekil (28, 28), 784 piksel<br><strong>Adım 2:</strong> Yoğun katman için düzleştir: <code>img.reshape(-1)</code> şekil (784,) verir<br><strong>Adım 3:</strong> Batch boyutu ekle: <code>img.reshape(1, 28, 28)</code> şekil (1, 28, 28) verir<br><strong>Adım 4:</strong> Normalize et: <code>img.astype(np.float32) / 255.0</code> [0, 1]\'e ölçekler<br><strong>Adım 5:</strong> CNN için: <code>img.reshape(1, 1, 28, 28)</code> (batch, kanal, yükseklik, genişlik) verir</div></div>'

+ '<div class="think-box"><div class="think-label">TEMEL ÇIKRIMLAR</div><div class="think-body"><strong>1.</strong> NumPy, C altyapısı, vektörizasyon ve ardışık bellek sayesinde Python listelerinden 10-100 kat daha hızlıdır.<br><strong>2.</strong> ndarray\'in temel nitelikleri: dtype, shape, ndim, size, itemsize, nbytes.<br><strong>3.</strong> Her amaç için dizi oluşturmak için zeros/ones/full/arange/linspace/random kullanın.<br><strong>4.</strong> dtype\'ınızı akıllıca seçin: ML için float32, kuantizasyon için int8, bilimsel hassasiyet için float64.<br><strong>5.</strong> reshape/ravel/T görünüm (paylaşılan bellek) döndürür. flatten/.copy() bağımsız kopyalar döndürür.<br><strong>6.</strong> Gerçek dünya veri iş hatları için yığınlama, ayırma, meshgrid ve kaydetme/yükleme konularına hakim olun.</div></div>'

};
