window.LISE_MAT_L3 = {

en: `<p class="l-text"><strong>Special angles are the workhorses of trigonometry.</strong> Almost every trigonometric problem you will solve on a high-school exam, in a physics question, or in a geometry construction asks for the sine, cosine, or tangent of one of a small handful of angles: 0&deg;, 30&deg;, 45&deg;, 60&deg;, 90&deg;, and their cousins in the other three quadrants. If you memorise the exact values for these angles &mdash; and, more importantly, understand <em>where they come from</em> &mdash; the rest of trigonometry stops feeling like a list of mysteries and starts looking like a clean, predictable pattern.</p>

<p class="l-text">In this lesson we derive the values for 30-60-90 and 45-45-90 triangles from first principles using only the Pythagorean theorem, then assemble the famous "trig table" that every Turkish lise (YKS-AYT) student needs at their fingertips. We extend the table to the boundary angles 0&deg;, 90&deg;, 180&deg;, 270&deg;, 360&deg; using the unit circle, and finally we learn the <strong>reference angle method</strong> that lets you evaluate sin, cos, tan of <em>any</em> angle &mdash; including negative angles and angles greater than 360&deg; &mdash; by reducing them back to the special angles you already know.</p>

<div class="lesson-outcomes" style="background:rgba(59,130,246,0.06);border-left:3px solid #3b82f6;padding:1rem 1.2rem;margin:1.5rem 0;border-radius:0 8px 8px 0">
<div style="font-size:0.78rem;font-weight:700;letter-spacing:0.08em;color:#3b82f6;margin-bottom:0.6rem">WHAT YOU WILL LEARN</div>
<ul style="margin:0;padding-left:1.3rem;line-height:1.65;font-size:0.93rem;color:rgba(235,230,220,0.92)">
<li>Derive the 30&deg;-60&deg;-90&deg; side ratios from an equilateral triangle cut in half</li>
<li>Derive the 45&deg;-45&deg;-90&deg; side ratios from an isosceles right triangle</li>
<li>Memorise (and reconstruct) the special-angle table for sin, cos, tan</li>
<li>Read off the values of sin, cos, tan at the boundary angles 0&deg;, 90&deg;, 180&deg;, 270&deg;, 360&deg;</li>
<li>Use the reference-angle method to evaluate trig functions for angles in any quadrant</li>
<li>Handle negative angles and angles above 360&deg; by reducing them to a coterminal special angle</li>
</ul>
</div>

<h2 class="l-title">1. Why Special Angles Matter</h2>

<div class="calc-highlight"><strong>Everyday picture:</strong> Open any AYT mathematics booklet, any physics problem about an inclined ramp, any geometry question about a regular hexagon, and you will find the same angles appearing again and again: 30&deg;, 45&deg;, 60&deg;. They are not chosen by accident &mdash; they fall out of the most symmetric shapes in elementary geometry (the equilateral triangle and the square), so they appear naturally whenever symmetry is in play.</div>

<p class="l-text">A handful of angles &mdash; 0&deg;, 30&deg;, 45&deg;, 60&deg;, 90&deg; in the first quadrant, plus their reflections in the other three quadrants &mdash; cover roughly <strong>80% of all trig values asked in Turkish high-school exams</strong>. Knowing them lets you:</p>

<div class="calc-cards">
<div class="calc-card"><div class="card-title">Solve YKS-AYT problems quickly</div><div class="card-body">No calculator allowed. If you know that sin&nbsp;30&deg; = 1/2 and cos&nbsp;60&deg; = 1/2 instantly, you save 30 seconds per question &mdash; a huge advantage in a timed exam.</div></div>
<div class="calc-card"><div class="card-title">Read physics formulas</div><div class="card-body">Forces resolved along a 30&deg; ramp, projectiles launched at 45&deg; for maximum range, light refracted through a 60&deg; prism &mdash; the same angles, over and over.</div></div>
<div class="calc-card"><div class="card-title">Build the unit circle</div><div class="card-body">The 16 most-referenced points on the unit circle are all generated by these few angles. Once you know them you can sketch the whole circle from memory.</div></div>
<div class="calc-card"><div class="card-title">Verify general identities</div><div class="card-body">When you suspect an identity like sin&nbsp;2x = 2&nbsp;sin&nbsp;x&nbsp;cos&nbsp;x, plugging in x = 30&deg; gives an instant numerical check.</div></div>
</div>

<p class="l-text"><strong>The strategy of this lesson.</strong> We will not ask you to <em>memorise</em> the table by brute force. Instead we derive the entries from two famous triangles whose sides you can reconstruct in 10 seconds with a pencil. Once the derivation feels natural, the table will stick on its own.</p>

<h2 class="l-title">2. The 30&deg;-60&deg;-90&deg; Triangle</h2>

<p class="l-text">The 30-60-90 triangle is obtained by cutting an <strong>equilateral triangle</strong> exactly in half along its altitude. This single picture is the source of every entry containing $\\sqrt{3}$ in the trig table.</p>

<div class="calc-steps">
<div class="calc-step"><div class="step-num">1</div><div class="step-content"><div class="step-title">Start with an equilateral triangle of side 2</div><div class="step-detail">All three sides equal 2, all three angles equal 60&deg;. We choose side&nbsp;2 instead of side&nbsp;1 so the half-sides come out as nice integers.</div></div></div>
<div class="calc-step"><div class="step-num">2</div><div class="step-content"><div class="step-title">Drop the altitude from one vertex</div><div class="step-detail">The altitude is a perpendicular line from the top vertex to the midpoint of the opposite side. By symmetry it bisects the top angle (60&deg; becomes two 30&deg; halves) and the bottom side (2 becomes two pieces of length 1).</div></div></div>
<div class="calc-step"><div class="step-num">3</div><div class="step-content"><div class="step-title">Read off the resulting right triangle</div><div class="step-detail">The half-triangle now has angles 30&deg;, 60&deg;, 90&deg; and two known sides: hypotenuse 2 and short leg 1. Pythagoras gives the long leg.</div></div></div>
<div class="calc-step"><div class="step-num">4</div><div class="step-content"><div class="step-title">Apply the Pythagorean theorem</div><div class="step-detail">$\\text{long leg}^2 + 1^2 = 2^2 \\implies \\text{long leg}^2 = 3 \\implies \\text{long leg} = \\sqrt{3}$.</div></div></div>
</div>

<div class="calc-formula"><div class="formula-label">30-60-90 SIDE RATIOS</div><div class="formula-main">$$\\text{opposite 30&deg;} : \\text{opposite 60&deg;} : \\text{opposite 90&deg;} \\;=\\; 1 : \\sqrt{3} : 2$$</div><div class="formula-sub">The shortest side is opposite the smallest angle (30&deg;). The hypotenuse is always opposite the right angle.</div></div>

<div id="plot-3060-en" class="plotly-graph" style="height:380px"></div>
<script>setTimeout(function(){
var tri={x:[0,Math.sqrt(3),0,0],y:[0,0,1,0],mode:"lines+markers",fill:"toself",fillcolor:"rgba(59,130,246,0.10)",line:{color:"#3b82f6",width:3},marker:{size:8,color:"#3b82f6"},name:"30-60-90"};
var sqr={x:[0,0.18,0.18,0],y:[0.18,0.18,0,0],mode:"lines",line:{color:"#3b82f6",width:1.5},showlegend:false,hoverinfo:"skip"};
var ann=[
{x:Math.sqrt(3)/2,y:-0.10,text:"&radic;3 (opposite 60&deg;)",showarrow:false,font:{color:"#3b82f6",size:13}},
{x:-0.16,y:0.5,text:"1 (opposite 30&deg;)",showarrow:false,font:{color:"#3b82f6",size:13},textangle:-90},
{x:Math.sqrt(3)/2+0.18,y:0.55,text:"2 (hypotenuse)",showarrow:false,font:{color:"#3b82f6",size:13},textangle:-30},
{x:0.32,y:0.06,text:"30&deg;",showarrow:false,font:{color:"#cbd5e1",size:12}},
{x:Math.sqrt(3)-0.20,y:0.06,text:"60&deg;",showarrow:false,font:{color:"#cbd5e1",size:12}},
{x:0.04,y:0.84,text:"90&deg;",showarrow:false,font:{color:"#cbd5e1",size:12}}
];
var layout={paper_bgcolor:"rgba(0,0,0,0)",plot_bgcolor:"rgba(0,0,0,0)",font:{color:"#ebe6dc"},xaxis:{range:[-0.6,2.4],showgrid:false,zeroline:false,visible:false},yaxis:{range:[-0.35,1.4],showgrid:false,zeroline:false,visible:false,scaleanchor:"x"},annotations:ann,margin:{t:20,r:20,b:20,l:20},showlegend:false};
Plotly.newPlot("plot-3060-en",[tri,sqr],layout,{responsive:true,displayModeBar:false});
},250)</script>

<div class="calc-graph"><div class="graph-caption"><strong>What this graph shows:</strong> A 30-60-90 right triangle drawn with the actual proportions. The shortest side (length 1) sits opposite the smallest angle (30&deg;). The longest leg (length $\\sqrt{3}$) sits opposite the 60&deg; angle. The hypotenuse (length 2) is opposite the right angle, as always.</div></div>

<p class="l-text"><strong>Reading the trig ratios off the triangle.</strong> Using SOHCAHTOA (sin = opposite/hypotenuse, cos = adjacent/hypotenuse, tan = opposite/adjacent), we get:</p>

<div class="calc-formula"><div class="formula-label">VALUES AT 30&deg; AND 60&deg;</div><div class="formula-main">$$\\sin 30^\\circ = \\frac{1}{2}, \\quad \\cos 30^\\circ = \\frac{\\sqrt{3}}{2}, \\quad \\tan 30^\\circ = \\frac{1}{\\sqrt{3}} = \\frac{\\sqrt{3}}{3}$$ $$\\sin 60^\\circ = \\frac{\\sqrt{3}}{2}, \\quad \\cos 60^\\circ = \\frac{1}{2}, \\quad \\tan 60^\\circ = \\sqrt{3}$$</div></div>

<div class="l-note"><strong>Pattern spotter.</strong> Notice that sin&nbsp;30&deg; = cos&nbsp;60&deg; and cos&nbsp;30&deg; = sin&nbsp;60&deg;. This is a special case of the co-function identity $\\sin\\theta = \\cos(90^\\circ - \\theta)$, which we will meet again in Lesson 4. It works because 30&deg; and 60&deg; are <strong>complementary</strong>: they sum to 90&deg;.</div>

<h2 class="l-title">3. The 45&deg;-45&deg;-90&deg; Triangle</h2>

<p class="l-text">The 45-45-90 triangle is even simpler: it is an <strong>isosceles right triangle</strong>, exactly half of a square cut along the diagonal. This picture is the source of every entry containing $\\sqrt{2}$ in the trig table.</p>

<div class="calc-steps">
<div class="calc-step"><div class="step-num">1</div><div class="step-content"><div class="step-title">Start with a unit square</div><div class="step-detail">All four sides equal 1, all four angles equal 90&deg;.</div></div></div>
<div class="calc-step"><div class="step-num">2</div><div class="step-content"><div class="step-title">Cut along the diagonal</div><div class="step-detail">This produces two congruent right triangles. Each has legs of length 1 and the diagonal as its hypotenuse.</div></div></div>
<div class="calc-step"><div class="step-num">3</div><div class="step-content"><div class="step-title">Read off the angles</div><div class="step-detail">The two non-right angles must sum to 90&deg; (since the three angles of a triangle add to 180&deg;) and by symmetry they are equal. So each is 45&deg;.</div></div></div>
<div class="calc-step"><div class="step-num">4</div><div class="step-content"><div class="step-title">Apply the Pythagorean theorem</div><div class="step-detail">$\\text{hyp}^2 = 1^2 + 1^2 = 2 \\implies \\text{hyp} = \\sqrt{2}$.</div></div></div>
</div>

<div class="calc-formula"><div class="formula-label">45-45-90 SIDE RATIOS</div><div class="formula-main">$$\\text{leg} : \\text{leg} : \\text{hypotenuse} \\;=\\; 1 : 1 : \\sqrt{2}$$</div><div class="formula-sub">Both legs are equal (the triangle is isosceles). The hypotenuse is $\\sqrt{2}$ times the leg.</div></div>

<div id="plot-4545-en" class="plotly-graph" style="height:380px"></div>
<script>setTimeout(function(){
var tri={x:[0,1,0,0],y:[0,0,1,0],mode:"lines+markers",fill:"toself",fillcolor:"rgba(59,130,246,0.10)",line:{color:"#3b82f6",width:3},marker:{size:8,color:"#3b82f6"},name:"45-45-90"};
var sqr={x:[0,0.10,0.10,0],y:[0.10,0.10,0,0],mode:"lines",line:{color:"#3b82f6",width:1.5},showlegend:false,hoverinfo:"skip"};
var ann=[
{x:0.5,y:-0.10,text:"1 (leg)",showarrow:false,font:{color:"#3b82f6",size:13}},
{x:-0.13,y:0.5,text:"1 (leg)",showarrow:false,font:{color:"#3b82f6",size:13},textangle:-90},
{x:0.62,y:0.55,text:"&radic;2 (hypotenuse)",showarrow:false,font:{color:"#3b82f6",size:13},textangle:-45},
{x:0.78,y:0.08,text:"45&deg;",showarrow:false,font:{color:"#cbd5e1",size:12}},
{x:0.04,y:0.78,text:"45&deg;",showarrow:false,font:{color:"#cbd5e1",size:12}},
{x:0.05,y:0.04,text:"90&deg;",showarrow:false,font:{color:"#cbd5e1",size:12}}
];
var layout={paper_bgcolor:"rgba(0,0,0,0)",plot_bgcolor:"rgba(0,0,0,0)",font:{color:"#ebe6dc"},xaxis:{range:[-0.4,1.4],showgrid:false,zeroline:false,visible:false},yaxis:{range:[-0.3,1.4],showgrid:false,zeroline:false,visible:false,scaleanchor:"x"},annotations:ann,margin:{t:20,r:20,b:20,l:20},showlegend:false};
Plotly.newPlot("plot-4545-en",[tri,sqr],layout,{responsive:true,displayModeBar:false});
},250)</script>

<div class="calc-graph"><div class="graph-caption"><strong>What this graph shows:</strong> A 45-45-90 right triangle drawn with the actual proportions. The two legs are equal (length 1). The hypotenuse, opposite the right angle, has length $\\sqrt{2} \\approx 1.414$.</div></div>

<div class="calc-formula"><div class="formula-label">VALUES AT 45&deg;</div><div class="formula-main">$$\\sin 45^\\circ = \\frac{1}{\\sqrt{2}} = \\frac{\\sqrt{2}}{2}, \\quad \\cos 45^\\circ = \\frac{\\sqrt{2}}{2}, \\quad \\tan 45^\\circ = 1$$</div><div class="formula-sub">Sine and cosine coincide at 45&deg; (the triangle is symmetric in its two legs). The tangent equals 1.</div></div>

<div class="l-note"><strong>Why rationalise?</strong> The expression $1/\\sqrt{2}$ and $\\sqrt{2}/2$ are exactly the same number. Turkish textbooks (and the AYT answer key) prefer the rationalised form $\\sqrt{2}/2$ &mdash; no irrational number in the denominator. Both forms are correct; use whichever the question key uses.</div>

<h2 class="l-title">4. The Special-Angle Table</h2>

<p class="l-text">Putting the work of the last two sections together, plus the boundary angles 0&deg; and 90&deg; (which we will derive properly in the next section), gives the famous table that every lise mathematics student must know:</p>

<div class="calc-formula"><div class="formula-label">SPECIAL-ANGLE TABLE (FIRST QUADRANT)</div><div class="formula-main">$$\\begin{array}{c|ccccc} \\theta & 0^\\circ & 30^\\circ & 45^\\circ & 60^\\circ & 90^\\circ \\\\ \\hline \\sin\\theta & 0 & \\dfrac{1}{2} & \\dfrac{\\sqrt{2}}{2} & \\dfrac{\\sqrt{3}}{2} & 1 \\\\[4pt] \\cos\\theta & 1 & \\dfrac{\\sqrt{3}}{2} & \\dfrac{\\sqrt{2}}{2} & \\dfrac{1}{2} & 0 \\\\[4pt] \\tan\\theta & 0 & \\dfrac{\\sqrt{3}}{3} & 1 & \\sqrt{3} & \\text{undef} \\end{array}$$</div></div>

<div class="l-note"><strong>Memory trick &mdash; the "$\\sqrt{n}/2$" rule.</strong> Write the sine row as $\\sqrt{0}/2, \\sqrt{1}/2, \\sqrt{2}/2, \\sqrt{3}/2, \\sqrt{4}/2$ for the five columns. Simplify: $0, 1/2, \\sqrt{2}/2, \\sqrt{3}/2, 1$. That is the sine row. The cosine row is the same but reversed. The tangent is sin/cos. With this trick you can rebuild the table from memory in 15 seconds.</div>

<div class="calc-formula"><div class="formula-label">THE SAME TABLE IN RADIANS</div><div class="formula-main">$$\\begin{array}{c|ccccc} \\theta & 0 & \\dfrac{\\pi}{6} & \\dfrac{\\pi}{4} & \\dfrac{\\pi}{3} & \\dfrac{\\pi}{2} \\\\ \\hline \\sin\\theta & 0 & \\dfrac{1}{2} & \\dfrac{\\sqrt{2}}{2} & \\dfrac{\\sqrt{3}}{2} & 1 \\\\[4pt] \\cos\\theta & 1 & \\dfrac{\\sqrt{3}}{2} & \\dfrac{\\sqrt{2}}{2} & \\dfrac{1}{2} & 0 \\end{array}$$</div><div class="formula-sub">Radian and degree columns line up: 0 = 0&deg;, &pi;/6 = 30&deg;, &pi;/4 = 45&deg;, &pi;/3 = 60&deg;, &pi;/2 = 90&deg;. AYT problems can be stated in either units &mdash; you must be comfortable with both.</div></div>

<h2 class="l-title">5. The Boundary Angles 0&deg;, 90&deg;, 180&deg;, 270&deg;, 360&deg;</h2>

<p class="l-text">The triangle method does not handle 0&deg;, 90&deg;, 180&deg;, 270&deg;, or 360&deg; directly &mdash; you cannot draw a right triangle with a zero-degree angle or a flat 180&deg; angle. For these <strong>boundary angles</strong> we use the unit circle definition: $(\\cos\\theta, \\sin\\theta)$ is the point on the unit circle reached by rotating angle $\\theta$ counter-clockwise from the positive x-axis.</p>

<div class="calc-cards">
<div class="calc-card"><div class="card-title">$\\theta = 0^\\circ$ &mdash; the point $(1, 0)$</div><div class="card-body">$\\cos 0^\\circ = 1$, $\\sin 0^\\circ = 0$, $\\tan 0^\\circ = 0/1 = 0$. The starting point of every rotation.</div></div>
<div class="calc-card"><div class="card-title">$\\theta = 90^\\circ$ &mdash; the point $(0, 1)$</div><div class="card-body">$\\cos 90^\\circ = 0$, $\\sin 90^\\circ = 1$, $\\tan 90^\\circ = 1/0$ &mdash; <strong>undefined</strong> (vertical line, infinite slope).</div></div>
<div class="calc-card"><div class="card-title">$\\theta = 180^\\circ$ &mdash; the point $(-1, 0)$</div><div class="card-body">$\\cos 180^\\circ = -1$, $\\sin 180^\\circ = 0$, $\\tan 180^\\circ = 0/(-1) = 0$. Opposite side of the circle from 0&deg;.</div></div>
<div class="calc-card"><div class="card-title">$\\theta = 270^\\circ$ &mdash; the point $(0, -1)$</div><div class="card-body">$\\cos 270^\\circ = 0$, $\\sin 270^\\circ = -1$, $\\tan 270^\\circ$ &mdash; <strong>undefined</strong> again (vertical, infinite).</div></div>
<div class="calc-card"><div class="card-title">$\\theta = 360^\\circ$ &mdash; back to $(1, 0)$</div><div class="card-body">Same values as 0&deg;. After one full turn you return to the starting point: $\\cos 360^\\circ = 1$, $\\sin 360^\\circ = 0$.</div></div>
</div>

<div id="plot-circle-en" class="plotly-graph" style="height:480px"></div>
<script>setTimeout(function(){
var th=[];var cx=[];var cy=[];for(var i=0;i<=360;i++){th.push(i);cx.push(Math.cos(i*Math.PI/180));cy.push(Math.sin(i*Math.PI/180));}
var circ={x:cx,y:cy,mode:"lines",line:{color:"rgba(59,130,246,0.45)",width:2},name:"unit circle",showlegend:false,hoverinfo:"skip"};
var pts={x:[1,Math.sqrt(3)/2,Math.sqrt(2)/2,1/2,0,-1/2,-Math.sqrt(2)/2,-Math.sqrt(3)/2,-1,-Math.sqrt(3)/2,-Math.sqrt(2)/2,-1/2,0,1/2,Math.sqrt(2)/2,Math.sqrt(3)/2],
y:[0,1/2,Math.sqrt(2)/2,Math.sqrt(3)/2,1,Math.sqrt(3)/2,Math.sqrt(2)/2,1/2,0,-1/2,-Math.sqrt(2)/2,-Math.sqrt(3)/2,-1,-Math.sqrt(3)/2,-Math.sqrt(2)/2,-1/2],
mode:"markers",marker:{size:9,color:"#3b82f6"},name:"special angles",showlegend:false};
var lbl=[
{x:1.12,y:0,text:"0&deg; / 360&deg;<br>(1, 0)",showarrow:false,font:{color:"#cbd5e1",size:10}},
{x:0.95,y:0.62,text:"30&deg;<br>(&radic;3/2, 1/2)",showarrow:false,font:{color:"#cbd5e1",size:10}},
{x:0.82,y:0.82,text:"45&deg;",showarrow:false,font:{color:"#cbd5e1",size:10}},
{x:0.62,y:0.95,text:"60&deg;",showarrow:false,font:{color:"#cbd5e1",size:10}},
{x:0,y:1.12,text:"90&deg;<br>(0, 1)",showarrow:false,font:{color:"#cbd5e1",size:10}},
{x:-0.62,y:0.95,text:"120&deg;",showarrow:false,font:{color:"#cbd5e1",size:10}},
{x:-0.95,y:0.62,text:"150&deg;",showarrow:false,font:{color:"#cbd5e1",size:10}},
{x:-1.18,y:0,text:"180&deg;<br>(&minus;1, 0)",showarrow:false,font:{color:"#cbd5e1",size:10}},
{x:-0.95,y:-0.62,text:"210&deg;",showarrow:false,font:{color:"#cbd5e1",size:10}},
{x:-0.62,y:-0.95,text:"240&deg;",showarrow:false,font:{color:"#cbd5e1",size:10}},
{x:0,y:-1.12,text:"270&deg;<br>(0, &minus;1)",showarrow:false,font:{color:"#cbd5e1",size:10}},
{x:0.62,y:-0.95,text:"300&deg;",showarrow:false,font:{color:"#cbd5e1",size:10}},
{x:0.95,y:-0.62,text:"330&deg;",showarrow:false,font:{color:"#cbd5e1",size:10}}
];
var ax={x:[-1.3,1.3,null,0,0],y:[0,0,null,-1.3,1.3],mode:"lines",line:{color:"rgba(255,255,255,0.15)",width:1},showlegend:false,hoverinfo:"skip"};
var layout={paper_bgcolor:"rgba(0,0,0,0)",plot_bgcolor:"rgba(0,0,0,0)",font:{color:"#ebe6dc"},xaxis:{range:[-1.45,1.45],showgrid:false,zeroline:false,visible:false},yaxis:{range:[-1.45,1.45],showgrid:false,zeroline:false,visible:false,scaleanchor:"x"},annotations:lbl,margin:{t:20,r:20,b:20,l:20},showlegend:false};
Plotly.newPlot("plot-circle-en",[circ,ax,pts],layout,{responsive:true,displayModeBar:false});
},250)</script>

<div class="calc-graph"><div class="graph-caption"><strong>What this graph shows:</strong> The unit circle with the 16 most-referenced special-angle points marked. Each point has coordinates $(\\cos\\theta, \\sin\\theta)$. The four "boundary" angles 0&deg;, 90&deg;, 180&deg;, 270&deg; sit on the axes; the eight "$\\sqrt{3}/2, 1/2$" angles (30, 60, 120, 150, 210, 240, 300, 330) and four "$\\sqrt{2}/2$" angles (45, 135, 225, 315) sit in the four quadrants.</div></div>

<div class="calc-formula"><div class="formula-label">EXTENDED TABLE INCLUDING BOUNDARY ANGLES</div><div class="formula-main">$$\\begin{array}{c|ccccccccc} \\theta & 0^\\circ & 30^\\circ & 45^\\circ & 60^\\circ & 90^\\circ & 180^\\circ & 270^\\circ & 360^\\circ \\\\ \\hline \\sin\\theta & 0 & \\frac{1}{2} & \\frac{\\sqrt{2}}{2} & \\frac{\\sqrt{3}}{2} & 1 & 0 & -1 & 0 \\\\[3pt] \\cos\\theta & 1 & \\frac{\\sqrt{3}}{2} & \\frac{\\sqrt{2}}{2} & \\frac{1}{2} & 0 & -1 & 0 & 1 \\\\[3pt] \\tan\\theta & 0 & \\frac{\\sqrt{3}}{3} & 1 & \\sqrt{3} & \\text{und.} & 0 & \\text{und.} & 0 \\end{array}$$</div></div>

<h2 class="l-title">6. Negative Angles and Angles Above 360&deg;</h2>

<p class="l-text">An angle of 400&deg; describes a point on the unit circle obtained by rotating one full turn (360&deg;) and then an extra 40&deg;. The endpoint is the same as that of 40&deg;. Likewise an angle of &minus;30&deg; means rotating <em>clockwise</em> by 30&deg; &mdash; the endpoint is the same as that of 330&deg;. We say the two angles are <strong>coterminal</strong>.</p>

<div class="calc-formula"><div class="formula-label">COTERMINAL-ANGLE RULE</div><div class="formula-main">$$\\theta \\;\\text{ and }\\; \\theta + 360^\\circ k \\;\\;(k \\in \\mathbb{Z}) \\;\\;\\text{give the same trig values}$$</div><div class="formula-sub">Add or subtract whole multiples of 360&deg; (or 2&pi; radians) freely &mdash; sin, cos, and tan are unchanged.</div></div>

<div class="calc-cards">
<div class="calc-card"><div class="card-title">Above 360&deg;</div><div class="card-body">$\\sin 400^\\circ = \\sin(400^\\circ - 360^\\circ) = \\sin 40^\\circ$. Subtract 360&deg; until you land in $[0^\\circ, 360^\\circ)$.</div></div>
<div class="calc-card"><div class="card-title">Above 720&deg;</div><div class="card-body">$\\cos 810^\\circ = \\cos(810^\\circ - 720^\\circ) = \\cos 90^\\circ = 0$. Subtract <strong>two</strong> full turns.</div></div>
<div class="calc-card"><div class="card-title">Negative</div><div class="card-body">$\\sin(-60^\\circ) = \\sin(-60^\\circ + 360^\\circ) = \\sin 300^\\circ = -\\sqrt{3}/2$. Add 360&deg; until you become positive.</div></div>
<div class="calc-card"><div class="card-title">Very negative</div><div class="card-body">$\\cos(-450^\\circ) = \\cos(-450^\\circ + 720^\\circ) = \\cos 270^\\circ = 0$. Add as many 360&deg;'s as needed.</div></div>
</div>

<div class="l-note"><strong>Parity shortcut.</strong> Sine and tangent are <em>odd</em>: $\\sin(-\\theta) = -\\sin\\theta$, $\\tan(-\\theta) = -\\tan\\theta$. Cosine is <em>even</em>: $\\cos(-\\theta) = \\cos\\theta$. So $\\sin(-60^\\circ) = -\\sin 60^\\circ = -\\sqrt{3}/2$ &mdash; one line, no addition of 360&deg; needed. We will prove these from the unit-circle picture in Lesson 4.</div>

<h2 class="l-title">7. The Reference-Angle Method</h2>

<p class="l-text">The reference angle is the single most useful trick for evaluating trig functions of <em>any</em> angle without a calculator. The idea: every angle in any quadrant has an "acute twin" in the first quadrant. Find that twin (the <strong>reference angle</strong>), look up its value from the special-angle table, then fix the sign using the quadrant.</p>

<div class="calc-formula"><div class="formula-label">DEFINITION OF REFERENCE ANGLE</div><div class="formula-main">$$\\theta' = \\text{the acute angle between the terminal side of } \\theta \\text{ and the x-axis}$$</div><div class="formula-sub">Always measured to the nearest x-axis, never the y-axis. Result is in $[0^\\circ, 90^\\circ]$.</div></div>

<div class="calc-cards">
<div class="calc-card"><div class="card-title">Quadrant I ($0^\\circ$ &ndash; $90^\\circ$)</div><div class="card-body">$\\theta' = \\theta$. The angle itself is acute, nothing to subtract.</div></div>
<div class="calc-card"><div class="card-title">Quadrant II ($90^\\circ$ &ndash; $180^\\circ$)</div><div class="card-body">$\\theta' = 180^\\circ - \\theta$. Example: 150&deg; has reference 30&deg;.</div></div>
<div class="calc-card"><div class="card-title">Quadrant III ($180^\\circ$ &ndash; $270^\\circ$)</div><div class="card-body">$\\theta' = \\theta - 180^\\circ$. Example: 210&deg; has reference 30&deg;.</div></div>
<div class="calc-card"><div class="card-title">Quadrant IV ($270^\\circ$ &ndash; $360^\\circ$)</div><div class="card-body">$\\theta' = 360^\\circ - \\theta$. Example: 330&deg; has reference 30&deg;.</div></div>
</div>

<p class="l-text"><strong>Sign by quadrant &mdash; the "ASTC" rule.</strong> Reading counter-clockwise from quadrant I: <strong>A</strong>ll, <strong>S</strong>ine, <strong>T</strong>angent, <strong>C</strong>osine. In each quadrant only the listed function (and its reciprocal) is positive; the others are negative.</p>

<div class="calc-formula"><div class="formula-label">SIGN OF SIN, COS, TAN BY QUADRANT</div><div class="formula-main">$$\\begin{array}{c|ccc} \\text{Quadrant} & \\sin\\theta & \\cos\\theta & \\tan\\theta \\\\ \\hline \\text{I} & + & + & + \\\\ \\text{II} & + & - & - \\\\ \\text{III} & - & - & + \\\\ \\text{IV} & - & + & - \\end{array}$$</div><div class="formula-sub">Mnemonic <strong>ASTC</strong>: All Sine Tangent Cosine. In Turkish: "All Students Take Calculus" or "Hepsi &mdash; Sin&uuml;s &mdash; Tan&#x015F;ant &mdash; Kos&uuml;s".</div></div>

<div class="calc-steps">
<div class="calc-step"><div class="step-num">1</div><div class="step-content"><div class="step-title">Reduce $\\theta$ to $[0^\\circ, 360^\\circ)$</div><div class="step-detail">Add or subtract multiples of 360&deg; until $\\theta$ lies in one full turn.</div></div></div>
<div class="calc-step"><div class="step-num">2</div><div class="step-content"><div class="step-title">Identify the quadrant of $\\theta$</div><div class="step-detail">I (0-90), II (90-180), III (180-270), IV (270-360).</div></div></div>
<div class="calc-step"><div class="step-num">3</div><div class="step-content"><div class="step-title">Compute the reference angle $\\theta'$</div><div class="step-detail">Use the formula for the quadrant. Result will be a special angle if the original was special.</div></div></div>
<div class="calc-step"><div class="step-num">4</div><div class="step-content"><div class="step-title">Look up the value of sin/cos/tan at $\\theta'$</div><div class="step-detail">From the first-quadrant table.</div></div></div>
<div class="calc-step"><div class="step-num">5</div><div class="step-content"><div class="step-title">Attach the correct sign using ASTC</div><div class="step-detail">Positive if the function is in the "allowed" group for that quadrant, negative otherwise.</div></div></div>
</div>

<div id="plot-quad-en" class="plotly-graph" style="height:420px"></div>
<script>setTimeout(function(){
var th=[];var cx=[];var cy=[];for(var i=0;i<=360;i++){th.push(i);cx.push(Math.cos(i*Math.PI/180));cy.push(Math.sin(i*Math.PI/180));}
var circ={x:cx,y:cy,mode:"lines",line:{color:"rgba(59,130,246,0.45)",width:2},showlegend:false,hoverinfo:"skip"};
var ax={x:[-1.4,1.4,null,0,0],y:[0,0,null,-1.4,1.4],mode:"lines",line:{color:"rgba(255,255,255,0.20)",width:1},showlegend:false,hoverinfo:"skip"};
var lbl=[
{x:0.55,y:0.55,text:"<b>I</b><br>sin&nbsp;+&nbsp;&nbsp;cos&nbsp;+<br>tan&nbsp;+<br><b>All&nbsp;positive</b>",showarrow:false,font:{color:"#86efac",size:11}},
{x:-0.55,y:0.55,text:"<b>II</b><br>sin&nbsp;+&nbsp;&nbsp;cos&nbsp;&minus;<br>tan&nbsp;&minus;<br><b>Sin&nbsp;only</b>",showarrow:false,font:{color:"#fcd34d",size:11}},
{x:-0.55,y:-0.55,text:"<b>III</b><br>sin&nbsp;&minus;&nbsp;&nbsp;cos&nbsp;&minus;<br>tan&nbsp;+<br><b>Tan&nbsp;only</b>",showarrow:false,font:{color:"#fb923c",size:11}},
{x:0.55,y:-0.55,text:"<b>IV</b><br>sin&nbsp;&minus;&nbsp;&nbsp;cos&nbsp;+<br>tan&nbsp;&minus;<br><b>Cos&nbsp;only</b>",showarrow:false,font:{color:"#67e8f9",size:11}}
];
var ray150={x:[0,Math.cos(150*Math.PI/180)],y:[0,Math.sin(150*Math.PI/180)],mode:"lines+markers",line:{color:"#f87171",width:2.5},marker:{size:[0,9],color:"#f87171"},name:"&theta;=150&deg;",showlegend:false};
var arc=[];for(var j=150;j<=180;j++){arc.push({x:0.35*Math.cos(j*Math.PI/180),y:0.35*Math.sin(j*Math.PI/180)});}
var arx=arc.map(function(p){return p.x;});var ary=arc.map(function(p){return p.y;});
var refarc={x:arx,y:ary,mode:"lines",line:{color:"#f87171",width:2,dash:"dot"},showlegend:false,hoverinfo:"skip"};
var refann=[
{x:Math.cos(150*Math.PI/180)-0.15,y:Math.sin(150*Math.PI/180)+0.08,text:"&theta;=150&deg;",showarrow:false,font:{color:"#f87171",size:11}},
{x:-0.50,y:0.10,text:"&theta;&#x2032;=30&deg;",showarrow:false,font:{color:"#f87171",size:10}}
];
var layout={paper_bgcolor:"rgba(0,0,0,0)",plot_bgcolor:"rgba(0,0,0,0)",font:{color:"#ebe6dc"},xaxis:{range:[-1.4,1.4],showgrid:false,zeroline:false,visible:false},yaxis:{range:[-1.4,1.4],showgrid:false,zeroline:false,visible:false,scaleanchor:"x"},annotations:lbl.concat(refann),margin:{t:20,r:20,b:20,l:20},showlegend:false};
Plotly.newPlot("plot-quad-en",[circ,ax,ray150,refarc],layout,{responsive:true,displayModeBar:false});
},250)</script>

<div class="calc-graph"><div class="graph-caption"><strong>What this graph shows:</strong> The four quadrants of the unit circle with ASTC signs labelled. The red ray illustrates the reference-angle idea for $\\theta = 150^\\circ$: its terminal side lies in quadrant II, the acute angle to the x-axis (reference angle) is $180^\\circ - 150^\\circ = 30^\\circ$, and the sign of sin&nbsp;150&deg; is positive (quadrant II) while cos&nbsp;150&deg; is negative.</div></div>

<div class="calc-example"><div class="example-label">WORKED EXAMPLE &mdash; sin&nbsp;150&deg;</div><div class="example-body"><strong>Step 1.</strong> 150&deg; is already in $[0^\\circ, 360^\\circ)$.<br><br><strong>Step 2.</strong> 150&deg; lies in quadrant II (between 90&deg; and 180&deg;).<br><br><strong>Step 3.</strong> Reference angle $= 180^\\circ - 150^\\circ = 30^\\circ$.<br><br><strong>Step 4.</strong> From the table, $\\sin 30^\\circ = 1/2$.<br><br><strong>Step 5.</strong> Sign: in quadrant II, sine is <em>positive</em> (ASTC: S).<br><br><strong>Answer:</strong> $\\sin 150^\\circ = +\\dfrac{1}{2}$.</div></div>

<h2 class="l-title">8. Worked Exercises</h2>

<p class="l-text">Eight classic AYT-style problems. Solve each with the reference-angle method before reading the solution.</p>

<div class="calc-example"><div class="example-label">EXERCISE 1 &mdash; cos&nbsp;240&deg;</div><div class="example-body"><strong>Quadrant III</strong> (180 &lt; 240 &lt; 270). Reference $= 240 - 180 = 60^\\circ$. From the table $\\cos 60^\\circ = 1/2$. Sign in QIII: cosine is negative (ASTC says only T is positive). Therefore $\\cos 240^\\circ = -\\dfrac{1}{2}$.</div></div>

<div class="calc-example"><div class="example-label">EXERCISE 2 &mdash; tan(&minus;60&deg;)</div><div class="example-body">Two ways. <em>Parity:</em> tangent is odd, so $\\tan(-60^\\circ) = -\\tan 60^\\circ = -\\sqrt{3}$. <em>Reference:</em> $-60^\\circ + 360^\\circ = 300^\\circ$, quadrant IV, reference $360 - 300 = 60^\\circ$. $\\tan 60^\\circ = \\sqrt{3}$; sign in QIV: tangent is negative. Result: $\\tan(-60^\\circ) = -\\sqrt{3}$. Both methods agree.</div></div>

<div class="calc-example"><div class="example-label">EXERCISE 3 &mdash; sin(7&pi;/6)</div><div class="example-body">Convert to degrees: $7\\pi/6 = 7 \\cdot 180^\\circ / 6 = 210^\\circ$. Quadrant III. Reference $= 210 - 180 = 30^\\circ$. $\\sin 30^\\circ = 1/2$. Sign in QIII: sine negative. Answer: $\\sin(7\\pi/6) = -\\dfrac{1}{2}$.</div></div>

<div class="calc-example"><div class="example-label">EXERCISE 4 &mdash; cos(5&pi;/4)</div><div class="example-body">$5\\pi/4 = 225^\\circ$. Quadrant III. Reference $= 225 - 180 = 45^\\circ$. $\\cos 45^\\circ = \\sqrt{2}/2$. Sign in QIII: cosine negative. Answer: $\\cos(5\\pi/4) = -\\dfrac{\\sqrt{2}}{2}$.</div></div>

<div class="calc-example"><div class="example-label">EXERCISE 5 &mdash; tan&nbsp;315&deg;</div><div class="example-body">Quadrant IV. Reference $= 360 - 315 = 45^\\circ$. $\\tan 45^\\circ = 1$. Sign in QIV: tangent negative. Answer: $\\tan 315^\\circ = -1$.</div></div>

<div class="calc-example"><div class="example-label">EXERCISE 6 &mdash; sin&nbsp;420&deg;</div><div class="example-body">$420 - 360 = 60^\\circ$ (coterminal). Quadrant I. $\\sin 60^\\circ = \\sqrt{3}/2$. Sign positive. Answer: $\\sin 420^\\circ = \\dfrac{\\sqrt{3}}{2}$.</div></div>

<div class="calc-example"><div class="example-label">EXERCISE 7 &mdash; cos(&minus;5&pi;/3)</div><div class="example-body">Cosine is even: $\\cos(-5\\pi/3) = \\cos(5\\pi/3) = \\cos 300^\\circ$. Quadrant IV. Reference $= 360 - 300 = 60^\\circ$. $\\cos 60^\\circ = 1/2$. Sign in QIV: cosine positive. Answer: $\\cos(-5\\pi/3) = \\dfrac{1}{2}$.</div></div>

<div class="calc-example"><div class="example-label">EXERCISE 8 &mdash; sin&nbsp;120&deg; &middot; cos&nbsp;330&deg; + tan&nbsp;225&deg;</div><div class="example-body">Three pieces.<br>$\\sin 120^\\circ$: QII, ref 60&deg;, sin positive $\\Rightarrow \\sqrt{3}/2$.<br>$\\cos 330^\\circ$: QIV, ref 30&deg;, cos positive $\\Rightarrow \\sqrt{3}/2$.<br>$\\tan 225^\\circ$: QIII, ref 45&deg;, tan positive $\\Rightarrow 1$.<br><br>Combine: $\\dfrac{\\sqrt{3}}{2} \\cdot \\dfrac{\\sqrt{3}}{2} + 1 = \\dfrac{3}{4} + 1 = \\dfrac{7}{4}$.</div></div>

<div class="l-note"><strong>Summary.</strong> In one lesson you have learned to evaluate the trig functions of <em>any</em> angle &mdash; positive, negative, large, or small &mdash; provided it reduces to one of the five special first-quadrant angles. This single skill underlies nearly every routine trigonometry problem on the YKS-AYT.</div>

<p class="l-text">In Lesson 4 we extend these foundations to the Pythagorean identity $\\sin^2\\theta + \\cos^2\\theta = 1$ and the sum-difference formulas, which together let us evaluate angles that are <em>not</em> special by combining ones that are.</p>`,

tr: `<p class="l-text"><strong>&Ouml;zel a&ccedil;&#x0131;lar trigonometrinin i&scedil; atlar&#x0131;d&#x0131;r.</strong> Bir lise s&#x0131;nav&#x0131;nda, bir fizik sorusunda ya da bir geometri &ccedil;iziminde &ccedil;&ouml;zd&uuml;&#x011F;&uuml;n&uuml;z neredeyse her trigonometri probleminin sin&uuml;s, kos&uuml;s ya da tanjant&#x0131;n&#x0131; istedi&#x011F;i a&ccedil;&#x0131; k&uuml;&ccedil;&uuml;k bir grupta toplan&#x0131;r: 0&deg;, 30&deg;, 45&deg;, 60&deg;, 90&deg; ve di&#x011F;er &uuml;&ccedil; b&ouml;lgedeki yans&#x0131;malar&#x0131;. Bu a&ccedil;&#x0131;lar i&ccedil;in tam de&#x011F;erleri ezberlerseniz &mdash; ve daha &ouml;nemlisi <em>nereden geldi&#x011F;ini</em> anlarsan&#x0131;z &mdash; trigonometrinin geri kalan&#x0131; gizemli bir listeden &ccedil;&#x0131;k&#x0131;p temiz, &ouml;ng&ouml;r&uuml;lebilir bir desene d&ouml;n&uuml;&scedil;&uuml;r.</p>

<p class="l-text">Bu derste 30-60-90 ve 45-45-90 &uuml;&ccedil;genlerinin de&#x011F;erlerini sadece Pisagor teoremiyle s&#x0131;f&#x0131;rdan t&uuml;retiyoruz, ard&#x0131;ndan her T&uuml;rk lise (YKS-AYT) &ouml;&#x011F;rencisinin parmaklar&#x0131;n&#x0131;n ucunda olmas&#x0131; gereken &uuml;nl&uuml; "trigonometri tablosunu" kuruyoruz. Tabloyu birim &ccedil;ember yard&#x0131;m&#x0131;yla 0&deg;, 90&deg;, 180&deg;, 270&deg;, 360&deg; s&#x0131;n&#x0131;r a&ccedil;&#x0131;lar&#x0131;na geni&scedil;letiyoruz ve son olarak <strong>referans a&ccedil;&#x0131; y&ouml;ntemini</strong> &ouml;&#x011F;reniyoruz &mdash; bu y&ouml;ntem, negatif a&ccedil;&#x0131;lar ve 360&deg;&apos;den b&uuml;y&uuml;k a&ccedil;&#x0131;lar dahil <em>her</em> a&ccedil;&#x0131;y&#x0131; zaten bildi&#x011F;iniz &ouml;zel a&ccedil;&#x0131;lara indirgemenizi sa&#x011F;lar.</p>

<div class="lesson-outcomes" style="background:rgba(59,130,246,0.06);border-left:3px solid #3b82f6;padding:1rem 1.2rem;margin:1.5rem 0;border-radius:0 8px 8px 0">
<div style="font-size:0.78rem;font-weight:700;letter-spacing:0.08em;color:#3b82f6;margin-bottom:0.6rem">NE &Ouml;&#x011E;RENECEKS&#x0130;N&#x0130;Z</div>
<ul style="margin:0;padding-left:1.3rem;line-height:1.65;font-size:0.93rem;color:rgba(235,230,220,0.92)">
<li>30&deg;-60&deg;-90&deg; kenar oranlar&#x0131;n&#x0131; ikiye b&ouml;l&uuml;nm&uuml;&scedil; e&scedil;kenar &uuml;&ccedil;genden t&uuml;retmek</li>
<li>45&deg;-45&deg;-90&deg; kenar oranlar&#x0131;n&#x0131; ikizkenar dik &uuml;&ccedil;genden t&uuml;retmek</li>
<li>sin, cos, tan i&ccedil;in &ouml;zel a&ccedil;&#x0131; tablosunu ezberlemek (ve gerekirse yeniden in&scedil;a etmek)</li>
<li>0&deg;, 90&deg;, 180&deg;, 270&deg;, 360&deg; s&#x0131;n&#x0131;r a&ccedil;&#x0131;lar&#x0131;nda sin, cos, tan de&#x011F;erlerini okumak</li>
<li>Referans a&ccedil;&#x0131; y&ouml;ntemiyle herhangi bir b&ouml;lgedeki a&ccedil;&#x0131; i&ccedil;in trig fonksiyonlar&#x0131;n&#x0131; hesaplamak</li>
<li>Negatif a&ccedil;&#x0131;lar&#x0131; ve 360&deg;&apos;in &uuml;st&uuml;ndeki a&ccedil;&#x0131;lar&#x0131; e&scedil; sonlu &ouml;zel a&ccedil;&#x0131;lara indirgemek</li>
</ul>
</div>

<h2 class="l-title">1. &Ouml;zel A&ccedil;&#x0131;lar Neden &Ouml;nemli?</h2>

<div class="calc-highlight"><strong>G&uuml;nl&uuml;k g&ouml;r&uuml;nt&uuml;:</strong> Herhangi bir AYT matematik kitap&ccedil;&#x0131;&#x011F;&#x0131;n&#x0131;, e&#x011F;ik bir rampa hakk&#x0131;ndaki herhangi bir fizik problemini, d&uuml;zg&uuml;n bir alt&#x0131;genle ilgili herhangi bir geometri sorusunu a&ccedil;&#x0131;n &mdash; ayn&#x0131; a&ccedil;&#x0131;lar tekrar tekrar kar&#x015F;&#x0131;n&#x0131;za &ccedil;&#x0131;kar: 30&deg;, 45&deg;, 60&deg;. Bu rastlant&#x0131; de&#x011F;ildir &mdash; bu a&ccedil;&#x0131;lar temel geometrinin en simetrik &scedil;ekillerinden (e&scedil;kenar &uuml;&ccedil;gen ve kare) do&#x011F;al olarak ortaya &ccedil;&#x0131;kar, dolay&#x0131;s&#x0131;yla simetri devreye girdi&#x011F;inde her zaman g&ouml;r&uuml;n&uuml;rler.</div>

<p class="l-text">Birinci b&ouml;lgede 0&deg;, 30&deg;, 45&deg;, 60&deg;, 90&deg; ve di&#x011F;er &uuml;&ccedil; b&ouml;lgedeki yans&#x0131;malar&#x0131; toplam birka&ccedil; a&ccedil;&#x0131;, <strong>T&uuml;rk lise s&#x0131;navlar&#x0131;nda sorulan trig de&#x011F;erlerinin yakla&#x015F;&#x0131;k %80&apos;ini</strong> kapsar. Bu de&#x011F;erleri bilmek size &scedil;unlar&#x0131; kazand&#x0131;r&#x0131;r:</p>

<div class="calc-cards">
<div class="calc-card"><div class="card-title">YKS-AYT sorular&#x0131;n&#x0131; h&#x0131;zl&#x0131; &ccedil;&ouml;zmek</div><div class="card-body">Hesap makinesi yasak. sin&nbsp;30&deg; = 1/2 ve cos&nbsp;60&deg; = 1/2 oldu&#x011F;unu an&#x0131;nda biliyorsan&#x0131;z her soruda 30 saniye kazan&#x0131;rs&#x0131;n&#x0131;z &mdash; s&#x0131;n&#x0131;rl&#x0131; s&uuml;rede b&uuml;y&uuml;k bir avantaj.</div></div>
<div class="calc-card"><div class="card-title">Fizik form&uuml;llerini okumak</div><div class="card-body">30&deg;&apos;lik rampada bile&#x015F;ke kuvvet, maksimum menzil i&ccedil;in 45&deg;&apos;de at&#x0131;lan c&#x0131;s&#x0131;mlar, 60&deg;&apos;lik prizmadan k&#x0131;r&#x0131;lan &#x0131;&#x015F;&#x0131;k &mdash; ayn&#x0131; a&ccedil;&#x0131;lar, defalarca.</div></div>
<div class="calc-card"><div class="card-title">Birim &ccedil;emberi kurmak</div><div class="card-body">Birim &ccedil;emberde en &ccedil;ok ge&ccedil;en 16 nokta hep bu birka&ccedil; a&ccedil;&#x0131;dan &uuml;retilir. Bunlar&#x0131; bildi&#x011F;inizde t&uuml;m &ccedil;emberi ezberden &ccedil;izebilirsiniz.</div></div>
<div class="calc-card"><div class="card-title">Genel &ouml;zde&#x015F;likleri kontrol etmek</div><div class="card-body">sin&nbsp;2x = 2&nbsp;sin&nbsp;x&nbsp;cos&nbsp;x gibi bir &ouml;zde&#x015F;likten &#x015F;&uuml;phelendi&#x011F;inizde x = 30&deg; yerle&#x015F;tirmek an&#x0131;nda say&#x0131;sal bir kontrol verir.</div></div>
</div>

<p class="l-text"><strong>Bu dersin stratejisi.</strong> Tabloyu kaba kuvvetle <em>ezberlemenizi</em> istemiyoruz. Bunun yerine de&#x011F;erleri, kalemle 10 saniyede yeniden &ccedil;izebilece&#x011F;iniz iki &uuml;nl&uuml; &uuml;&ccedil;genden t&uuml;retiyoruz. T&uuml;retim do&#x011F;al hissetti&#x011F;inde tablo kendili&#x011F;inden akl&#x0131;n&#x0131;zda kal&#x0131;r.</p>

<h2 class="l-title">2. 30&deg;-60&deg;-90&deg; &Uuml;&ccedil;geni</h2>

<p class="l-text">30-60-90 &uuml;&ccedil;geni, bir <strong>e&scedil;kenar &uuml;&ccedil;genin</strong> tam y&uuml;ksekli&#x011F;i boyunca ikiye b&ouml;l&uuml;nmesiyle elde edilir. Bu tek resim, trig tablosundaki $\\sqrt{3}$ i&ccedil;eren her girdiye kaynakl&#x0131;k eder.</p>

<div class="calc-steps">
<div class="calc-step"><div class="step-num">1</div><div class="step-content"><div class="step-title">Kenar&#x0131; 2 olan bir e&scedil;kenar &uuml;&ccedil;genle ba&#x015F;lay&#x0131;n</div><div class="step-detail">&Uuml;&ccedil; kenar da 2, &uuml;&ccedil; a&ccedil;&#x0131; da 60&deg;. Yar&#x0131; kenarlar tam say&#x0131; &ccedil;&#x0131;ks&#x0131;n diye kenar 1 yerine 2 se&ccedil;iyoruz.</div></div></div>
<div class="calc-step"><div class="step-num">2</div><div class="step-content"><div class="step-title">Bir tepeden y&uuml;ksekli&#x011F;i indirin</div><div class="step-detail">Y&uuml;kseklik, &uuml;st tepeden kar&#x015F;&#x0131; kenar&#x0131;n orta noktas&#x0131;na inilen dik bir do&#x011F;rudur. Simetri gere&#x011F;i &uuml;st a&ccedil;&#x0131;y&#x0131; (60&deg; iki adet 30&deg;&apos;lik par&ccedil;aya) ve alt kenar&#x0131; (2 say&#x0131;s&#x0131; iki adet 1 birimlik par&ccedil;aya) ikiye b&ouml;ler.</div></div></div>
<div class="calc-step"><div class="step-num">3</div><div class="step-content"><div class="step-title">Ortaya &ccedil;&#x0131;kan dik &uuml;&ccedil;geni okuyun</div><div class="step-detail">Yar&#x0131; &uuml;&ccedil;genin a&ccedil;&#x0131;lar&#x0131; 30&deg;, 60&deg;, 90&deg;&apos;dir; iki kenar&#x0131; bilinir: hipoten&uuml;s 2 ve k&#x0131;sa dik kenar 1. Pisagor uzun dik kenar&#x0131; verir.</div></div></div>
<div class="calc-step"><div class="step-num">4</div><div class="step-content"><div class="step-title">Pisagor teoremini uygulay&#x0131;n</div><div class="step-detail">$\\text{uzun}^2 + 1^2 = 2^2 \\implies \\text{uzun}^2 = 3 \\implies \\text{uzun} = \\sqrt{3}$.</div></div></div>
</div>

<div class="calc-formula"><div class="formula-label">30-60-90 KENAR ORANLARI</div><div class="formula-main">$$\\text{30&deg;&apos;nin kar&#x015F;&#x0131;s&#x0131;} : \\text{60&deg;&apos;nin kar&#x015F;&#x0131;s&#x0131;} : \\text{90&deg;&apos;nin kar&#x015F;&#x0131;s&#x0131;} \\;=\\; 1 : \\sqrt{3} : 2$$</div><div class="formula-sub">En k&#x0131;sa kenar, en k&uuml;&ccedil;&uuml;k a&ccedil;&#x0131;n&#x0131;n (30&deg;) kar&#x015F;&#x0131;s&#x0131;ndad&#x0131;r. Hipoten&uuml;s her zaman dik a&ccedil;&#x0131;n&#x0131;n kar&#x015F;&#x0131;s&#x0131;ndad&#x0131;r.</div></div>

<div id="plot-3060-tr" class="plotly-graph" style="height:380px"></div>
<script>setTimeout(function(){
var tri={x:[0,Math.sqrt(3),0,0],y:[0,0,1,0],mode:"lines+markers",fill:"toself",fillcolor:"rgba(59,130,246,0.10)",line:{color:"#3b82f6",width:3},marker:{size:8,color:"#3b82f6"},name:"30-60-90"};
var sqr={x:[0,0.18,0.18,0],y:[0.18,0.18,0,0],mode:"lines",line:{color:"#3b82f6",width:1.5},showlegend:false,hoverinfo:"skip"};
var ann=[
{x:Math.sqrt(3)/2,y:-0.10,text:"&radic;3 (60&deg;&apos;nin kar&#x015F;&#x0131;s&#x0131;)",showarrow:false,font:{color:"#3b82f6",size:13}},
{x:-0.16,y:0.5,text:"1 (30&deg;&apos;nin kar&#x015F;&#x0131;s&#x0131;)",showarrow:false,font:{color:"#3b82f6",size:13},textangle:-90},
{x:Math.sqrt(3)/2+0.18,y:0.55,text:"2 (hipoten&uuml;s)",showarrow:false,font:{color:"#3b82f6",size:13},textangle:-30},
{x:0.32,y:0.06,text:"30&deg;",showarrow:false,font:{color:"#cbd5e1",size:12}},
{x:Math.sqrt(3)-0.20,y:0.06,text:"60&deg;",showarrow:false,font:{color:"#cbd5e1",size:12}},
{x:0.04,y:0.84,text:"90&deg;",showarrow:false,font:{color:"#cbd5e1",size:12}}
];
var layout={paper_bgcolor:"rgba(0,0,0,0)",plot_bgcolor:"rgba(0,0,0,0)",font:{color:"#ebe6dc"},xaxis:{range:[-0.6,2.4],showgrid:false,zeroline:false,visible:false},yaxis:{range:[-0.35,1.4],showgrid:false,zeroline:false,visible:false,scaleanchor:"x"},annotations:ann,margin:{t:20,r:20,b:20,l:20},showlegend:false};
Plotly.newPlot("plot-3060-tr",[tri,sqr],layout,{responsive:true,displayModeBar:false});
},250)</script>

<div class="calc-graph"><div class="graph-caption"><strong>Bu grafik ne g&ouml;steriyor:</strong> Ger&ccedil;ek oranlarda &ccedil;izilmi&#x015F; bir 30-60-90 dik &uuml;&ccedil;geni. En k&#x0131;sa kenar (uzunluk 1) en k&uuml;&ccedil;&uuml;k a&ccedil;&#x0131;n&#x0131;n (30&deg;) kar&#x015F;&#x0131;s&#x0131;ndad&#x0131;r. En uzun dik kenar (uzunluk $\\sqrt{3}$) 60&deg;&apos;nin kar&#x015F;&#x0131;s&#x0131;ndad&#x0131;r. Hipoten&uuml;s (uzunluk 2) dik a&ccedil;&#x0131;n&#x0131;n kar&#x015F;&#x0131;s&#x0131;ndad&#x0131;r &mdash; her zaman b&ouml;yle.</div></div>

<p class="l-text"><strong>Trig oranlar&#x0131;n&#x0131; &uuml;&ccedil;genden okumak.</strong> SOHCAHTOA (sin = kar&#x015F;&#x0131;/hipoten&uuml;s, cos = kom&#x015F;u/hipoten&uuml;s, tan = kar&#x015F;&#x0131;/kom&#x015F;u) ile:</p>

<div class="calc-formula"><div class="formula-label">30&deg; VE 60&deg;&apos;DE DE&#x011E;ERLER</div><div class="formula-main">$$\\sin 30^\\circ = \\frac{1}{2}, \\quad \\cos 30^\\circ = \\frac{\\sqrt{3}}{2}, \\quad \\tan 30^\\circ = \\frac{1}{\\sqrt{3}} = \\frac{\\sqrt{3}}{3}$$ $$\\sin 60^\\circ = \\frac{\\sqrt{3}}{2}, \\quad \\cos 60^\\circ = \\frac{1}{2}, \\quad \\tan 60^\\circ = \\sqrt{3}$$</div></div>

<div class="l-note"><strong>Desen yakalay&#x0131;c&#x0131;.</strong> sin&nbsp;30&deg; = cos&nbsp;60&deg; ve cos&nbsp;30&deg; = sin&nbsp;60&deg; oldu&#x011F;una dikkat edin. Bu, Ders 4&apos;te tekrar kar&#x015F;&#x0131;la&#x015F;aca&#x011F;&#x0131;m&#x0131;z $\\sin\\theta = \\cos(90^\\circ - \\theta)$ kofonksiyon &ouml;zde&#x015F;li&#x011F;inin &ouml;zel bir halidir. &Ccedil;al&#x0131;&#x015F;mas&#x0131;n&#x0131;n nedeni 30&deg; ve 60&deg;&apos;nin <strong>t&uuml;mler</strong> olmas&#x0131;d&#x0131;r: toplamlar&#x0131; 90&deg;&apos;dir.</div>

<h2 class="l-title">3. 45&deg;-45&deg;-90&deg; &Uuml;&ccedil;geni</h2>

<p class="l-text">45-45-90 &uuml;&ccedil;geni daha da basittir: <strong>ikizkenar dik &uuml;&ccedil;gendir</strong>, k&ouml;&#x015F;egeni boyunca ikiye b&ouml;l&uuml;nm&uuml;&#x015F; bir karenin tam yar&#x0131;s&#x0131;d&#x0131;r. Bu resim, trig tablosundaki $\\sqrt{2}$ i&ccedil;eren her girdiye kaynakl&#x0131;k eder.</p>

<div class="calc-steps">
<div class="calc-step"><div class="step-num">1</div><div class="step-content"><div class="step-title">Birim kare ile ba&#x015F;lay&#x0131;n</div><div class="step-detail">D&ouml;rt kenar da 1, d&ouml;rt a&ccedil;&#x0131; da 90&deg;.</div></div></div>
<div class="calc-step"><div class="step-num">2</div><div class="step-content"><div class="step-title">K&ouml;&#x015F;egen boyunca kesin</div><div class="step-detail">Bu, iki e&#x015F; dik &uuml;&ccedil;gen verir. Her birinin dik kenarlar&#x0131; 1, hipoten&uuml;s&uuml; ise k&ouml;&#x015F;egendir.</div></div></div>
<div class="calc-step"><div class="step-num">3</div><div class="step-content"><div class="step-title">A&ccedil;&#x0131;lar&#x0131; okuyun</div><div class="step-detail">Dik olmayan iki a&ccedil;&#x0131;n&#x0131;n toplam&#x0131; 90&deg;&apos;dir (&uuml;&ccedil; a&ccedil;&#x0131; 180&deg;) ve simetri gere&#x011F;i e&#x015F;ittirler. Yani her biri 45&deg;.</div></div></div>
<div class="calc-step"><div class="step-num">4</div><div class="step-content"><div class="step-title">Pisagor teoremini uygulay&#x0131;n</div><div class="step-detail">$\\text{hip}^2 = 1^2 + 1^2 = 2 \\implies \\text{hip} = \\sqrt{2}$.</div></div></div>
</div>

<div class="calc-formula"><div class="formula-label">45-45-90 KENAR ORANLARI</div><div class="formula-main">$$\\text{dik kenar} : \\text{dik kenar} : \\text{hipoten&uuml;s} \\;=\\; 1 : 1 : \\sqrt{2}$$</div><div class="formula-sub">Her iki dik kenar e&#x015F;ittir (&uuml;&ccedil;gen ikizkenar). Hipoten&uuml;s, dik kenar&#x0131;n $\\sqrt{2}$ kat&#x0131;d&#x0131;r.</div></div>

<div id="plot-4545-tr" class="plotly-graph" style="height:380px"></div>
<script>setTimeout(function(){
var tri={x:[0,1,0,0],y:[0,0,1,0],mode:"lines+markers",fill:"toself",fillcolor:"rgba(59,130,246,0.10)",line:{color:"#3b82f6",width:3},marker:{size:8,color:"#3b82f6"},name:"45-45-90"};
var sqr={x:[0,0.10,0.10,0],y:[0.10,0.10,0,0],mode:"lines",line:{color:"#3b82f6",width:1.5},showlegend:false,hoverinfo:"skip"};
var ann=[
{x:0.5,y:-0.10,text:"1 (dik kenar)",showarrow:false,font:{color:"#3b82f6",size:13}},
{x:-0.13,y:0.5,text:"1 (dik kenar)",showarrow:false,font:{color:"#3b82f6",size:13},textangle:-90},
{x:0.62,y:0.55,text:"&radic;2 (hipoten&uuml;s)",showarrow:false,font:{color:"#3b82f6",size:13},textangle:-45},
{x:0.78,y:0.08,text:"45&deg;",showarrow:false,font:{color:"#cbd5e1",size:12}},
{x:0.04,y:0.78,text:"45&deg;",showarrow:false,font:{color:"#cbd5e1",size:12}},
{x:0.05,y:0.04,text:"90&deg;",showarrow:false,font:{color:"#cbd5e1",size:12}}
];
var layout={paper_bgcolor:"rgba(0,0,0,0)",plot_bgcolor:"rgba(0,0,0,0)",font:{color:"#ebe6dc"},xaxis:{range:[-0.4,1.4],showgrid:false,zeroline:false,visible:false},yaxis:{range:[-0.3,1.4],showgrid:false,zeroline:false,visible:false,scaleanchor:"x"},annotations:ann,margin:{t:20,r:20,b:20,l:20},showlegend:false};
Plotly.newPlot("plot-4545-tr",[tri,sqr],layout,{responsive:true,displayModeBar:false});
},250)</script>

<div class="calc-graph"><div class="graph-caption"><strong>Bu grafik ne g&ouml;steriyor:</strong> Ger&ccedil;ek oranlarda &ccedil;izilmi&#x015F; bir 45-45-90 dik &uuml;&ccedil;geni. &#x0130;ki dik kenar e&#x015F;ittir (uzunluk 1). Dik a&ccedil;&#x0131;n&#x0131;n kar&#x015F;&#x0131;s&#x0131;ndaki hipoten&uuml;s, $\\sqrt{2} \\approx 1{,}414$ uzunlu&#x011F;undad&#x0131;r.</div></div>

<div class="calc-formula"><div class="formula-label">45&deg;&apos;DE DE&#x011E;ERLER</div><div class="formula-main">$$\\sin 45^\\circ = \\frac{1}{\\sqrt{2}} = \\frac{\\sqrt{2}}{2}, \\quad \\cos 45^\\circ = \\frac{\\sqrt{2}}{2}, \\quad \\tan 45^\\circ = 1$$</div><div class="formula-sub">45&deg;&apos;de sin&uuml;s ile kos&uuml;s &ccedil;ak&#x0131;&#x015F;&#x0131;r (&uuml;&ccedil;gen iki dik kenarda simetrik). Tanjant 1&apos;e e&#x015F;ittir.</div></div>

<div class="l-note"><strong>Niye paydadan kurtulmak?</strong> $1/\\sqrt{2}$ ve $\\sqrt{2}/2$ tam olarak ayn&#x0131; say&#x0131;d&#x0131;r. T&uuml;rk ders kitaplar&#x0131; (ve AYT cevap anahtar&#x0131;) paydas&#x0131;nda irrasyonel olmayan $\\sqrt{2}/2$ formunu tercih eder. Her iki form da do&#x011F;rudur; soru anahtar&#x0131;n&#x0131;n kulland&#x0131;&#x011F;&#x0131; formu kullan&#x0131;n.</div>

<h2 class="l-title">4. &Ouml;zel A&ccedil;&#x0131; Tablosu</h2>

<p class="l-text">Son iki b&ouml;l&uuml;mdeki &ccedil;al&#x0131;&#x015F;may&#x0131; bir sonraki b&ouml;l&uuml;mde t&uuml;retece&#x011F;imiz 0&deg; ve 90&deg; s&#x0131;n&#x0131;r a&ccedil;&#x0131;lar&#x0131; ile birle&#x015F;tirince, her lise matematik &ouml;&#x011F;rencisinin bilmesi gereken &uuml;nl&uuml; tabloyu elde ederiz:</p>

<div class="calc-formula"><div class="formula-label">&Ouml;ZEL A&Ccedil;I TABLOSU (B&#x0130;R&#x0130;NC&#x0130; B&Ouml;LGE)</div><div class="formula-main">$$\\begin{array}{c|ccccc} \\theta & 0^\\circ & 30^\\circ & 45^\\circ & 60^\\circ & 90^\\circ \\\\ \\hline \\sin\\theta & 0 & \\dfrac{1}{2} & \\dfrac{\\sqrt{2}}{2} & \\dfrac{\\sqrt{3}}{2} & 1 \\\\[4pt] \\cos\\theta & 1 & \\dfrac{\\sqrt{3}}{2} & \\dfrac{\\sqrt{2}}{2} & \\dfrac{1}{2} & 0 \\\\[4pt] \\tan\\theta & 0 & \\dfrac{\\sqrt{3}}{3} & 1 & \\sqrt{3} & \\text{tan&#x0131;ms&#x0131;z} \\end{array}$$</div></div>

<div class="l-note"><strong>Ezber p&uuml;f noktas&#x0131; &mdash; "$\\sqrt{n}/2$" kural&#x0131;.</strong> Sin&uuml;s sat&#x0131;r&#x0131;n&#x0131; be&#x015F; s&uuml;tun i&ccedil;in $\\sqrt{0}/2, \\sqrt{1}/2, \\sqrt{2}/2, \\sqrt{3}/2, \\sqrt{4}/2$ olarak yaz&#x0131;n. Sadele&#x015F;tirin: $0, 1/2, \\sqrt{2}/2, \\sqrt{3}/2, 1$. &#x0130;&#x015F;te sin&uuml;s sat&#x0131;r&#x0131;. Kos&uuml;s sat&#x0131;r&#x0131; ayn&#x0131;d&#x0131;r ama tersten yaz&#x0131;l&#x0131;r. Tanjant ise sin/cos&apos;tur. Bu p&uuml;f noktas&#x0131;yla tabloyu 15 saniyede ezberden kurars&#x0131;n&#x0131;z.</div>

<div class="calc-formula"><div class="formula-label">AYNI TABLO RADYAN C&#x0130;NS&#x0130;NDEN</div><div class="formula-main">$$\\begin{array}{c|ccccc} \\theta & 0 & \\dfrac{\\pi}{6} & \\dfrac{\\pi}{4} & \\dfrac{\\pi}{3} & \\dfrac{\\pi}{2} \\\\ \\hline \\sin\\theta & 0 & \\dfrac{1}{2} & \\dfrac{\\sqrt{2}}{2} & \\dfrac{\\sqrt{3}}{2} & 1 \\\\[4pt] \\cos\\theta & 1 & \\dfrac{\\sqrt{3}}{2} & \\dfrac{\\sqrt{2}}{2} & \\dfrac{1}{2} & 0 \\end{array}$$</div><div class="formula-sub">Radyan ve derece s&uuml;tunlar&#x0131; e&#x015F;le&#x015F;ir: 0 = 0&deg;, &pi;/6 = 30&deg;, &pi;/4 = 45&deg;, &pi;/3 = 60&deg;, &pi;/2 = 90&deg;. AYT sorular&#x0131; iki birim de kullanabilir &mdash; her ikisinde de rahat olmal&#x0131;s&#x0131;n&#x0131;z.</div></div>

<h2 class="l-title">5. 0&deg;, 90&deg;, 180&deg;, 270&deg;, 360&deg; S&#x0131;n&#x0131;r A&ccedil;&#x0131;lar&#x0131;</h2>

<p class="l-text">&Uuml;&ccedil;gen y&ouml;ntemi 0&deg;, 90&deg;, 180&deg;, 270&deg; ya da 360&deg; i&ccedil;in do&#x011F;rudan i&#x015F;e yaramaz &mdash; s&#x0131;f&#x0131;r dereceli ya da 180&deg;&apos;lik bir d&uuml;z a&ccedil;&#x0131;ya sahip bir dik &uuml;&ccedil;gen &ccedil;izemezsiniz. Bu <strong>s&#x0131;n&#x0131;r a&ccedil;&#x0131;lar&#x0131;</strong> i&ccedil;in birim &ccedil;ember tan&#x0131;m&#x0131;n&#x0131; kullan&#x0131;r&#x0131;z: $(\\cos\\theta, \\sin\\theta)$, pozitif x ekseninden saat y&ouml;n&uuml;n&uuml;n tersine $\\theta$ a&ccedil;&#x0131;s&#x0131; kadar d&ouml;n&uuml;lerek ula&#x015F;&#x0131;lan birim &ccedil;ember noktas&#x0131;d&#x0131;r.</p>

<div class="calc-cards">
<div class="calc-card"><div class="card-title">$\\theta = 0^\\circ$ &mdash; nokta $(1, 0)$</div><div class="card-body">$\\cos 0^\\circ = 1$, $\\sin 0^\\circ = 0$, $\\tan 0^\\circ = 0/1 = 0$. Her d&ouml;n&uuml;&#x015F;&uuml;n ba&#x015F;lang&#x0131;&ccedil; noktas&#x0131;.</div></div>
<div class="calc-card"><div class="card-title">$\\theta = 90^\\circ$ &mdash; nokta $(0, 1)$</div><div class="card-body">$\\cos 90^\\circ = 0$, $\\sin 90^\\circ = 1$, $\\tan 90^\\circ = 1/0$ &mdash; <strong>tan&#x0131;ms&#x0131;z</strong> (dikey do&#x011F;ru, sonsuz e&#x011F;im).</div></div>
<div class="calc-card"><div class="card-title">$\\theta = 180^\\circ$ &mdash; nokta $(-1, 0)$</div><div class="card-body">$\\cos 180^\\circ = -1$, $\\sin 180^\\circ = 0$, $\\tan 180^\\circ = 0/(-1) = 0$. &Ccedil;emberin 0&deg;&apos;ye g&ouml;re tam kar&#x015F;&#x0131; taraf&#x0131;.</div></div>
<div class="calc-card"><div class="card-title">$\\theta = 270^\\circ$ &mdash; nokta $(0, -1)$</div><div class="card-body">$\\cos 270^\\circ = 0$, $\\sin 270^\\circ = -1$, $\\tan 270^\\circ$ &mdash; yine <strong>tan&#x0131;ms&#x0131;z</strong> (dikey, sonsuz).</div></div>
<div class="calc-card"><div class="card-title">$\\theta = 360^\\circ$ &mdash; tekrar $(1, 0)$</div><div class="card-body">0&deg; ile ayn&#x0131; de&#x011F;erler. Tam bir tur sonra ba&#x015F;lang&#x0131;&ccedil; noktas&#x0131;na d&ouml;nersiniz: $\\cos 360^\\circ = 1$, $\\sin 360^\\circ = 0$.</div></div>
</div>

<div id="plot-circle-tr" class="plotly-graph" style="height:480px"></div>
<script>setTimeout(function(){
var th=[];var cx=[];var cy=[];for(var i=0;i<=360;i++){th.push(i);cx.push(Math.cos(i*Math.PI/180));cy.push(Math.sin(i*Math.PI/180));}
var circ={x:cx,y:cy,mode:"lines",line:{color:"rgba(59,130,246,0.45)",width:2},name:"birim &ccedil;ember",showlegend:false,hoverinfo:"skip"};
var pts={x:[1,Math.sqrt(3)/2,Math.sqrt(2)/2,1/2,0,-1/2,-Math.sqrt(2)/2,-Math.sqrt(3)/2,-1,-Math.sqrt(3)/2,-Math.sqrt(2)/2,-1/2,0,1/2,Math.sqrt(2)/2,Math.sqrt(3)/2],
y:[0,1/2,Math.sqrt(2)/2,Math.sqrt(3)/2,1,Math.sqrt(3)/2,Math.sqrt(2)/2,1/2,0,-1/2,-Math.sqrt(2)/2,-Math.sqrt(3)/2,-1,-Math.sqrt(3)/2,-Math.sqrt(2)/2,-1/2],
mode:"markers",marker:{size:9,color:"#3b82f6"},name:"&ouml;zel a&ccedil;&#x0131;lar",showlegend:false};
var lbl=[
{x:1.12,y:0,text:"0&deg; / 360&deg;<br>(1, 0)",showarrow:false,font:{color:"#cbd5e1",size:10}},
{x:0.95,y:0.62,text:"30&deg;<br>(&radic;3/2, 1/2)",showarrow:false,font:{color:"#cbd5e1",size:10}},
{x:0.82,y:0.82,text:"45&deg;",showarrow:false,font:{color:"#cbd5e1",size:10}},
{x:0.62,y:0.95,text:"60&deg;",showarrow:false,font:{color:"#cbd5e1",size:10}},
{x:0,y:1.12,text:"90&deg;<br>(0, 1)",showarrow:false,font:{color:"#cbd5e1",size:10}},
{x:-0.62,y:0.95,text:"120&deg;",showarrow:false,font:{color:"#cbd5e1",size:10}},
{x:-0.95,y:0.62,text:"150&deg;",showarrow:false,font:{color:"#cbd5e1",size:10}},
{x:-1.18,y:0,text:"180&deg;<br>(&minus;1, 0)",showarrow:false,font:{color:"#cbd5e1",size:10}},
{x:-0.95,y:-0.62,text:"210&deg;",showarrow:false,font:{color:"#cbd5e1",size:10}},
{x:-0.62,y:-0.95,text:"240&deg;",showarrow:false,font:{color:"#cbd5e1",size:10}},
{x:0,y:-1.12,text:"270&deg;<br>(0, &minus;1)",showarrow:false,font:{color:"#cbd5e1",size:10}},
{x:0.62,y:-0.95,text:"300&deg;",showarrow:false,font:{color:"#cbd5e1",size:10}},
{x:0.95,y:-0.62,text:"330&deg;",showarrow:false,font:{color:"#cbd5e1",size:10}}
];
var ax={x:[-1.3,1.3,null,0,0],y:[0,0,null,-1.3,1.3],mode:"lines",line:{color:"rgba(255,255,255,0.15)",width:1},showlegend:false,hoverinfo:"skip"};
var layout={paper_bgcolor:"rgba(0,0,0,0)",plot_bgcolor:"rgba(0,0,0,0)",font:{color:"#ebe6dc"},xaxis:{range:[-1.45,1.45],showgrid:false,zeroline:false,visible:false},yaxis:{range:[-1.45,1.45],showgrid:false,zeroline:false,visible:false,scaleanchor:"x"},annotations:lbl,margin:{t:20,r:20,b:20,l:20},showlegend:false};
Plotly.newPlot("plot-circle-tr",[circ,ax,pts],layout,{responsive:true,displayModeBar:false});
},250)</script>

<div class="calc-graph"><div class="graph-caption"><strong>Bu grafik ne g&ouml;steriyor:</strong> Birim &ccedil;ember &uuml;zerinde en &ccedil;ok ge&ccedil;en 16 &ouml;zel a&ccedil;&#x0131; noktas&#x0131; i&#x015F;aretlenmi&#x015F;tir. Her noktan&#x0131;n koordinat&#x0131; $(\\cos\\theta, \\sin\\theta)$&apos;dir. D&ouml;rt "s&#x0131;n&#x0131;r" a&ccedil;&#x0131;s&#x0131; (0&deg;, 90&deg;, 180&deg;, 270&deg;) eksenler &uuml;zerindedir; sekiz "$\\sqrt{3}/2, 1/2$" a&ccedil;&#x0131;s&#x0131; (30, 60, 120, 150, 210, 240, 300, 330) ve d&ouml;rt "$\\sqrt{2}/2$" a&ccedil;&#x0131;s&#x0131; (45, 135, 225, 315) d&ouml;rt b&ouml;lgede yer al&#x0131;r.</div></div>

<div class="calc-formula"><div class="formula-label">SINIR A&Ccedil;ILARI DAH&#x0130;L GEN&#x0130;&Scedil;LET&#x0130;LM&#x0130;&Scedil; TABLO</div><div class="formula-main">$$\\begin{array}{c|ccccccccc} \\theta & 0^\\circ & 30^\\circ & 45^\\circ & 60^\\circ & 90^\\circ & 180^\\circ & 270^\\circ & 360^\\circ \\\\ \\hline \\sin\\theta & 0 & \\frac{1}{2} & \\frac{\\sqrt{2}}{2} & \\frac{\\sqrt{3}}{2} & 1 & 0 & -1 & 0 \\\\[3pt] \\cos\\theta & 1 & \\frac{\\sqrt{3}}{2} & \\frac{\\sqrt{2}}{2} & \\frac{1}{2} & 0 & -1 & 0 & 1 \\\\[3pt] \\tan\\theta & 0 & \\frac{\\sqrt{3}}{3} & 1 & \\sqrt{3} & \\text{tan.} & 0 & \\text{tan.} & 0 \\end{array}$$</div></div>

<h2 class="l-title">6. Negatif A&ccedil;&#x0131;lar ve 360&deg; &Uuml;zeri A&ccedil;&#x0131;lar</h2>

<p class="l-text">400&deg;&apos;lik bir a&ccedil;&#x0131;, birim &ccedil;ember &uuml;zerinde bir tam tur (360&deg;) ve ard&#x0131;ndan ekstra 40&deg; d&ouml;nerek elde edilen noktay&#x0131; tan&#x0131;mlar. Var&#x0131;&#x015F; noktas&#x0131; 40&deg;&apos;ninkiyle ayn&#x0131;d&#x0131;r. Benzer &#x015F;ekilde &minus;30&deg;&apos;lik bir a&ccedil;&#x0131;, <em>saat y&ouml;n&uuml;nde</em> 30&deg; d&ouml;nmek demektir &mdash; var&#x0131;&#x015F; noktas&#x0131; 330&deg;&apos;ninkiyle ayn&#x0131;d&#x0131;r. Bu iki a&ccedil;&#x0131;ya <strong>e&#x015F; sonlu</strong> denir.</p>

<div class="calc-formula"><div class="formula-label">E&#x015E; SONLU A&Ccedil;I KURALI</div><div class="formula-main">$$\\theta \\;\\text{ ve }\\; \\theta + 360^\\circ k \\;\\;(k \\in \\mathbb{Z}) \\;\\;\\text{ayn&#x0131; trig de&#x011F;erlerini verir}$$</div><div class="formula-sub">360&deg;&apos;nin (ya da 2&pi; radyan&#x0131;n) tam katlar&#x0131;n&#x0131; serbest&ccedil;e ekleyip &ccedil;&#x0131;karabilirsiniz &mdash; sin, cos ve tan de&#x011F;i&#x015F;mez.</div></div>

<div class="calc-cards">
<div class="calc-card"><div class="card-title">360&deg;&apos;in &uuml;zerinde</div><div class="card-body">$\\sin 400^\\circ = \\sin(400^\\circ - 360^\\circ) = \\sin 40^\\circ$. $[0^\\circ, 360^\\circ)$ aral&#x0131;&#x011F;&#x0131;na inene kadar 360&deg; &ccedil;&#x0131;kar&#x0131;n.</div></div>
<div class="calc-card"><div class="card-title">720&deg;&apos;in &uuml;zerinde</div><div class="card-body">$\\cos 810^\\circ = \\cos(810^\\circ - 720^\\circ) = \\cos 90^\\circ = 0$. <strong>&#x0130;ki</strong> tam tur &ccedil;&#x0131;kar&#x0131;n.</div></div>
<div class="calc-card"><div class="card-title">Negatif</div><div class="card-body">$\\sin(-60^\\circ) = \\sin(-60^\\circ + 360^\\circ) = \\sin 300^\\circ = -\\sqrt{3}/2$. Pozitif olana kadar 360&deg; ekleyin.</div></div>
<div class="calc-card"><div class="card-title">&Ccedil;ok negatif</div><div class="card-body">$\\cos(-450^\\circ) = \\cos(-450^\\circ + 720^\\circ) = \\cos 270^\\circ = 0$. Gerekti&#x011F;i kadar 360&deg; ekleyin.</div></div>
</div>

<div class="l-note"><strong>Parite k&#x0131;sayolu.</strong> Sin&uuml;s ve tanjant <em>tek</em> fonksiyonlard&#x0131;r: $\\sin(-\\theta) = -\\sin\\theta$, $\\tan(-\\theta) = -\\tan\\theta$. Kos&uuml;s <em>&ccedil;ift</em>tir: $\\cos(-\\theta) = \\cos\\theta$. B&ouml;ylece $\\sin(-60^\\circ) = -\\sin 60^\\circ = -\\sqrt{3}/2$ &mdash; tek sat&#x0131;rda, 360&deg; eklemeye gerek yok. Bunlar&#x0131; Ders 4&apos;te birim &ccedil;ember resminden ispatlayaca&#x011F;&#x0131;z.</div>

<h2 class="l-title">7. Referans A&ccedil;&#x0131; Y&ouml;ntemi</h2>

<p class="l-text">Referans a&ccedil;&#x0131;, <em>herhangi</em> bir a&ccedil;&#x0131;n&#x0131;n trig de&#x011F;erini hesap makinesi olmadan bulmak i&ccedil;in en kullan&#x0131;&#x015F;l&#x0131; tek h&uuml;nerdir. Fikir &#x015F;u: herhangi bir b&ouml;lgedeki her a&ccedil;&#x0131;n&#x0131;n birinci b&ouml;lgede bir "dar a&ccedil;&#x0131; ikizi" vard&#x0131;r. Bu ikizi (<strong>referans a&ccedil;&#x0131;y&#x0131;</strong>) bulun, de&#x011F;erini &ouml;zel a&ccedil;&#x0131; tablosundan okuyun, sonra b&ouml;lgeye g&ouml;re i&#x015F;areti d&uuml;zeltin.</p>

<div class="calc-formula"><div class="formula-label">REFERANS A&Ccedil;I TANIMI</div><div class="formula-main">$$\\theta' = \\theta \\text{&apos;n&#x0131;n son kenar&#x0131; ile x ekseni aras&#x0131;ndaki dar a&ccedil;&#x0131;}$$</div><div class="formula-sub">Her zaman en yak&#x0131;n x eksenine g&ouml;re &ouml;l&ccedil;&uuml;l&uuml;r, asla y eksenine g&ouml;re de&#x011F;il. Sonu&ccedil; $[0^\\circ, 90^\\circ]$ aral&#x0131;&#x011F;&#x0131;ndad&#x0131;r.</div></div>

<div class="calc-cards">
<div class="calc-card"><div class="card-title">I. B&ouml;lge ($0^\\circ$ &ndash; $90^\\circ$)</div><div class="card-body">$\\theta' = \\theta$. A&ccedil;&#x0131;n&#x0131;n kendisi zaten dard&#x0131;r, &ccedil;&#x0131;karma yok.</div></div>
<div class="calc-card"><div class="card-title">II. B&ouml;lge ($90^\\circ$ &ndash; $180^\\circ$)</div><div class="card-body">$\\theta' = 180^\\circ - \\theta$. &Ouml;rnek: 150&deg;&apos;nin referans&#x0131; 30&deg;&apos;dir.</div></div>
<div class="calc-card"><div class="card-title">III. B&ouml;lge ($180^\\circ$ &ndash; $270^\\circ$)</div><div class="card-body">$\\theta' = \\theta - 180^\\circ$. &Ouml;rnek: 210&deg;&apos;nin referans&#x0131; 30&deg;&apos;dir.</div></div>
<div class="calc-card"><div class="card-title">IV. B&ouml;lge ($270^\\circ$ &ndash; $360^\\circ$)</div><div class="card-body">$\\theta' = 360^\\circ - \\theta$. &Ouml;rnek: 330&deg;&apos;nin referans&#x0131; 30&deg;&apos;dir.</div></div>
</div>

<p class="l-text"><strong>B&ouml;lgeye g&ouml;re i&#x015F;aret &mdash; "ASTC" kural&#x0131;.</strong> Birinci b&ouml;lgeden saat y&ouml;n&uuml;n&uuml;n tersine: <strong>A</strong>ll (Hepsi), <strong>S</strong>ine (Sin), <strong>T</strong>angent (Tan), <strong>C</strong>osine (Cos). Her b&ouml;lgede yaln&#x0131;zca yaz&#x0131;l&#x0131; fonksiyon (ve onun ters fonksiyonu) pozitiftir; di&#x011F;erleri negatiftir.</p>

<div class="calc-formula"><div class="formula-label">B&Ouml;LGEYE G&Ouml;RE SIN, COS, TAN &#x0130;&Scedil;ARETLER&#x0130;</div><div class="formula-main">$$\\begin{array}{c|ccc} \\text{B&ouml;lge} & \\sin\\theta & \\cos\\theta & \\tan\\theta \\\\ \\hline \\text{I} & + & + & + \\\\ \\text{II} & + & - & - \\\\ \\text{III} & - & - & + \\\\ \\text{IV} & - & + & - \\end{array}$$</div><div class="formula-sub">Hat&#x0131;rlat&#x0131;c&#x0131; <strong>ASTC</strong>: All Sine Tangent Cosine. T&uuml;rk&ccedil;e: "Hepsi &mdash; Sin&uuml;s &mdash; Tanjant &mdash; Kos&uuml;s".</div></div>

<div class="calc-steps">
<div class="calc-step"><div class="step-num">1</div><div class="step-content"><div class="step-title">$\\theta$&apos;y&#x0131; $[0^\\circ, 360^\\circ)$ aral&#x0131;&#x011F;&#x0131;na indirin</div><div class="step-detail">$\\theta$ bir tam tur i&ccedil;ine girene kadar 360&deg;&apos;nin katlar&#x0131;n&#x0131; ekleyip &ccedil;&#x0131;kar&#x0131;n.</div></div></div>
<div class="calc-step"><div class="step-num">2</div><div class="step-content"><div class="step-title">$\\theta$&apos;n&#x0131;n b&ouml;lgesini belirleyin</div><div class="step-detail">I (0-90), II (90-180), III (180-270), IV (270-360).</div></div></div>
<div class="calc-step"><div class="step-num">3</div><div class="step-content"><div class="step-title">Referans a&ccedil;&#x0131; $\\theta'$&apos;y&#x0131; hesaplay&#x0131;n</div><div class="step-detail">B&ouml;lgenin form&uuml;l&uuml;n&uuml; kullan&#x0131;n. Orijinal &ouml;zelse sonu&ccedil; da &ouml;zel a&ccedil;&#x0131; olacakt&#x0131;r.</div></div></div>
<div class="calc-step"><div class="step-num">4</div><div class="step-content"><div class="step-title">$\\theta'$&apos;de sin/cos/tan de&#x011F;erini okuyun</div><div class="step-detail">Birinci b&ouml;lge tablosundan.</div></div></div>
<div class="calc-step"><div class="step-num">5</div><div class="step-content"><div class="step-title">ASTC ile do&#x011F;ru i&#x015F;areti koyun</div><div class="step-detail">B&ouml;lge i&ccedil;in fonksiyon "izinli" grubundaysa pozitif, de&#x011F;ilse negatif.</div></div></div>
</div>

<div id="plot-quad-tr" class="plotly-graph" style="height:420px"></div>
<script>setTimeout(function(){
var th=[];var cx=[];var cy=[];for(var i=0;i<=360;i++){th.push(i);cx.push(Math.cos(i*Math.PI/180));cy.push(Math.sin(i*Math.PI/180));}
var circ={x:cx,y:cy,mode:"lines",line:{color:"rgba(59,130,246,0.45)",width:2},showlegend:false,hoverinfo:"skip"};
var ax={x:[-1.4,1.4,null,0,0],y:[0,0,null,-1.4,1.4],mode:"lines",line:{color:"rgba(255,255,255,0.20)",width:1},showlegend:false,hoverinfo:"skip"};
var lbl=[
{x:0.55,y:0.55,text:"<b>I</b><br>sin&nbsp;+&nbsp;&nbsp;cos&nbsp;+<br>tan&nbsp;+<br><b>Hepsi&nbsp;+</b>",showarrow:false,font:{color:"#86efac",size:11}},
{x:-0.55,y:0.55,text:"<b>II</b><br>sin&nbsp;+&nbsp;&nbsp;cos&nbsp;&minus;<br>tan&nbsp;&minus;<br><b>Sadece&nbsp;sin</b>",showarrow:false,font:{color:"#fcd34d",size:11}},
{x:-0.55,y:-0.55,text:"<b>III</b><br>sin&nbsp;&minus;&nbsp;&nbsp;cos&nbsp;&minus;<br>tan&nbsp;+<br><b>Sadece&nbsp;tan</b>",showarrow:false,font:{color:"#fb923c",size:11}},
{x:0.55,y:-0.55,text:"<b>IV</b><br>sin&nbsp;&minus;&nbsp;&nbsp;cos&nbsp;+<br>tan&nbsp;&minus;<br><b>Sadece&nbsp;cos</b>",showarrow:false,font:{color:"#67e8f9",size:11}}
];
var ray150={x:[0,Math.cos(150*Math.PI/180)],y:[0,Math.sin(150*Math.PI/180)],mode:"lines+markers",line:{color:"#f87171",width:2.5},marker:{size:[0,9],color:"#f87171"},name:"&theta;=150&deg;",showlegend:false};
var arc=[];for(var j=150;j<=180;j++){arc.push({x:0.35*Math.cos(j*Math.PI/180),y:0.35*Math.sin(j*Math.PI/180)});}
var arx=arc.map(function(p){return p.x;});var ary=arc.map(function(p){return p.y;});
var refarc={x:arx,y:ary,mode:"lines",line:{color:"#f87171",width:2,dash:"dot"},showlegend:false,hoverinfo:"skip"};
var refann=[
{x:Math.cos(150*Math.PI/180)-0.15,y:Math.sin(150*Math.PI/180)+0.08,text:"&theta;=150&deg;",showarrow:false,font:{color:"#f87171",size:11}},
{x:-0.50,y:0.10,text:"&theta;&#x2032;=30&deg;",showarrow:false,font:{color:"#f87171",size:10}}
];
var layout={paper_bgcolor:"rgba(0,0,0,0)",plot_bgcolor:"rgba(0,0,0,0)",font:{color:"#ebe6dc"},xaxis:{range:[-1.4,1.4],showgrid:false,zeroline:false,visible:false},yaxis:{range:[-1.4,1.4],showgrid:false,zeroline:false,visible:false,scaleanchor:"x"},annotations:lbl.concat(refann),margin:{t:20,r:20,b:20,l:20},showlegend:false};
Plotly.newPlot("plot-quad-tr",[circ,ax,ray150,refarc],layout,{responsive:true,displayModeBar:false});
},250)</script>

<div class="calc-graph"><div class="graph-caption"><strong>Bu grafik ne g&ouml;steriyor:</strong> Birim &ccedil;emberin d&ouml;rt b&ouml;lgesi ve ASTC i&#x015F;aretleri. K&#x0131;rm&#x0131;z&#x0131; &#x0131;&#x015F;&#x0131;n, $\\theta = 150^\\circ$ i&ccedil;in referans a&ccedil;&#x0131; fikrini g&ouml;sterir: a&ccedil;&#x0131;n&#x0131;n son kenar&#x0131; II. b&ouml;lgededir, x eksenine olan dar a&ccedil;&#x0131; (referans a&ccedil;&#x0131;) $180^\\circ - 150^\\circ = 30^\\circ$&apos;dir; sin&nbsp;150&deg; pozitiftir (II. b&ouml;lge), cos&nbsp;150&deg; ise negatiftir.</div></div>

<div class="calc-example"><div class="example-label">&Ouml;RNEK &mdash; sin&nbsp;150&deg;</div><div class="example-body"><strong>Ad&#x0131;m 1.</strong> 150&deg; zaten $[0^\\circ, 360^\\circ)$ aral&#x0131;&#x011F;&#x0131;ndad&#x0131;r.<br><br><strong>Ad&#x0131;m 2.</strong> 150&deg;, II. b&ouml;lgededir (90&deg; ile 180&deg; aras&#x0131;).<br><br><strong>Ad&#x0131;m 3.</strong> Referans a&ccedil;&#x0131; $= 180^\\circ - 150^\\circ = 30^\\circ$.<br><br><strong>Ad&#x0131;m 4.</strong> Tablodan $\\sin 30^\\circ = 1/2$.<br><br><strong>Ad&#x0131;m 5.</strong> &#x0130;&#x015F;aret: II. b&ouml;lgede sin&uuml;s <em>pozitiftir</em> (ASTC: S).<br><br><strong>Cevap:</strong> $\\sin 150^\\circ = +\\dfrac{1}{2}$.</div></div>

<h2 class="l-title">8. Klasik Al&#x0131;&#x015F;t&#x0131;rmalar</h2>

<p class="l-text">Sekiz klasik AYT tarz&#x0131; problem. Her birini referans a&ccedil;&#x0131; y&ouml;ntemiyle &ccedil;&ouml;zd&uuml;kten sonra &ccedil;&ouml;z&uuml;m&uuml; okuyun.</p>

<div class="calc-example"><div class="example-label">SORU 1 &mdash; cos&nbsp;240&deg;</div><div class="example-body"><strong>III. b&ouml;lge</strong> (180 &lt; 240 &lt; 270). Referans $= 240 - 180 = 60^\\circ$. Tablodan $\\cos 60^\\circ = 1/2$. III. b&ouml;lgede i&#x015F;aret: kos&uuml;s negatiftir (ASTC sadece T pozitif). Sonu&ccedil;: $\\cos 240^\\circ = -\\dfrac{1}{2}$.</div></div>

<div class="calc-example"><div class="example-label">SORU 2 &mdash; tan(&minus;60&deg;)</div><div class="example-body">&#x0130;ki yol. <em>Parite:</em> tanjant tek bir fonksiyondur, dolay&#x0131;s&#x0131;yla $\\tan(-60^\\circ) = -\\tan 60^\\circ = -\\sqrt{3}$. <em>Referans:</em> $-60^\\circ + 360^\\circ = 300^\\circ$, IV. b&ouml;lge, referans $360 - 300 = 60^\\circ$. $\\tan 60^\\circ = \\sqrt{3}$; IV. b&ouml;lgede i&#x015F;aret: tanjant negatiftir. Sonu&ccedil;: $\\tan(-60^\\circ) = -\\sqrt{3}$. &#x0130;ki y&ouml;ntem uyu&#x015F;ur.</div></div>

<div class="calc-example"><div class="example-label">SORU 3 &mdash; sin(7&pi;/6)</div><div class="example-body">Dereceye &ccedil;evirin: $7\\pi/6 = 7 \\cdot 180^\\circ / 6 = 210^\\circ$. III. b&ouml;lge. Referans $= 210 - 180 = 30^\\circ$. $\\sin 30^\\circ = 1/2$. III. b&ouml;lgede sin negatif. Cevap: $\\sin(7\\pi/6) = -\\dfrac{1}{2}$.</div></div>

<div class="calc-example"><div class="example-label">SORU 4 &mdash; cos(5&pi;/4)</div><div class="example-body">$5\\pi/4 = 225^\\circ$. III. b&ouml;lge. Referans $= 225 - 180 = 45^\\circ$. $\\cos 45^\\circ = \\sqrt{2}/2$. III. b&ouml;lgede cos negatif. Cevap: $\\cos(5\\pi/4) = -\\dfrac{\\sqrt{2}}{2}$.</div></div>

<div class="calc-example"><div class="example-label">SORU 5 &mdash; tan&nbsp;315&deg;</div><div class="example-body">IV. b&ouml;lge. Referans $= 360 - 315 = 45^\\circ$. $\\tan 45^\\circ = 1$. IV. b&ouml;lgede tan negatif. Cevap: $\\tan 315^\\circ = -1$.</div></div>

<div class="calc-example"><div class="example-label">SORU 6 &mdash; sin&nbsp;420&deg;</div><div class="example-body">$420 - 360 = 60^\\circ$ (e&#x015F; sonlu). I. b&ouml;lge. $\\sin 60^\\circ = \\sqrt{3}/2$. &#x0130;&#x015F;aret pozitif. Cevap: $\\sin 420^\\circ = \\dfrac{\\sqrt{3}}{2}$.</div></div>

<div class="calc-example"><div class="example-label">SORU 7 &mdash; cos(&minus;5&pi;/3)</div><div class="example-body">Kos&uuml;s &ccedil;ifttir: $\\cos(-5\\pi/3) = \\cos(5\\pi/3) = \\cos 300^\\circ$. IV. b&ouml;lge. Referans $= 360 - 300 = 60^\\circ$. $\\cos 60^\\circ = 1/2$. IV. b&ouml;lgede cos pozitif. Cevap: $\\cos(-5\\pi/3) = \\dfrac{1}{2}$.</div></div>

<div class="calc-example"><div class="example-label">SORU 8 &mdash; sin&nbsp;120&deg; &middot; cos&nbsp;330&deg; + tan&nbsp;225&deg;</div><div class="example-body">&Uuml;&ccedil; par&ccedil;a.<br>$\\sin 120^\\circ$: II, ref 60&deg;, sin pozitif $\\Rightarrow \\sqrt{3}/2$.<br>$\\cos 330^\\circ$: IV, ref 30&deg;, cos pozitif $\\Rightarrow \\sqrt{3}/2$.<br>$\\tan 225^\\circ$: III, ref 45&deg;, tan pozitif $\\Rightarrow 1$.<br><br>Birle&#x015F;tirin: $\\dfrac{\\sqrt{3}}{2} \\cdot \\dfrac{\\sqrt{3}}{2} + 1 = \\dfrac{3}{4} + 1 = \\dfrac{7}{4}$.</div></div>

<div class="l-note"><strong>&Ouml;zet.</strong> Tek bir derste, be&#x015F; &ouml;zel birinci b&ouml;lge a&ccedil;&#x0131;s&#x0131;na indirgenebilen <em>her</em> a&ccedil;&#x0131;n&#x0131;n &mdash; pozitif, negatif, b&uuml;y&uuml;k ya da k&uuml;&ccedil;&uuml;k &mdash; trig fonksiyonlar&#x0131;n&#x0131; hesaplamay&#x0131; &ouml;&#x011F;rendiniz. Bu tek beceri, YKS-AYT&apos;deki neredeyse her rutin trigonometri probleminin temelidir.</div>

<p class="l-text">Ders 4&apos;te bu temelleri $\\sin^2\\theta + \\cos^2\\theta = 1$ Pisagor &ouml;zde&#x015F;li&#x011F;ine ve toplam-fark form&uuml;llerine geni&#x015F;letiyoruz; bunlar birlikte &ouml;zel <em>olmayan</em> a&ccedil;&#x0131;lar&#x0131; &ouml;zel olanlar&#x0131;n bile&#x015F;imi olarak hesaplamam&#x0131;za olanak verir.</p>`

};
