window.MULTIMODAL_L3 = {
en: `<p class="l-text"><strong>CLIP can tell you whether a photo matches a caption. It cannot describe the photo, answer questions about it, follow up on its own answer, or write a poem about it.</strong> For that you need a Vision-Language Model — a system where the visual encoder feeds tokens into a real, autoregressive LLM that can chat. The 2023 leap was the realization that you do not need to retrain either the LLM or the visual encoder; you only need a small adapter that maps visual features into the LLM's token space. BLIP-2 (Salesforce, Jan 2023) shipped a Q-Former with 188M trainable parameters; LLaVA (Liu et al., Apr 2023) shipped a single linear layer. Both worked. The implications were enormous: anyone with a 7B LLM and a CLIP/SigLIP encoder could build a credible visual chatbot in a few thousand GPU-hours.</p>

<p class="l-text">In this lesson we walk the full LLaVA recipe — its architecture, the visual instruction-tuning dataset (LLaVA-Instruct-150K, generated by GPT-4 from COCO captions), the two-stage training (feature alignment, then visual instruction tuning), and the v1.5 / v1.6 (LLaVA-Next) improvements (higher resolution via AnyRes, MM-Vet bench gains). We also cover BLIP-2's Q-Former (a learned set of 32 query tokens that pull information from the frozen ViT), MiniGPT-4, InstructBLIP, Idefics2, Qwen2-VL, and InternVL 2 — the open-source frontier as of 2026. Closed frontier models (GPT-4V, Claude 3.5 Sonnet, Gemini 2.0) use the same recipe at much larger scale.</p>

<div class="lesson-outcomes" style="background:rgba(200,169,110,0.06);border-left:3px solid #c8a96e;padding:1rem 1.2rem;margin:1.5rem 0;border-radius:0 8px 8px 0">
<div style="font-size:0.78rem;font-weight:700;letter-spacing:0.08em;color:#c8a96e;margin-bottom:0.6rem">📍 WHAT YOU'LL LEARN</div>
<ul style="margin:0;padding-left:1.3rem;line-height:1.65;font-size:0.93rem;color:rgba(235,230,220,0.92)">
<li>Reconstruct the LLaVA architecture: ViT-L/14 → linear projection → LLaMA token stream</li>
<li>Understand BLIP-2's Q-Former: 32 learnable queries cross-attending to ViT features</li>
<li>Walk the two-stage training recipe (alignment → instruction tuning) and what each stage teaches</li>
<li>Compare LLaVA, BLIP-2, MiniGPT-4, InstructBLIP, Qwen2-VL on benchmarks (VQAv2, GQA, MMBench, MMMU)</li>
<li>Identify the visual-token bottleneck and how AnyRes / dynamic resolution fixes it</li>
<li>Build a toy VLM with sklearn that captures the architectural pattern</li>
</ul>
</div>

<div class="lesson-block" id="section-1">
<h2 class="lesson-title">1. The LLaVA Recipe — Three Components, One Pipeline</h2>
<p class="l-text">LLaVA's architecture fits on one slide. The image goes through a frozen CLIP ViT-L/14 (336px in v1.5). The 576 patch tokens (24×24 grid) get linearly projected into the LLM's hidden dim (4096 for LLaMA-2-7B). These 576 visual tokens are concatenated with the user's text tokens and fed to the LLM. The LLM autoregressively generates the answer. That is the whole thing.</p>

<div class="calc-cards">
<div class="calc-card"><div class="card-title">Visual encoder (frozen)</div><div class="card-body">CLIP ViT-L/14@336 in LLaVA-1.5. 24 transformer layers, output: 24×24 + 1 = 577 tokens × 1024 dim. The CLS token is dropped; the 576 patch tokens are kept.</div></div>
<div class="calc-card"><div class="card-title">Projector (trained)</div><div class="card-body">v1: single Linear(1024 → 4096). v1.5: 2-layer MLP with GELU. v1.6: same MLP but processes higher-resolution AnyRes patches. The only thing that adapts in stage 1.</div></div>
<div class="calc-card"><div class="card-title">LLM (frozen → fine-tuned in stage 2)</div><div class="card-body">Vicuna-7B / 13B, then LLaMA-3-8B in v1.6. Standard decoder transformer. Visual tokens occupy positions in the same sequence as text tokens.</div></div>
<div class="calc-card"><div class="card-title">Token layout</div><div class="card-body"><code>&lt;sys&gt; You are a helpful... &lt;img&gt;[576 visual tokens]&lt;/img&gt; &lt;user&gt; What is in this image? &lt;asst&gt;</code> The LLM has no idea those 576 are "visual" — to it they are just embeddings.</div></div>
</div>

<div class="calc-highlight"><strong>The crucial trick:</strong> visual tokens live in the LLM's regular token space. Self-attention inside the LLM is the cross-modal fusion mechanism — no separate cross-attention layers needed. This is why LLaVA's adapter is so small: the LLM already knows how to attend; you only need to teach the projector to "speak LLM".</div>
</div>

<div class="lesson-block" id="section-2">
<h2 class="lesson-title">2. Two-Stage Training</h2>
<p class="l-text">LLaVA trains in two stages. Stage 1 teaches the projector to align visual features with the LLM's embedding space. Stage 2 teaches the model to <em>follow instructions</em> about images.</p>

<div class="calc-cards">
<div class="calc-card"><div class="card-title">Stage 1 — Feature alignment</div><div class="card-body"><strong>Data:</strong> 558K (image, caption) pairs from LAION/CC/SBU. <strong>Frozen:</strong> ViT, LLM. <strong>Trained:</strong> projector only. <strong>Task:</strong> next-token prediction on the caption given the image. <strong>Cost:</strong> ~4 hours on 8×A100 for the 7B model.</div></div>
<div class="calc-card"><div class="card-title">Stage 2 — Visual instruction tuning</div><div class="card-body"><strong>Data:</strong> LLaVA-Instruct-150K (158K examples, generated by GPT-4 from COCO captions in three formats: detailed description, conversation, complex reasoning). <strong>Frozen:</strong> ViT. <strong>Trained:</strong> projector + LLM. <strong>Cost:</strong> ~8 hours on 8×A100.</div></div>
<div class="calc-card"><div class="card-title">Why two stages?</div><div class="card-body">Stage 1 alone produces a model that captions well but cannot chat. Stage 2 alone (no alignment) leaves the projector untrained — visual tokens look like noise to the LLM. Together: 73.7% on MMBench (LLaVA-1.5-13B), close to GPT-4V on many tasks.</div></div>
</div>

<div class="katex-block">$$L_{\\text{stage1}} = -\\sum_{t=1}^{T} \\log p_\\theta(c_t \\mid c_{&lt;t}, \\text{Proj}(\\text{ViT}(I)))$$</div>

<p class="l-text">Stage 1 is straightforward language modeling: maximize the probability of caption token c_t given previous caption tokens and the projected visual features. Only the projector's parameters θ are updated.</p>
</div>

<div class="lesson-block" id="section-3">
<h2 class="lesson-title">3. BLIP-2 and the Q-Former</h2>
<p class="l-text">Six months before LLaVA, BLIP-2 (Li et al., Salesforce, Jan 2023) solved the same problem with a different adapter — the <strong>Q-Former</strong>, a small transformer (188M params) with 32 learnable query tokens that cross-attend to the frozen ViT's output and self-attend among themselves.</p>

<div class="calc-cards">
<div class="calc-card"><div class="card-title">Architecture</div><div class="card-body">32 learnable query tokens × 768 dim. Each Q-Former layer: self-attn(queries) → cross-attn(queries → frozen ViT features) → FFN. 12 layers. Output: 32 tokens × 768 dim, then linear → LLM hidden dim.</div></div>
<div class="calc-card"><div class="card-title">Two-stage training (different from LLaVA)</div><div class="card-body">Stage 1: representation learning — Image-Text Contrastive (like CLIP) + Image-grounded Text Generation + Image-Text Matching. Stage 2: connect to frozen LLM (OPT or FlanT5), only Q-Former trained.</div></div>
<div class="calc-card"><div class="card-title">Why 32 tokens?</div><div class="card-body">Compresses the 257 ViT tokens into a fixed 32-token bottleneck. Pro: fits in any LLM context, faster inference. Con: discards spatial detail — bad for fine-grained VQA. LLaVA's 576 tokens preserve spatial layout.</div></div>
<div class="calc-card"><div class="card-title">When BLIP-2 wins</div><div class="card-body">When you must keep visual context tiny (mobile, edge, multi-image). When LLaVA wins: anything spatial, OCR-like, or counting. By 2024 most open-source projects switched to LLaVA-style projectors.</div></div>
</div>
</div>

<div class="lesson-block" id="section-4">
<h2 class="lesson-title">4. The Open-Source VLM Family Tree (2023–2026)</h2>
<p class="l-text">Once the recipe was public, derivatives flooded the field. A condensed family tree:</p>

<div class="calc-cards">
<div class="calc-card"><div class="card-title">MiniGPT-4 (Apr 2023)</div><div class="card-body">Zhu et al., KAUST. BLIP-2's Q-Former + Vicuna. ~5K curated instruction examples. Demonstrated visual chat is achievable on a single A100.</div></div>
<div class="calc-card"><div class="card-title">InstructBLIP (May 2023)</div><div class="card-body">Salesforce. BLIP-2 + 13 VQA/captioning datasets converted to instructions. Strong on academic benchmarks; less natural in open chat than LLaVA.</div></div>
<div class="calc-card"><div class="card-title">LLaVA-1.5 (Oct 2023)</div><div class="card-body">Adds ScienceQA, OCR-VQA, A-OKVQA to instruction data. Switches to MLP projector. SOTA on 11/12 benchmarks among 7-13B open VLMs at release.</div></div>
<div class="calc-card"><div class="card-title">LLaVA-Next / 1.6 (Jan 2024)</div><div class="card-body">AnyRes: split high-res image into 4 sub-tiles (672×672 → 4×336×336) plus a downsampled global view. Up to 2880 visual tokens. Big jumps on text-in-image tasks (TextVQA, ChartQA).</div></div>
<div class="calc-card"><div class="card-title">Idefics2 (Apr 2024)</div><div class="card-body">HuggingFace. SigLIP-So400m + Mistral-7B + Perceiver-style resampler. Strong document understanding. Apache-licensed.</div></div>
<div class="calc-card"><div class="card-title">Qwen2-VL (Aug 2024)</div><div class="card-body">Alibaba. Native dynamic resolution (no sub-tile splitting), M-RoPE for time/space, video support, agent-grade tool use. 72B variant matches GPT-4V on most benchmarks.</div></div>
<div class="calc-card"><div class="card-title">InternVL 2 / 2.5 (2024)</div><div class="card-body">Shanghai AI Lab. Up to 76B. InternViT-6B visual encoder (much larger than CLIP). Best open-source on MMMU as of late 2024.</div></div>
<div class="calc-card"><div class="card-title">Pixtral (Sep 2024)</div><div class="card-body">Mistral. SigLIP-So400m + Mistral Nemo 12B. Native variable resolution. Apache-2.0.</div></div>
</div>
</div>

<div class="lesson-block" id="section-5">
<h2 class="lesson-title">5. Hands-On — A Toy VLM in 40 Lines</h2>
<p class="l-text">A real VLM needs gigabytes and a GPU. The structural pattern — visual features projected into a "language" space, then jointly classified — fits in a notebook. We use sklearn's Pipeline as a stand-in for the LLM head.</p>

<div class="code-wrap"><div class="code-label"><span>PYTHON (DEMO — real LLaVA)</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest('.code-wrap').querySelector('code').textContent)">COPY</button></div><pre class="code-block"><code><span class="cm"># Real LLaVA inference with HuggingFace transformers — Pyodide-blocked</span>
<span class="kw">from</span> transformers <span class="kw">import</span> LlavaForConditionalGeneration, AutoProcessor
<span class="kw">import</span> torch
<span class="kw">from</span> PIL <span class="kw">import</span> Image

model_id = <span class="str">"llava-hf/llava-1.5-7b-hf"</span>
model = LlavaForConditionalGeneration.<span class="fn">from_pretrained</span>(
    model_id, torch_dtype=torch.float16, device_map=<span class="str">"cuda"</span>
)
processor = AutoProcessor.<span class="fn">from_pretrained</span>(model_id)

img = Image.<span class="fn">open</span>(<span class="str">"receipt.jpg"</span>)
prompt = <span class="str">"USER: &lt;image&gt;\\nWhat is the total on this receipt?\\nASSISTANT:"</span>
inputs = <span class="fn">processor</span>(prompt, img, return_tensors=<span class="str">"pt"</span>).<span class="fn">to</span>(<span class="str">"cuda"</span>)
out = model.<span class="fn">generate</span>(**inputs, max_new_tokens=<span class="num">200</span>)
<span class="fn">print</span>(processor.<span class="fn">decode</span>(out[<span class="num">0</span>], skip_special_tokens=<span class="kw">True</span>))
</code></pre></div>

<div class="pyodide-alt" style="margin:0.4rem 0 1.5rem;padding:1rem 1.1rem;background:rgba(120,180,200,0.06);border:1px solid rgba(120,180,200,0.22);border-radius:10px">
<div style="font-size:0.82rem;color:#7cc;margin-bottom:0.55rem;font-weight:600;letter-spacing:0.02em">🔁 Pyodide-equivalent (runs in the browser)</div>
<p class="l-text" style="font-size:0.88rem;margin:0.3rem 0 0.7rem 0;opacity:0.85">A toy VLM: visual features (image channel statistics) get linearly projected and concatenated with TF-IDF text features, then fed to a logistic regression "head" that picks an answer class. Same architecture topology as LLaVA, just toy-sized.</p>
<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest('.code-wrap').querySelector('code').textContent)">COPY</button></div><pre class="code-block"><code><span class="kw">import</span> numpy <span class="kw">as</span> np
<span class="kw">from</span> sklearn.feature_extraction.text <span class="kw">import</span> TfidfVectorizer
<span class="kw">from</span> sklearn.linear_model <span class="kw">import</span> LogisticRegression
<span class="kw">from</span> sklearn.pipeline <span class="kw">import</span> Pipeline

<span class="cm"># Synthetic VQA-like dataset: (image-stats, question) -> answer category</span>
np.random.<span class="fn">seed</span>(<span class="num">42</span>)
N = <span class="num">200</span>
<span class="cm"># Visual encoder: just (mean R, mean G, mean B) of a 16x16 image</span>
<span class="kw">def</span> <span class="fn">vis</span>(img):
    <span class="kw">return</span> img.<span class="fn">mean</span>(axis=(<span class="num">0</span>,<span class="num">1</span>))  <span class="cm"># (3,)</span>

<span class="cm"># Build dataset</span>
imgs = []
qs = []
ys = []
<span class="kw">for</span> _ <span class="kw">in</span> <span class="fn">range</span>(N):
    <span class="cm"># bright "outdoor" image</span>
    <span class="kw">if</span> np.random.<span class="fn">rand</span>() < <span class="num">0.5</span>:
        im = np.random.<span class="fn">rand</span>(<span class="num">16</span>,<span class="num">16</span>,<span class="num">3</span>) * np.<span class="fn">array</span>([<span class="num">0.9</span>, <span class="num">0.9</span>, <span class="num">1.0</span>])
        q  = np.random.<span class="fn">choice</span>([<span class="str">"What is the weather?"</span>, <span class="str">"Is this outdoor?"</span>, <span class="str">"How bright is it?"</span>])
        y  = <span class="str">"sunny"</span>
    <span class="kw">else</span>:
        im = np.random.<span class="fn">rand</span>(<span class="num">16</span>,<span class="num">16</span>,<span class="num">3</span>) * np.<span class="fn">array</span>([<span class="num">0.3</span>, <span class="num">0.3</span>, <span class="num">0.4</span>])
        q  = np.random.<span class="fn">choice</span>([<span class="str">"What is the weather?"</span>, <span class="str">"Is this outdoor?"</span>, <span class="str">"How bright is it?"</span>])
        y  = <span class="str">"dark"</span>
    imgs.<span class="fn">append</span>(im); qs.<span class="fn">append</span>(q); ys.<span class="fn">append</span>(y)

<span class="cm"># "Projector": visual features fixed-mapped, then concatenated with TF-IDF text</span>
proj = np.random.<span class="fn">RandomState</span>(<span class="num">0</span>).<span class="fn">randn</span>(<span class="num">3</span>, <span class="num">8</span>)   <span class="cm"># 3 -> 8-dim "visual tokens"</span>
V = np.<span class="fn">stack</span>([<span class="fn">vis</span>(i) <span class="kw">for</span> i <span class="kw">in</span> imgs]) @ proj   <span class="cm"># (N, 8)</span>
vec = <span class="fn">TfidfVectorizer</span>().<span class="fn">fit</span>(qs)
T = vec.<span class="fn">transform</span>(qs).<span class="fn">toarray</span>()               <span class="cm"># (N, vocab)</span>

X = np.<span class="fn">hstack</span>([V, T])                         <span class="cm"># the joint multimodal embedding</span>
clf = <span class="fn">LogisticRegression</span>(max_iter=<span class="num">500</span>).<span class="fn">fit</span>(X, ys)

<span class="cm"># Evaluate on a fresh batch</span>
test_imgs = [np.random.<span class="fn">rand</span>(<span class="num">16</span>,<span class="num">16</span>,<span class="num">3</span>) * <span class="num">0.9</span>, np.random.<span class="fn">rand</span>(<span class="num">16</span>,<span class="num">16</span>,<span class="num">3</span>) * <span class="num">0.3</span>]
test_qs   = [<span class="str">"What is the weather?"</span>, <span class="str">"Is this outdoor?"</span>]
Vt = np.<span class="fn">stack</span>([<span class="fn">vis</span>(i) <span class="kw">for</span> i <span class="kw">in</span> test_imgs]) @ proj
Tt = vec.<span class="fn">transform</span>(test_qs).<span class="fn">toarray</span>()
Xt = np.<span class="fn">hstack</span>([Vt, Tt])
<span class="fn">print</span>(<span class="str">"Predictions:"</span>, clf.<span class="fn">predict</span>(Xt))
<span class="fn">print</span>(<span class="str">"Train acc:  "</span>, clf.<span class="fn">score</span>(X, ys))
</code></pre></div>
</div>

<p class="l-text">Three things this toy gets right structurally: (1) visual features are projected into the same numeric space as text features, (2) the joint vector is what the head consumes, (3) at inference time you only need to project the new image and re-vectorize the new question. Replace LogisticRegression with a 7B autoregressive LLM and you have LLaVA.</p>
</div>

<div class="lesson-block" id="section-6">
<h2 class="lesson-title">6. The Visual-Token Bottleneck and AnyRes</h2>
<p class="l-text">CLIP ViT-L/14@336 produces 576 patch tokens. For a 1080×1920 screenshot that gets resized to 336×336, 95% of the pixel information is gone before the LLM ever sees it. This is a deal-breaker for receipts, charts, dense documents, and dashboards.</p>

<div class="calc-cards">
<div class="calc-card"><div class="card-title">LLaVA-Next AnyRes</div><div class="card-body">Pick a target aspect (e.g., 4 tiles arranged 2×2). Resize the image so each tile is 336×336. Encode each tile separately with the frozen ViT (4× cost). Concatenate the 4×576 = 2304 tokens with a 576-token global low-res view → 2880 tokens total.</div></div>
<div class="calc-card"><div class="card-title">Qwen2-VL native dynamic resolution</div><div class="card-body">Encoder runs at the image's actual aspect (up to a max). M-RoPE encodes 2D position natively. No tile splitting, no information loss at boundaries. Best-in-class on document/chart benchmarks.</div></div>
<div class="calc-card"><div class="card-title">Idefics2 / Pixtral Perceiver-resampler</div><div class="card-body">Variable image size on input, fixed 64 or 256 output tokens via Perceiver cross-attention. Compromise: small token budget but flexible input.</div></div>
<div class="calc-card"><div class="card-title">Trade-off in 2026</div><div class="card-body">More tokens = better fine-detail, slower inference. Frontier open-source uses 1K–3K visual tokens for general use, scales to 16K+ for document tasks. Closed models (GPT-4V, Gemini) likely use similar tactics.</div></div>
</div>
</div>

<div class="lesson-block" id="section-7">
<h2 class="lesson-title">7. Benchmarks and What They Actually Measure</h2>
<p class="l-text">VLM benchmarks fragmented in 2023–2024. Knowing which one to trust per task family:</p>

<div class="calc-cards">
<div class="calc-card"><div class="card-title">VQAv2 (2017)</div><div class="card-body">Open-ended VQA over COCO. ~80% is the strong-VLM range. Saturated; not a good discriminator anymore.</div></div>
<div class="calc-card"><div class="card-title">GQA (2019)</div><div class="card-body">Compositional reasoning over scene graphs. Stricter than VQAv2. LLaVA-1.5-13B: 63.3%. GPT-4V: ~75%.</div></div>
<div class="calc-card"><div class="card-title">MMBench / MMBench-CN (2023)</div><div class="card-body">3K multiple-choice across 20 ability dimensions, English + Chinese. Robust to prompt format. GPT-4V: 75.1%. Qwen2-VL-72B: 86.5%. Open SOTA.</div></div>
<div class="calc-card"><div class="card-title">MMMU (2024)</div><div class="card-body">College-level multimodal (math, physics, art, medicine). 11.5K questions. Brutal benchmark. GPT-4o: 69.1%. Best open ~63% (InternVL 2.5).</div></div>
<div class="calc-card"><div class="card-title">TextVQA / ChartQA / DocVQA</div><div class="card-body">Text in images, charts, documents. Resolution-sensitive. AnyRes / dynamic resolution swings these by 10+ points.</div></div>
<div class="calc-card"><div class="card-title">MM-Vet</div><div class="card-body">Open-ended generation graded by GPT-4. Captures conversational quality, not just multiple choice. Used in LLaVA-Next paper.</div></div>
</div>

<div class="calc-highlight"><strong>Choosing a benchmark:</strong> for general capability, MMBench. For research-grade hard reasoning, MMMU. For document/OCR, DocVQA + ChartQA. For open-ended chat quality, MM-Vet. Never report on only one — single-bench gaming is rampant.</div>
</div>

<div class="lesson-block" id="section-frontier">
<h2 class="lesson-title">2024–2026 Frontier Models</h2>
<p class="l-text"><strong>The LLaVA recipe scaled — and then 2024 happened.</strong> The cards below are the modern descendants of the LLaVA / BLIP-2 family that you will actually deploy or fine-tune in production. Three patterns dominate: closed multimodal LLMs that are end-to-end (GPT-4o, Claude 3.7, Gemini 2.0), open-weight VLMs that fine-tune cleanly (Llama 3.2, Qwen2-VL), and high-fidelity open competitors (InternVL 2.5).</p>
<div class="calc-cards">
<div class="calc-card"><div class="card-title">GPT-4o (OpenAI, May 2024)</div><div class="card-body">Native multimodal text + vision + audio in one model. 50% cheaper than GPT-4 Turbo, end-to-end audio (no separate Whisper / TTS). Default closed baseline for VQA and chart reading.</div></div>
<div class="calc-card"><div class="card-title">Claude 3.5 / 3.7 Sonnet (Anthropic, Jun 2024 / Feb 2025)</div><div class="card-body">Strong vision + extended thinking + computer use. Claude 3.7 can take a screenshot and drive a UI — clicks, types, scrolls. Best for document QA, screenshot debugging, and agentic UI tasks.</div></div>
<div class="calc-card"><div class="card-title">Gemini 2.0 Flash (Google, Dec 2024)</div><div class="card-body">Native multimodal <em>output</em> — generates interleaved text + image + audio. 1M+ token context, hour-long video, streaming Live API for real-time assistants.</div></div>
<div class="calc-card"><div class="card-title">Llama 3.2 Vision 11B / 90B (Meta, Sep 2024)</div><div class="card-body">First Meta open-weight VLMs. Cross-attention adapter on frozen Llama 3.1. The 11B runs on a single A100; 90B rivals GPT-4V on charts. Fine-tunable — the practical pick for private deployment.</div></div>
<div class="calc-card"><div class="card-title">Qwen2-VL 72B (Alibaba, Aug 2024)</div><div class="card-body">Native dynamic resolution (no AnyRes hack), 20-minute video, SOTA open-source on MMMU and DocVQA. First open VLM truly competing with frontier closed models.</div></div>
<div class="calc-card"><div class="card-title">InternVL 2.5 (OpenGVLab, Dec 2024)</div><div class="card-body">78B open VLM, ~70% on MMMU (near GPT-4V). Uses a 6B InternViT-6B encoder and progressive training. Proof that open models are ~6 months — not 2 years — behind closed frontier.</div></div>
</div>
<div class="calc-highlight"><strong>Architectural shift since LLaVA-1:</strong> the trend is bigger visual encoders (InternViT-6B), native dynamic resolution instead of AnyRes patching (Qwen2-VL), and explicit reasoning budgets at inference (Claude 3.7 extended thinking). The Q-Former bottleneck has been largely abandoned — full visual-token sequences with smart tiling win on chart/document tasks.</div>
</div>

<div class="lesson-block" id="section-8">
<h2 class="lesson-title">8. Recap and What's Next</h2>
<p class="l-text">A modern Vision-Language Model is a frozen visual encoder + a small adapter + a strong LLM. LLaVA's recipe (linear/MLP projector, two-stage training on captions then GPT-4-generated instructions) and BLIP-2's Q-Former alternative covered nearly all open-source progress 2023–2024. By 2026, native dynamic resolution (Qwen2-VL) and bigger visual encoders (InternVL) are the main axes of improvement.</p>

<div class="calc-highlight"><strong>Key takeaways:</strong>
<ul style="margin:0.5rem 0 0;padding-left:1.2rem;line-height:1.65">
<li>LLaVA = frozen ViT + linear/MLP projector + LLM. Visual tokens live in the LLM's regular sequence.</li>
<li>Two-stage training: alignment on captions, then visual instruction tuning on GPT-4-generated 150K examples.</li>
<li>BLIP-2 uses a 32-token Q-Former bottleneck; LLaVA uses 576 patch tokens (2880 with AnyRes).</li>
<li>Open-source 2024 frontier: Qwen2-VL, InternVL 2.5, Pixtral. Closed: GPT-4o, Gemini 2.0, Claude 3.5.</li>
<li>The visual-token bottleneck matters: AnyRes / dynamic resolution unlock document and chart tasks.</li>
<li>Benchmark portfolio: MMBench (general), MMMU (hard reasoning), DocVQA/ChartQA (text-in-image), MM-Vet (chat quality).</li>
</ul>
</div>

<p class="l-text">In <strong>multimodal-L4</strong> we shift modalities — from vision to audio. We will see how Whisper handles 99 languages of speech, how SeamlessM4T extends end-to-end translation across speech and text, and how Qwen-Audio and AudioGPT plug audio into the same LLM-with-adapter recipe we just learned.</p>
</div>`,
tr: `<p class="l-text"><strong>CLIP size bir fotoğrafın bir açıklamayla eşleşip eşleşmediğini söyleyebilir. Fotoğrafı tanımlayamaz, hakkında soruları cevaplayamaz, kendi cevabı üzerine devam edemez veya hakkında şiir yazamaz.</strong> Bunun için bir Görü-Dil Modeline ihtiyacınız var — görsel kodlayıcının token'ları gerçek, özyineli (autoregressive) bir LLM'ye besleyip onun sohbet edebildiği bir sistem. 2023 sıçraması, ne LLM'yi ne de görsel kodlayıcıyı yeniden eğitmenize gerek olmadığının fark edilmesiydi; sadece görsel öznitelikleri LLM'nin token uzayına eşleştiren küçük bir adaptör gerekir. BLIP-2 (Salesforce, Oca 2023) 188M eğitilebilir parametreyle bir Q-Former gönderdi; LLaVA (Liu vd., Nis 2023) tek bir doğrusal katman gönderdi. İkisi de çalıştı. Etkileri devasaydı: 7B'lik bir LLM ve bir CLIP/SigLIP kodlayıcısı olan herkes birkaç bin GPU-saatinde inandırıcı bir görsel chatbot oluşturabilir.</p>

<p class="l-text">Bu derste tam LLaVA tarifini yürüyoruz — mimarisi, görsel talimat-ayarlama veri kümesi (LLaVA-Instruct-150K, COCO açıklamalarından GPT-4 tarafından üretildi), iki aşamalı eğitim (öznitelik hizalama, ardından görsel talimat ayarlama) ve v1.5 / v1.6 (LLaVA-Next) iyileştirmeleri (AnyRes ile yüksek çözünürlük, MM-Vet bench kazançları). Ayrıca BLIP-2'nin Q-Former'ını (donmuş ViT'ten bilgi çeken 32 öğrenilmiş sorgu token'ından oluşan bir küme), MiniGPT-4, InstructBLIP, Idefics2, Qwen2-VL ve InternVL 2'yi — 2026 itibariyle açık kaynak öncüsünü — işliyoruz. Kapalı öncü modeller (GPT-4V, Claude 3.5 Sonnet, Gemini 2.0) aynı tarifi çok daha büyük ölçekte kullanır.</p>

<div class="lesson-outcomes" style="background:rgba(200,169,110,0.06);border-left:3px solid #c8a96e;padding:1rem 1.2rem;margin:1.5rem 0;border-radius:0 8px 8px 0">
<div style="font-size:0.78rem;font-weight:700;letter-spacing:0.08em;color:#c8a96e;margin-bottom:0.6rem">📍 BU DERSTE ÖĞRENECEKSİN</div>
<ul style="margin:0;padding-left:1.3rem;line-height:1.65;font-size:0.93rem;color:rgba(235,230,220,0.92)">
<li>LLaVA mimarisini yeniden inşa etmek: ViT-L/14 → doğrusal projeksiyon → LLaMA token akışı</li>
<li>BLIP-2'nin Q-Former'ını anlamak: ViT özniteliklerine çapraz dikkat eden 32 öğrenilebilir sorgu</li>
<li>İki aşamalı eğitim tarifini yürümek (hizalama → talimat ayarlama) ve her aşamanın ne öğrettiği</li>
<li>LLaVA, BLIP-2, MiniGPT-4, InstructBLIP, Qwen2-VL'yi benchmarklarda karşılaştırmak (VQAv2, GQA, MMBench, MMMU)</li>
<li>Görsel-token darboğazını ve AnyRes / dinamik çözünürlüğün bunu nasıl düzelttiğini tanımak</li>
<li>Mimari deseni yakalayan oyuncak bir VLM'yi sklearn ile inşa etmek</li>
</ul>
</div>

<div class="lesson-block" id="section-1">
<h2 class="lesson-title">1. LLaVA Tarifi — Üç Bileşen, Tek Hat</h2>
<p class="l-text">LLaVA'nın mimarisi tek slayda sığar. Görüntü donmuş bir CLIP ViT-L/14'ten geçer (v1.5'te 336px). 576 yama token (24×24 ızgara) LLM'nin gizli boyutuna doğrusal olarak projekte edilir (LLaMA-2-7B için 4096). Bu 576 görsel token kullanıcının metin token'larıyla birleştirilir ve LLM'ye beslenir. LLM cevabı özyineli olarak üretir. Tüm hikaye bu.</p>

<div class="calc-cards">
<div class="calc-card"><div class="card-title">Görsel kodlayıcı (donmuş)</div><div class="card-body">LLaVA-1.5'te CLIP ViT-L/14@336. 24 transformer katmanı, çıktı: 24×24 + 1 = 577 token × 1024 boyut. CLS token atılır; 576 yama token tutulur.</div></div>
<div class="calc-card"><div class="card-title">Projektör (eğitilir)</div><div class="card-body">v1: tek Linear(1024 → 4096). v1.5: GELU ile 2-katmanlı MLP. v1.6: aynı MLP ama yüksek çözünürlüklü AnyRes yamalarını işler. Aşama 1'de uyum sağlayan tek şey.</div></div>
<div class="calc-card"><div class="card-title">LLM (donmuş → aşama 2'de ince ayarlanır)</div><div class="card-body">Vicuna-7B / 13B, sonra v1.6'da LLaMA-3-8B. Standart kodlayıcı (decoder) transformer. Görsel token'lar metin token'larıyla aynı dizide pozisyon işgal eder.</div></div>
<div class="calc-card"><div class="card-title">Token düzeni</div><div class="card-body"><code>&lt;sys&gt; You are a helpful... &lt;img&gt;[576 görsel token]&lt;/img&gt; &lt;user&gt; What is in this image? &lt;asst&gt;</code> LLM'nin bu 576'nın "görsel" olduğuna dair hiçbir fikri yoktur — onun için sadece gömmelerdir.</div></div>
</div>

<div class="calc-highlight"><strong>Kritik numara:</strong> görsel token'lar LLM'nin normal token uzayında yaşar. LLM içindeki öz-dikkat çapraz-modal füzyon mekanizmasıdır — ayrı çapraz-dikkat katmanlarına gerek yoktur. LLaVA'nın adaptörü bu yüzden bu kadar küçüktür: LLM zaten dikkat etmeyi biliyor; sadece projektöre "LLM konuşmayı" öğretmeniz gerekiyor.</div>
</div>

<div class="lesson-block" id="section-2">
<h2 class="lesson-title">2. İki Aşamalı Eğitim</h2>
<p class="l-text">LLaVA iki aşamada eğitilir. Aşama 1 projektöre görsel öznitelikleri LLM'nin gömme uzayıyla hizalamayı öğretir. Aşama 2 modele görüntüler hakkında <em>talimat takip etmeyi</em> öğretir.</p>

<div class="calc-cards">
<div class="calc-card"><div class="card-title">Aşama 1 — Öznitelik hizalama</div><div class="card-body"><strong>Veri:</strong> LAION/CC/SBU'dan 558K (görüntü, açıklama) çifti. <strong>Donmuş:</strong> ViT, LLM. <strong>Eğitilir:</strong> yalnız projektör. <strong>Görev:</strong> görüntü verildiğinde açıklamada sonraki-token tahmini. <strong>Maliyet:</strong> 7B model için 8×A100'de ~4 saat.</div></div>
<div class="calc-card"><div class="card-title">Aşama 2 — Görsel talimat ayarlama</div><div class="card-body"><strong>Veri:</strong> LLaVA-Instruct-150K (158K örnek, COCO açıklamalarından GPT-4 tarafından üç formatta üretildi: detaylı tanım, sohbet, karmaşık akıl yürütme). <strong>Donmuş:</strong> ViT. <strong>Eğitilir:</strong> projektör + LLM. <strong>Maliyet:</strong> 8×A100'de ~8 saat.</div></div>
<div class="calc-card"><div class="card-title">Neden iki aşama?</div><div class="card-body">Yalnız Aşama 1, iyi açıklama yapan ama sohbet edemeyen bir model üretir. Yalnız Aşama 2 (hizalama yok) projektörü eğitilmemiş bırakır — görsel token'lar LLM'ye gürültü gibi görünür. Birlikte: MMBench'te %73.7 (LLaVA-1.5-13B), birçok görevde GPT-4V'ye yakın.</div></div>
</div>

<div class="katex-block">$$L_{\\text{stage1}} = -\\sum_{t=1}^{T} \\log p_\\theta(c_t \\mid c_{&lt;t}, \\text{Proj}(\\text{ViT}(I)))$$</div>

<p class="l-text">Aşama 1 doğrudan dil modelleme: önceki açıklama token'ları ve projekte edilmiş görsel öznitelikler verildiğinde açıklama token c_t'nin olasılığını maksimize et. Yalnızca projektörün parametreleri θ güncellenir.</p>
</div>

<div class="lesson-block" id="section-3">
<h2 class="lesson-title">3. BLIP-2 ve Q-Former</h2>
<p class="l-text">LLaVA'dan altı ay önce, BLIP-2 (Li vd., Salesforce, Oca 2023) aynı problemi farklı bir adaptörle — donmuş ViT'in çıktısına çapraz-dikkat eden ve kendi aralarında öz-dikkat eden 32 öğrenilebilir sorgu token'ına sahip küçük bir transformer (188M parametre) olan <strong>Q-Former</strong> ile çözdü.</p>

<div class="calc-cards">
<div class="calc-card"><div class="card-title">Mimari</div><div class="card-body">32 öğrenilebilir sorgu token × 768 boyut. Her Q-Former katmanı: self-attn(sorgular) → cross-attn(sorgular → donmuş ViT öznitelikleri) → FFN. 12 katman. Çıktı: 32 token × 768 boyut, sonra doğrusal → LLM gizli boyutu.</div></div>
<div class="calc-card"><div class="card-title">İki aşamalı eğitim (LLaVA'dan farklı)</div><div class="card-body">Aşama 1: temsil öğrenme — Görüntü-Metin Karşıt (CLIP gibi) + Görüntü-yerleştirilmiş Metin Üretimi + Görüntü-Metin Eşleştirme. Aşama 2: donmuş LLM'ye bağlan (OPT veya FlanT5), yalnızca Q-Former eğitilir.</div></div>
<div class="calc-card"><div class="card-title">Neden 32 token?</div><div class="card-body">257 ViT token'ını sabit 32-token darboğaza sıkıştırır. Avantaj: herhangi bir LLM bağlamına sığar, daha hızlı çıkarım. Dezavantaj: uzamsal detayı atar — ince taneli VQA için kötü. LLaVA'nın 576 token'ı uzamsal düzeni korur.</div></div>
<div class="calc-card"><div class="card-title">BLIP-2 ne zaman kazanır</div><div class="card-body">Görsel bağlamı küçük tutmak zorunda olduğunuzda (mobil, edge, çoklu görüntü). LLaVA ne zaman kazanır: uzamsal, OCR-benzeri veya sayma her şey. 2024'e kadar çoğu açık kaynak proje LLaVA-tarzı projektörlere geçti.</div></div>
</div>
</div>

<div class="lesson-block" id="section-4">
<h2 class="lesson-title">4. Açık Kaynak VLM Aile Ağacı (2023–2026)</h2>
<p class="l-text">Tarif kamuya açıldığında türevler alanı kapladı. Yoğunlaştırılmış aile ağacı:</p>

<div class="calc-cards">
<div class="calc-card"><div class="card-title">MiniGPT-4 (Nis 2023)</div><div class="card-body">Zhu vd., KAUST. BLIP-2'nin Q-Former'ı + Vicuna. ~5K küratörlü talimat örneği. Görsel sohbetin tek bir A100'de elde edilebilir olduğunu gösterdi.</div></div>
<div class="calc-card"><div class="card-title">InstructBLIP (May 2023)</div><div class="card-body">Salesforce. BLIP-2 + talimatlara dönüştürülmüş 13 VQA/açıklama veri kümesi. Akademik benchmarklarda güçlü; LLaVA'dan açık sohbette daha az doğal.</div></div>
<div class="calc-card"><div class="card-title">LLaVA-1.5 (Eki 2023)</div><div class="card-body">Talimat verisine ScienceQA, OCR-VQA, A-OKVQA ekler. MLP projektöre geçer. Yayında 7-13B açık VLM'ler arasında 11/12 benchmarkta SOTA.</div></div>
<div class="calc-card"><div class="card-title">LLaVA-Next / 1.6 (Oca 2024)</div><div class="card-body">AnyRes: yüksek çözünürlüklü görüntüyü 4 alt-karoya böl (672×672 → 4×336×336) artı altörnekleme global görünüm. 2880 görsel tokene kadar. Görüntüde-metin görevlerinde büyük sıçramalar (TextVQA, ChartQA).</div></div>
<div class="calc-card"><div class="card-title">Idefics2 (Nis 2024)</div><div class="card-body">HuggingFace. SigLIP-So400m + Mistral-7B + Perceiver-tarzı yeniden örnekleyici. Güçlü belge anlama. Apache lisanslı.</div></div>
<div class="calc-card"><div class="card-title">Qwen2-VL (Ağu 2024)</div><div class="card-body">Alibaba. Yerel dinamik çözünürlük (alt-karo bölme yok), zaman/uzay için M-RoPE, video desteği, ajan-seviye araç kullanımı. 72B varyantı çoğu benchmarkta GPT-4V ile eşleşir.</div></div>
<div class="calc-card"><div class="card-title">InternVL 2 / 2.5 (2024)</div><div class="card-body">Şanghay AI Lab. 76B'ye kadar. InternViT-6B görsel kodlayıcı (CLIP'ten çok daha büyük). 2024 sonu itibariyle MMMU'da en iyi açık kaynak.</div></div>
<div class="calc-card"><div class="card-title">Pixtral (Eyl 2024)</div><div class="card-body">Mistral. SigLIP-So400m + Mistral Nemo 12B. Yerel değişken çözünürlük. Apache-2.0.</div></div>
</div>
</div>

<div class="lesson-block" id="section-5">
<h2 class="lesson-title">5. Uygulama — 40 Satırlık Oyuncak VLM</h2>
<p class="l-text">Gerçek bir VLM gigabaytlar ve bir GPU gerektirir. Yapısal desen — bir "dil" uzayına projekte edilen görsel öznitelikler, ardından ortak sınıflandırılan — bir notebook'a sığar. LLM başı yerine sklearn'in Pipeline'ını kullanıyoruz.</p>

<div class="code-wrap"><div class="code-label"><span>PYTHON (DEMO — gerçek LLaVA)</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest('.code-wrap').querySelector('code').textContent)">COPY</button></div><pre class="code-block"><code><span class="cm"># HuggingFace transformers ile gercek LLaVA cikarimi — Pyodide tarafindan engellendi</span>
<span class="kw">from</span> transformers <span class="kw">import</span> LlavaForConditionalGeneration, AutoProcessor
<span class="kw">import</span> torch
<span class="kw">from</span> PIL <span class="kw">import</span> Image

model_id = <span class="str">"llava-hf/llava-1.5-7b-hf"</span>
model = LlavaForConditionalGeneration.<span class="fn">from_pretrained</span>(
    model_id, torch_dtype=torch.float16, device_map=<span class="str">"cuda"</span>
)
processor = AutoProcessor.<span class="fn">from_pretrained</span>(model_id)

img = Image.<span class="fn">open</span>(<span class="str">"receipt.jpg"</span>)
prompt = <span class="str">"USER: &lt;image&gt;\\nWhat is the total on this receipt?\\nASSISTANT:"</span>
inputs = <span class="fn">processor</span>(prompt, img, return_tensors=<span class="str">"pt"</span>).<span class="fn">to</span>(<span class="str">"cuda"</span>)
out = model.<span class="fn">generate</span>(**inputs, max_new_tokens=<span class="num">200</span>)
<span class="fn">print</span>(processor.<span class="fn">decode</span>(out[<span class="num">0</span>], skip_special_tokens=<span class="kw">True</span>))
</code></pre></div>

<div class="pyodide-alt" style="margin:0.4rem 0 1.5rem;padding:1rem 1.1rem;background:rgba(120,180,200,0.06);border:1px solid rgba(120,180,200,0.22);border-radius:10px">
<div style="font-size:0.82rem;color:#7cc;margin-bottom:0.55rem;font-weight:600;letter-spacing:0.02em">🔁 Pyodide-eşdeğeri (tarayıcıda çalışır)</div>
<p class="l-text" style="font-size:0.88rem;margin:0.3rem 0 0.7rem 0;opacity:0.85">Oyuncak bir VLM: görsel öznitelikler (görüntü kanal istatistikleri) doğrusal projekte edilip TF-IDF metin öznitelikleriyle birleştirilir, ardından bir cevap sınıfı seçen lojistik regresyon "başına" beslenir. LLaVA ile aynı mimari topolojisi, sadece oyuncak boyutta.</p>
<div class="code-wrap"><div class="code-label"><span>PYTHON</span><button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest('.code-wrap').querySelector('code').textContent)">COPY</button></div><pre class="code-block"><code><span class="kw">import</span> numpy <span class="kw">as</span> np
<span class="kw">from</span> sklearn.feature_extraction.text <span class="kw">import</span> TfidfVectorizer
<span class="kw">from</span> sklearn.linear_model <span class="kw">import</span> LogisticRegression
<span class="kw">from</span> sklearn.pipeline <span class="kw">import</span> Pipeline

<span class="cm"># Sentetik VQA-benzeri veri kumesi: (gorsel-istatistikler, soru) -> cevap kategorisi</span>
np.random.<span class="fn">seed</span>(<span class="num">42</span>)
N = <span class="num">200</span>
<span class="cm"># Goru kodlayici: 16x16 goruntunun yalnizca (ortalama R, G, B)</span>
<span class="kw">def</span> <span class="fn">vis</span>(img):
    <span class="kw">return</span> img.<span class="fn">mean</span>(axis=(<span class="num">0</span>,<span class="num">1</span>))  <span class="cm"># (3,)</span>

<span class="cm"># Veri kumesi olustur</span>
imgs = []
qs = []
ys = []
<span class="kw">for</span> _ <span class="kw">in</span> <span class="fn">range</span>(N):
    <span class="cm"># parlak "disari" goruntusu</span>
    <span class="kw">if</span> np.random.<span class="fn">rand</span>() < <span class="num">0.5</span>:
        im = np.random.<span class="fn">rand</span>(<span class="num">16</span>,<span class="num">16</span>,<span class="num">3</span>) * np.<span class="fn">array</span>([<span class="num">0.9</span>, <span class="num">0.9</span>, <span class="num">1.0</span>])
        q  = np.random.<span class="fn">choice</span>([<span class="str">"What is the weather?"</span>, <span class="str">"Is this outdoor?"</span>, <span class="str">"How bright is it?"</span>])
        y  = <span class="str">"sunny"</span>
    <span class="kw">else</span>:
        im = np.random.<span class="fn">rand</span>(<span class="num">16</span>,<span class="num">16</span>,<span class="num">3</span>) * np.<span class="fn">array</span>([<span class="num">0.3</span>, <span class="num">0.3</span>, <span class="num">0.4</span>])
        q  = np.random.<span class="fn">choice</span>([<span class="str">"What is the weather?"</span>, <span class="str">"Is this outdoor?"</span>, <span class="str">"How bright is it?"</span>])
        y  = <span class="str">"dark"</span>
    imgs.<span class="fn">append</span>(im); qs.<span class="fn">append</span>(q); ys.<span class="fn">append</span>(y)

<span class="cm"># "Projektor": gorsel oznitelikler sabit-eslestirilir, sonra TF-IDF metniyle birlestirilir</span>
proj = np.random.<span class="fn">RandomState</span>(<span class="num">0</span>).<span class="fn">randn</span>(<span class="num">3</span>, <span class="num">8</span>)   <span class="cm"># 3 -> 8-boyutlu "gorsel tokenler"</span>
V = np.<span class="fn">stack</span>([<span class="fn">vis</span>(i) <span class="kw">for</span> i <span class="kw">in</span> imgs]) @ proj   <span class="cm"># (N, 8)</span>
vec = <span class="fn">TfidfVectorizer</span>().<span class="fn">fit</span>(qs)
T = vec.<span class="fn">transform</span>(qs).<span class="fn">toarray</span>()               <span class="cm"># (N, vocab)</span>

X = np.<span class="fn">hstack</span>([V, T])                         <span class="cm"># ortak multimodal gomme</span>
clf = <span class="fn">LogisticRegression</span>(max_iter=<span class="num">500</span>).<span class="fn">fit</span>(X, ys)

<span class="cm"># Yeni bir batch'te degerlendir</span>
test_imgs = [np.random.<span class="fn">rand</span>(<span class="num">16</span>,<span class="num">16</span>,<span class="num">3</span>) * <span class="num">0.9</span>, np.random.<span class="fn">rand</span>(<span class="num">16</span>,<span class="num">16</span>,<span class="num">3</span>) * <span class="num">0.3</span>]
test_qs   = [<span class="str">"What is the weather?"</span>, <span class="str">"Is this outdoor?"</span>]
Vt = np.<span class="fn">stack</span>([<span class="fn">vis</span>(i) <span class="kw">for</span> i <span class="kw">in</span> test_imgs]) @ proj
Tt = vec.<span class="fn">transform</span>(test_qs).<span class="fn">toarray</span>()
Xt = np.<span class="fn">hstack</span>([Vt, Tt])
<span class="fn">print</span>(<span class="str">"Tahminler:"</span>, clf.<span class="fn">predict</span>(Xt))
<span class="fn">print</span>(<span class="str">"Egitim dogr:  "</span>, clf.<span class="fn">score</span>(X, ys))
</code></pre></div>
</div>

<p class="l-text">Bu oyuncağın yapısal olarak doğru yaptığı üç şey: (1) görsel öznitelikler metin öznitelikleriyle aynı sayısal uzaya projekte edilir, (2) ortak vektör baş tarafından tüketilir, (3) çıkarım zamanında yalnızca yeni görüntüyü projekte etmeniz ve yeni soruyu yeniden vektörleştirmeniz gerekir. LogisticRegression'u 7B özyineli LLM ile değiştirin ve LLaVA'ya sahip olursunuz.</p>
</div>

<div class="lesson-block" id="section-6">
<h2 class="lesson-title">6. Görsel-Token Darboğazı ve AnyRes</h2>
<p class="l-text">CLIP ViT-L/14@336 576 yama token üretir. 336×336'ya yeniden boyutlandırılmış 1080×1920 ekran görüntüsü için, LLM görmeden önce piksel bilgisinin %95'i gitmiştir. Bu makbuzlar, grafikler, yoğun belgeler ve kontrol panelleri için anlaşma bozucudur.</p>

<div class="calc-cards">
<div class="calc-card"><div class="card-title">LLaVA-Next AnyRes</div><div class="card-body">Hedef bir en-boy oranı seç (örn. 2×2 düzenli 4 karo). Görüntüyü her karo 336×336 olacak şekilde yeniden boyutlandır. Her karoyu donmuş ViT ile ayrı kodla (4× maliyet). 4×576 = 2304 token'ı 576-token global düşük-çözünürlük görünümüyle birleştir → toplam 2880 token.</div></div>
<div class="calc-card"><div class="card-title">Qwen2-VL yerel dinamik çözünürlük</div><div class="card-body">Kodlayıcı görüntünün gerçek en-boy oranında çalışır (bir maksimuma kadar). M-RoPE 2D pozisyonu yerel olarak kodlar. Karo bölme yok, sınırlarda bilgi kaybı yok. Belge/grafik benchmarklarında en iyi sınıf.</div></div>
<div class="calc-card"><div class="card-title">Idefics2 / Pixtral Perceiver-yeniden örnekleyici</div><div class="card-body">Girdide değişken görüntü boyutu, Perceiver çapraz-dikkati ile sabit 64 veya 256 çıktı token'ı. Uzlaşma: küçük token bütçesi ama esnek girdi.</div></div>
<div class="calc-card"><div class="card-title">2026'da denge</div><div class="card-body">Daha çok token = daha iyi ince detay, daha yavaş çıkarım. Öncü açık kaynak genel kullanım için 1K–3K görsel token kullanır, belge görevleri için 16K+'ye ölçeklenir. Kapalı modeller (GPT-4V, Gemini) muhtemelen benzer taktikler kullanır.</div></div>
</div>
</div>

<div class="lesson-block" id="section-7">
<h2 class="lesson-title">7. Benchmarklar ve Aslında Ne Ölçtükleri</h2>
<p class="l-text">VLM benchmarklar 2023–2024'te parçalandı. Hangi görev ailesinde hangisine güveneceğinizi bilmek:</p>

<div class="calc-cards">
<div class="calc-card"><div class="card-title">VQAv2 (2017)</div><div class="card-body">COCO üzerinde açık-uçlu VQA. ~%80 güçlü-VLM aralığıdır. Doymuş; artık iyi bir ayırt edici değil.</div></div>
<div class="calc-card"><div class="card-title">GQA (2019)</div><div class="card-body">Sahne grafikleri üzerinde kompozisyonel akıl yürütme. VQAv2'den daha sıkı. LLaVA-1.5-13B: %63.3. GPT-4V: ~%75.</div></div>
<div class="calc-card"><div class="card-title">MMBench / MMBench-CN (2023)</div><div class="card-body">20 yetenek boyutunda 3K çoktan seçmeli, İngilizce + Çince. Prompt formatına dayanıklı. GPT-4V: %75.1. Qwen2-VL-72B: %86.5. Açık SOTA.</div></div>
<div class="calc-card"><div class="card-title">MMMU (2024)</div><div class="card-body">Üniversite-seviyesi multimodal (matematik, fizik, sanat, tıp). 11.5K soru. Acımasız benchmark. GPT-4o: %69.1. En iyi açık ~%63 (InternVL 2.5).</div></div>
<div class="calc-card"><div class="card-title">TextVQA / ChartQA / DocVQA</div><div class="card-body">Görüntülerde metin, grafikler, belgeler. Çözünürlüğe duyarlı. AnyRes / dinamik çözünürlük bunları 10+ puan dalgalandırır.</div></div>
<div class="calc-card"><div class="card-title">MM-Vet</div><div class="card-body">GPT-4 tarafından notlandırılan açık-uçlu üretim. Yalnızca çoktan seçmeli değil, sohbet kalitesini yakalar. LLaVA-Next makalesinde kullanıldı.</div></div>
</div>

<div class="calc-highlight"><strong>Bir benchmark seçimi:</strong> genel yetenek için MMBench. Araştırma-sınıf zor akıl yürütme için MMMU. Belge/OCR için DocVQA + ChartQA. Açık-uçlu sohbet kalitesi için MM-Vet. Asla yalnızca birini raporlamayın — tek-bench oyunlaştırma yaygındır.</div>
</div>

<div class="lesson-block" id="section-frontier">
<h2 class="lesson-title">2024–2026 Sınır Modelleri</h2>
<p class="l-text"><strong>LLaVA tarifi ölçeklendi — sonra 2024 oldu.</strong> Aşağıdaki kartlar, üretimde gerçekten dağıtacağınız veya ince ayar yapacağınız LLaVA / BLIP-2 ailesinin modern torunlarıdır. Üç desen baskındır: uçtan uca kapalı multimodal LLM'ler (GPT-4o, Claude 3.7, Gemini 2.0), temiz ince ayar yapılabilen açık-ağırlıklı VLM'ler (Llama 3.2, Qwen2-VL) ve yüksek-sadakat açık rakipler (InternVL 2.5).</p>
<div class="calc-cards">
<div class="calc-card"><div class="card-title">GPT-4o (OpenAI, May 2024)</div><div class="card-body">Tek modelde doğal multimodal metin + görü + ses. GPT-4 Turbo'dan %50 daha ucuz, uçtan uca ses (ayrı Whisper / TTS yok). VQA ve grafik okuma için varsayılan kapalı referans.</div></div>
<div class="calc-card"><div class="card-title">Claude 3.5 / 3.7 Sonnet (Anthropic, Haz 2024 / Şub 2025)</div><div class="card-body">Güçlü görü + genişletilmiş düşünme + bilgisayar kullanımı. Claude 3.7 ekran görüntüsü alıp UI'yı sürebilir — tıklar, yazar, kaydırır. Belge YS, ekran görüntüsü hata ayıklama ve ajansal UI görevleri için en iyisi.</div></div>
<div class="calc-card"><div class="card-title">Gemini 2.0 Flash (Google, Ara 2024)</div><div class="card-body">Doğal multimodal <em>çıktı</em> — iç içe metin + görüntü + ses üretir. 1M+ token bağlam, saatlik video, gerçek zamanlı asistanlar için akışlı Live API.</div></div>
<div class="calc-card"><div class="card-title">Llama 3.2 Vision 11B / 90B (Meta, Eyl 2024)</div><div class="card-body">İlk Meta açık-ağırlık VLM'leri. Donmuş Llama 3.1 üzerinde çapraz-dikkat adaptörü. 11B tek A100'de çalışır; 90B grafiklerde GPT-4V ile yarışır. İnce ayar yapılabilir — özel dağıtım için pratik seçim.</div></div>
<div class="calc-card"><div class="card-title">Qwen2-VL 72B (Alibaba, Ağu 2024)</div><div class="card-body">Doğal dinamik çözünürlük (AnyRes hilesi yok), 20 dakikalık video, MMMU ve DocVQA'da SOTA açık-kaynak. Sınır kapalı modellerle gerçekten yarışan ilk açık VLM.</div></div>
<div class="calc-card"><div class="card-title">InternVL 2.5 (OpenGVLab, Ara 2024)</div><div class="card-body">78B açık VLM, MMMU'da ~%70 (GPT-4V'ye yakın). 6B InternViT-6B kodlayıcı ve aşamalı eğitim kullanır. Açık modellerin kapalı sınırın 2 yıl değil ~6 ay gerisinde olduğunun kanıtı.</div></div>
</div>
<div class="calc-highlight"><strong>LLaVA-1'den beri mimari kayma:</strong> trend daha büyük görsel kodlayıcılar (InternViT-6B), AnyRes patching yerine doğal dinamik çözünürlük (Qwen2-VL) ve çıkarımda açık akıl yürütme bütçeleri (Claude 3.7 genişletilmiş düşünme). Q-Former darboğazı büyük ölçüde terk edildi — akıllı döşemeli tam görsel-token dizileri grafik/belge görevlerinde kazanıyor.</div>
</div>

<div class="lesson-block" id="section-8">
<h2 class="lesson-title">8. Özet ve Sonraki</h2>
<p class="l-text">Modern bir Görü-Dil Modeli; donmuş bir görsel kodlayıcı + küçük bir adaptör + güçlü bir LLM'dir. LLaVA'nın tarifi (doğrusal/MLP projektör, açıklamalarda iki aşamalı eğitim sonra GPT-4 tarafından üretilen talimatlar) ve BLIP-2'nin Q-Former alternatifi 2023–2024'teki neredeyse tüm açık kaynak ilerlemesini kapsadı. 2026'ya kadar yerel dinamik çözünürlük (Qwen2-VL) ve daha büyük görsel kodlayıcılar (InternVL) ana iyileştirme eksenleri.</p>

<div class="calc-highlight"><strong>Önemli çıkarımlar:</strong>
<ul style="margin:0.5rem 0 0;padding-left:1.2rem;line-height:1.65">
<li>LLaVA = donmuş ViT + doğrusal/MLP projektör + LLM. Görsel token'lar LLM'nin normal dizisinde yaşar.</li>
<li>İki aşamalı eğitim: açıklamalarda hizalama, sonra GPT-4 tarafından üretilen 150K örnekte görsel talimat ayarlama.</li>
<li>BLIP-2 32-token Q-Former darboğazı kullanır; LLaVA 576 yama token kullanır (AnyRes ile 2880).</li>
<li>Açık kaynak 2024 öncüsü: Qwen2-VL, InternVL 2.5, Pixtral. Kapalı: GPT-4o, Gemini 2.0, Claude 3.5.</li>
<li>Görsel-token darboğazı önemlidir: AnyRes / dinamik çözünürlük belge ve grafik görevlerini açar.</li>
<li>Benchmark portföyü: MMBench (genel), MMMU (zor akıl yürütme), DocVQA/ChartQA (görüntüde-metin), MM-Vet (sohbet kalitesi).</li>
</ul>
</div>

<p class="l-text"><strong>multimodal-L4</strong>'te modaliteleri değiştiriyoruz — görüden sese. Whisper'ın 99 dilde konuşmayı nasıl ele aldığını, SeamlessM4T'nin uçtan uca çeviriyi konuşma ve metin arasında nasıl genişlettiğini ve Qwen-Audio ile AudioGPT'nin az önce öğrendiğimiz aynı LLM-artı-adaptör tarifine sesi nasıl taktığını göreceğiz.</p>
</div>`
};
