/**
 * foundations.i18n.js — Math for ML translations (EN/TR/DE/ES)
 * Loaded after shared.i18n.js
 */
const T_LOCAL = {

  "math.eyebrow": {
    en:"Tutorial · Math for Machine Learning",
    tr:"Eğitim · Makine Öğrenmesi için Matematik",
    de:"Tutorial · Mathematik für ML",
    es:"Tutorial · Matemáticas para ML"},
  "math.desc": {
    en:"The <strong>mathematical language behind every ML algorithm</strong>. Derivatives drive gradient descent, integrals define probability distributions, linear algebra powers every neural network layer. No shortcuts — understand the math, understand the models.",
    tr:"<strong>Her ML algoritmasının arkasındaki matematiksel dil</strong>. Türevler gradyan inişini yönlendirir, integraller olasılık dağılımlarını tanımlar, lineer cebir her sinir ağı katmanını çalıştırır. Kısayol yok — matematiği anla, modelleri anla.",
    de:"Die <strong>mathematische Sprache hinter jedem ML-Algorithmus</strong>. Ableitungen treiben Gradientenabstieg, Integrale definieren Wahrscheinlichkeitsverteilungen, lineare Algebra betreibt jede neuronale Netzwerkschicht.",
    es:"El <strong>lenguaje matemático detrás de cada algoritmo ML</strong>. Las derivadas impulsan el descenso de gradiente, las integrales definen distribuciones de probabilidad, el álgebra lineal potencia cada capa de red neuronal."},
  "math.level": {
    en:"Beginner → Intermediate",
    tr:"Başlangıç → Orta",
    de:"Anfänger → Mittel",
    es:"Principiante → Intermedio"},

  "math.l1.t": {en:"Functions & Graphs",tr:"Fonksiyonlar & Grafikler",de:"Funktionen & Graphen",es:"Funciones y Gráficas"},
  "math.l1.s": {en:"f(x) · domain/range · linear · polynomial · exponential · sigmoid · 8 min",tr:"f(x) · tanım/değer kümesi · lineer · polinom · üstel · sigmoid · 8 dk",de:"f(x) · Definitions-/Wertebereich · linear · Polynom · exponentiell · Sigmoid · 8 Min.",es:"f(x) · dominio/rango · lineal · polinomio · exponencial · sigmoid · 8 min"},
  "math.l1.p1":{en:"A <strong>function</strong> maps each input to exactly one output: <code>f(x) = y</code>. In ML, everything is a function — a model maps inputs to predictions, a loss function maps predictions to error values, an activation function maps weighted sums to neuron outputs.",tr:"Bir <strong>fonksiyon</strong> her girdiyi tam olarak bir çıktıya eşler: <code>f(x) = y</code>. ML'de her şey bir fonksiyondur — bir model girdileri tahminlere, kayıp fonksiyonu tahminleri hata değerlerine, aktivasyon fonksiyonu ağırlıklı toplamları nöron çıktılarına eşler.",de:"Eine <strong>Funktion</strong> bildet jede Eingabe auf genau eine Ausgabe ab: <code>f(x) = y</code>. In ML ist alles eine Funktion — ein Modell bildet Eingaben auf Vorhersagen ab, eine Verlustfunktion Vorhersagen auf Fehlerwerte.",es:"Una <strong>función</strong> mapea cada entrada a exactamente una salida: <code>f(x) = y</code>. En ML todo es una función — un modelo mapea entradas a predicciones, una función de pérdida mapea predicciones a valores de error."},

  "math.l2.t": {en:"Derivatives — The Core of Learning",tr:"Türevler — Öğrenmenin Temeli",de:"Ableitungen — Der Kern des Lernens",es:"Derivadas — El Núcleo del Aprendizaje"},
  "math.l2.s": {en:"Limit definition · basic rules · chain rule · partial derivatives · 12 min",tr:"Limit tanımı · temel kurallar · zincir kuralı · kısmi türevler · 12 dk",de:"Grenzwertdefinition · Grundregeln · Kettenregel · partielle Ableitungen · 12 Min.",es:"Definición de límite · reglas básicas · regla de la cadena · derivadas parciales · 12 min"},
  "math.l2.p1":{en:"The <strong>derivative</strong> measures the rate of change of a function. In ML, the derivative tells us: \"if I slightly change this parameter, how much does the loss change?\" This is the <strong>entire basis of gradient descent</strong> — the algorithm that trains every neural network.",tr:"<strong>Türev</strong> bir fonksiyonun değişim hızını ölçer. ML'de türev bize şunu söyler: \"bu parametreyi biraz değiştirirsem, kayıp ne kadar değişir?\" Bu <strong>gradyan inişinin tüm temelidir</strong> — her sinir ağını eğiten algoritma.",de:"Die <strong>Ableitung</strong> misst die Änderungsrate einer Funktion. In ML sagt uns die Ableitung: \"Wenn ich diesen Parameter leicht ändere, wie stark ändert sich der Verlust?\" Dies ist die <strong>gesamte Grundlage des Gradientenabstiegs</strong>.",es:"La <strong>derivada</strong> mide la tasa de cambio de una función. En ML, la derivada nos dice: \"si cambio ligeramente este parámetro, ¿cuánto cambia la pérdida?\" Esta es la <strong>base completa del descenso de gradiente</strong>."},

  "math.l3.t": {en:"Derivatives in ML — Gradient Descent",tr:"ML'de Türevler — Gradyan İnişi",de:"Ableitungen in ML — Gradientenabstieg",es:"Derivadas en ML — Descenso de Gradiente"},
  "math.l3.s": {en:"Gradient · partial derivatives · gradient descent step · learning rate · 10 min",tr:"Gradyan · kısmi türevler · gradyan inişi adımı · öğrenme oranı · 10 dk",de:"Gradient · partielle Ableitungen · Gradientenabstiegsschritt · Lernrate · 10 Min.",es:"Gradiente · derivadas parciales · paso de descenso · tasa de aprendizaje · 10 min"},
  "math.l3.p1":{en:"The <strong>gradient</strong> is the vector of all partial derivatives — it points in the direction of steepest increase. To minimize a loss function, we move in the <strong>opposite direction</strong> of the gradient. This is gradient descent, and it's how every ML model learns.",tr:"<strong>Gradyan</strong> tüm kısmi türevlerin vektörüdür — en dik artış yönünü gösterir. Bir kayıp fonksiyonunu minimize etmek için gradyanın <strong>zıt yönüne</strong> hareket ederiz. Bu gradyan inişidir ve her ML modelinin öğrenme şeklidir.",de:"Der <strong>Gradient</strong> ist der Vektor aller partiellen Ableitungen — er zeigt in die Richtung des steilsten Anstiegs. Um eine Verlustfunktion zu minimieren, bewegen wir uns in die <strong>entgegengesetzte Richtung</strong>.",es:"El <strong>gradiente</strong> es el vector de todas las derivadas parciales — apunta en la dirección de mayor aumento. Para minimizar una función de pérdida, nos movemos en la <strong>dirección opuesta</strong>."},

  "math.l4.t": {en:"Integrals — Area & Accumulation",tr:"İntegraller — Alan & Birikim",de:"Integrale — Fläche & Akkumulation",es:"Integrales — Área y Acumulación"},
  "math.l4.s": {en:"Indefinite/definite integral · Fundamental Theorem · basic rules · 10 min",tr:"Belirsiz/belirli integral · Temel Teorem · temel kurallar · 10 dk",de:"Unbestimmtes/bestimmtes Integral · Fundamentalsatz · Grundregeln · 10 Min.",es:"Integral indefinida/definida · Teorema Fundamental · reglas básicas · 10 min"},
  "math.l4.p1":{en:"The <strong>integral</strong> is the reverse of differentiation — it accumulates quantities over an interval. If the derivative gives you speed, the integral gives you distance traveled. In ML, integrals define probability distributions, expected values, and continuous loss functions.",tr:"<strong>İntegral</strong> türevin tersidir — bir aralıktaki büyüklükleri biriktirir. Türev size hızı verirse, integral kat edilen mesafeyi verir. ML'de integraller olasılık dağılımlarını, beklenen değerleri ve sürekli kayıp fonksiyonlarını tanımlar.",de:"Das <strong>Integral</strong> ist die Umkehrung der Differentiation — es akkumuliert Größen über ein Intervall. Wenn die Ableitung Geschwindigkeit gibt, gibt das Integral die zurückgelegte Strecke.",es:"La <strong>integral</strong> es el reverso de la diferenciación — acumula cantidades sobre un intervalo. Si la derivada da velocidad, la integral da distancia recorrida."},

  "math.l5.t": {en:"Integrals in ML — Expectation & Probability",tr:"ML'de İntegraller — Beklenti & Olasılık",de:"Integrale in ML — Erwartungswert & Wahrscheinlichkeit",es:"Integrales en ML — Esperanza y Probabilidad"},
  "math.l5.s": {en:"PDF · CDF · expected value · variance · KL divergence · 10 min",tr:"PDF · CDF · beklenen değer · varyans · KL divergence · 10 dk",de:"PDF · CDF · Erwartungswert · Varianz · KL-Divergenz · 10 Min.",es:"PDF · CDF · valor esperado · varianza · divergencia KL · 10 min"},
  "math.l5.p1":{en:"In machine learning, integrals appear everywhere through <strong>probability</strong>. The expected value of a loss function, the area under precision-recall curves, KL divergence between distributions — all defined by integrals.",tr:"Makine öğrenmesinde integraller <strong>olasılık</strong> yoluyla her yerde karşımıza çıkar. Kayıp fonksiyonunun beklenen değeri, precision-recall eğrilerinin altındaki alan, dağılımlar arası KL divergence — hepsi integrallerle tanımlanır.",de:"In ML erscheinen Integrale überall durch <strong>Wahrscheinlichkeit</strong>. Der Erwartungswert einer Verlustfunktion, die Fläche unter Precision-Recall-Kurven, KL-Divergenz — alle durch Integrale definiert.",es:"En ML, las integrales aparecen en todas partes a través de la <strong>probabilidad</strong>. El valor esperado de una función de pérdida, el área bajo curvas precision-recall, divergencia KL — todo definido por integrales."},

  "math.l6.t": {en:"Linear Algebra Essentials",tr:"Lineer Cebir Temelleri",de:"Grundlagen der Linearen Algebra",es:"Fundamentos de Álgebra Lineal"},
  "math.l6.s": {en:"Vectors · matrices · dot product · matrix multiplication · eigenvalues · 12 min",tr:"Vektörler · matrisler · iç çarpım · matris çarpımı · özdeğerler · 12 dk",de:"Vektoren · Matrizen · Skalarprodukt · Matrixmultiplikation · Eigenwerte · 12 Min.",es:"Vectores · matrices · producto punto · multiplicación de matrices · eigenvalores · 12 min"},
  "math.l6.p1":{en:"<strong>Linear algebra is the computational engine of deep learning.</strong> Every input is a vector, every weight matrix transforms that vector, every attention score is a dot product. Without linear algebra, there is no deep learning.",tr:"<strong>Lineer cebir, derin öğrenmenin hesaplama motorudur.</strong> Her girdi bir vektör, her ağırlık matrisi o vektörü dönüştürür, her dikkat skoru bir iç çarpımdır. Lineer cebir olmadan derin öğrenme yoktur.",de:"<strong>Lineare Algebra ist der Rechenmotor von Deep Learning.</strong> Jede Eingabe ist ein Vektor, jede Gewichtsmatrix transformiert diesen Vektor, jeder Attention-Score ist ein Skalarprodukt.",es:"<strong>El álgebra lineal es el motor computacional del deep learning.</strong> Cada entrada es un vector, cada matriz de pesos transforma ese vector, cada score de atención es un producto punto."},

  "math.l7.t": {en:"Probability & Statistics for ML",tr:"ML için Olasılık & İstatistik",de:"Wahrscheinlichkeit & Statistik für ML",es:"Probabilidad y Estadísticas para ML"},
  "math.l7.s": {en:"Bayes' theorem · distributions · MLE · bias-variance tradeoff · 12 min",tr:"Bayes teoremi · dağılımlar · MLE · yanlılık-varyans dengesi · 12 dk",de:"Satz von Bayes · Verteilungen · MLE · Bias-Varianz-Tradeoff · 12 Min.",es:"Teorema de Bayes · distribuciones · MLE · tradeoff sesgo-varianza · 12 min"},
  "math.l7.p1":{en:"<strong>Probability is the language of uncertainty</strong>, and ML is all about making decisions under uncertainty. Bayes' theorem is the foundation of many classifiers, maximum likelihood estimation (MLE) is how models learn parameters, and understanding distributions tells you which loss function to use.",tr:"<strong>Olasılık belirsizliğin dilidir</strong> ve ML tamamen belirsizlik altında karar vermekle ilgilidir. Bayes teoremi birçok sınıflandırıcının temelidir, maksimum olabilirlik tahmini (MLE) modellerin parametreleri öğrenme şeklidir ve dağılımları anlamak hangi kayıp fonksiyonunu kullanacağınızı söyler.",de:"<strong>Wahrscheinlichkeit ist die Sprache der Unsicherheit</strong>, und ML dreht sich um Entscheidungen unter Unsicherheit. Der Satz von Bayes ist die Grundlage vieler Klassifikatoren, MLE ist wie Modelle Parameter lernen.",es:"<strong>La probabilidad es el lenguaje de la incertidumbre</strong>, y ML trata de tomar decisiones bajo incertidumbre. El teorema de Bayes es la base de muchos clasificadores, MLE es cómo los modelos aprenden parámetros."},
};

Object.assign(T, T_LOCAL);
