/**
 * numpy.i18n.js — NumPy translations (EN/TR/DE/ES)
 * Loaded after shared.i18n.js
 */
const T_LOCAL = {

  "np.eyebrow": {
    en:"Tutorial · NumPy",
    tr:"Eğitim · NumPy",
    de:"Tutorial · NumPy",
    es:"Tutorial · NumPy"},
  "np.desc": {
    en:"The <strong>mathematical backbone of Python's ML ecosystem</strong>. NumPy arrays power every tensor in PyTorch and TensorFlow. Master arrays, broadcasting, linear algebra, and vectorized operations — the foundation that makes deep learning possible.",
    tr:"Python'un ML ekosisteminin <strong>matematiksel omurgası</strong>. NumPy dizileri PyTorch ve TensorFlow'daki her tensörü besler. Dizileri, broadcasting'i, lineer cebri ve vektörel işlemleri öğrenin — derin öğrenmeyi mümkün kılan temel.",
    de:"Das <strong>mathematische Rückgrat von Pythons ML-Ökosystem</strong>. NumPy-Arrays treiben jeden Tensor in PyTorch und TensorFlow an. Meistern Sie Arrays, Broadcasting, lineare Algebra und vektorisierte Operationen.",
    es:"La <strong>columna vertebral matemática del ecosistema ML de Python</strong>. Los arrays de NumPy impulsan cada tensor en PyTorch y TensorFlow. Domina arrays, broadcasting, álgebra lineal y operaciones vectorizadas."},
  "np.level": {
    en:"Beginner → Intermediate",
    tr:"Başlangıç → Orta",
    de:"Anfänger → Mittel",
    es:"Principiante → Intermedio"},

  "np.l1.t":  {en:"Array Basics",tr:"Dizi Temelleri",de:"Array-Grundlagen",es:"Fundamentos de Arrays"},
  "np.l1.s":  {en:"np.array · ndim · shape · dtype · zeros/ones/arange/linspace · 8 min",tr:"np.array · ndim · shape · dtype · zeros/ones/arange/linspace · 8 dk",de:"np.array · ndim · shape · dtype · zeros/ones/arange/linspace · 8 Min.",es:"np.array · ndim · shape · dtype · zeros/ones/arange/linspace · 8 min"},
  "np.l1.p1": {en:"A NumPy <strong>ndarray</strong> is a fixed-type, contiguous-memory array — fundamentally different from Python lists. This design makes mathematical operations orders of magnitude faster. Every PyTorch tensor, every TensorFlow array, every Scikit-learn matrix is built on NumPy's foundation.",tr:"NumPy <strong>ndarray</strong> sabit tipli, bitişik bellekli bir dizidir — Python listelerinden temelden farklıdır. Bu tasarım matematiksel işlemleri kat kat hızlı yapar. Her PyTorch tensörü, her TensorFlow dizisi, her Scikit-learn matrisi NumPy temeli üzerine inşa edilir.",de:"Ein NumPy <strong>ndarray</strong> ist ein Typ-festes, zusammenhängendes Speicher-Array — grundlegend anders als Python-Listen. Jeder PyTorch-Tensor, jedes TensorFlow-Array baut auf NumPy auf.",es:"Un <strong>ndarray</strong> de NumPy es un array de tipo fijo y memoria contigua — fundamentalmente diferente de las listas Python. Cada tensor de PyTorch, cada array de TensorFlow se construye sobre NumPy."},

  "np.l2.t":  {en:"Indexing & Slicing",tr:"İndeksleme & Dilimleme",de:"Indizierung & Slicing",es:"Indexación y Slicing"},
  "np.l2.s":  {en:"Basic/fancy indexing · boolean masks · np.where · np.argmax/argmin · 8 min",tr:"Temel/fancy indeksleme · boolean maskeler · np.where · np.argmax/argmin · 8 dk",de:"Basis-/Fancy-Indizierung · Boolesche Masken · np.where · np.argmax/argmin · 8 Min.",es:"Indexación básica/fancy · máscaras booleanas · np.where · np.argmax/argmin · 8 min"},
  "np.l2.p1": {en:"NumPy indexing goes far beyond Python lists. <strong>Boolean masks</strong> filter arrays by condition, <strong>fancy indexing</strong> selects specific indices, and <code>np.where</code> is the vectorized if-else. These are the operations you'll use constantly when processing model outputs.",tr:"NumPy indeksleme Python listelerinin çok ötesine geçer. <strong>Boolean maskeler</strong> dizileri koşullarla filtreler, <strong>fancy indeksleme</strong> belirli indeksleri seçer ve <code>np.where</code> vektörel if-else'dir.",de:"NumPy-Indizierung geht weit über Python-Listen hinaus. <strong>Boolesche Masken</strong> filtern nach Bedingungen, <strong>Fancy-Indizierung</strong> wählt bestimmte Indizes, und <code>np.where</code> ist das vektorisierte if-else.",es:"La indexación NumPy va mucho más allá de las listas Python. Las <strong>máscaras booleanas</strong> filtran por condición, la <strong>indexación fancy</strong> selecciona índices específicos, y <code>np.where</code> es el if-else vectorizado."},

  "np.l3.t":  {en:"Array Operations & Broadcasting",tr:"Dizi İşlemleri & Broadcasting",de:"Array-Operationen & Broadcasting",es:"Operaciones de Arrays y Broadcasting"},
  "np.l3.s":  {en:"Element-wise ops · broadcasting rules · universal functions (ufuncs) · 10 min",tr:"Eleman bazlı işlemler · broadcasting kuralları · evrensel fonksiyonlar (ufunc'lar) · 10 dk",de:"Elementweise Ops · Broadcasting-Regeln · universelle Funktionen (Ufuncs) · 10 Min.",es:"Ops elemento a elemento · reglas de broadcasting · funciones universales (ufuncs) · 10 min"},
  "np.l3.p1": {en:"<strong>Broadcasting</strong> is NumPy's most powerful feature — it lets you perform operations between arrays of different shapes without explicit loops. Understanding broadcasting rules is essential for writing efficient neural network code.",tr:"<strong>Broadcasting</strong> NumPy'ın en güçlü özelliğidir — farklı şekillerdeki diziler arasında açık döngüler olmadan işlem yapmanızı sağlar. Broadcasting kurallarını anlamak verimli sinir ağı kodu yazmak için olmazsa olmazdır.",de:"<strong>Broadcasting</strong> ist NumPys leistungsstärkstes Feature — es ermöglicht Operationen zwischen Arrays unterschiedlicher Form ohne explizite Schleifen.",es:"<strong>Broadcasting</strong> es la característica más poderosa de NumPy — permite operaciones entre arrays de diferentes formas sin bucles explícitos."},

  "np.l4.t":  {en:"Reshaping & Stacking",tr:"Yeniden Şekillendirme & Yığma",de:"Umformung & Stapeln",es:"Remodelado y Apilamiento"},
  "np.l4.s":  {en:"reshape · ravel · flatten · transpose · concatenate · vstack/hstack · 8 min",tr:"reshape · ravel · flatten · transpose · concatenate · vstack/hstack · 8 dk",de:"reshape · ravel · flatten · transpose · concatenate · vstack/hstack · 8 Min.",es:"reshape · ravel · flatten · transpose · concatenate · vstack/hstack · 8 min"},
  "np.l4.p1": {en:"<strong>Reshaping</strong> changes how data is organized without copying it. In deep learning, you constantly reshape tensors — flattening CNN outputs, adding batch dimensions, transposing attention matrices. These operations must be second nature.",tr:"<strong>Yeniden şekillendirme</strong> veriyi kopyalamadan nasıl organize edildiğini değiştirir. Derin öğrenmede sürekli tensörleri yeniden şekillendirirsiniz — CNN çıktılarını düzleştirme, batch boyutu ekleme, dikkat matrislerini transpoze etme.",de:"<strong>Umformung</strong> ändert die Datenorganisation ohne Kopieren. In Deep Learning formt man ständig Tensoren um — CNN-Ausgaben glätten, Batch-Dimensionen hinzufügen, Attention-Matrizen transponieren.",es:"<strong>Remodelar</strong> cambia cómo se organizan los datos sin copiarlos. En deep learning constantemente remodelamos tensores — aplanar salidas CNN, agregar dimensiones batch, transponer matrices de atención."},

  "np.l5.t":  {en:"Linear Algebra",tr:"Lineer Cebir",de:"Lineare Algebra",es:"Álgebra Lineal"},
  "np.l5.s":  {en:"dot product · matrix multiplication · np.linalg (inv, det, eig, svd) · 10 min",tr:"iç çarpım · matris çarpımı · np.linalg (inv, det, eig, svd) · 10 dk",de:"Skalarprodukt · Matrixmultiplikation · np.linalg (inv, det, eig, svd) · 10 Min.",es:"producto punto · multiplicación de matrices · np.linalg (inv, det, eig, svd) · 10 min"},
  "np.l5.p1": {en:"<strong>Linear algebra is the language of deep learning.</strong> Every forward pass is a matrix multiplication, every attention score is a dot product, every dimensionality reduction uses SVD or eigendecomposition. NumPy's <code>linalg</code> module gives you the tools.",tr:"<strong>Lineer cebir, derin öğrenmenin dilidir.</strong> Her ileri geçiş bir matris çarpımı, her dikkat skoru bir iç çarpım, her boyut indirgeme SVD veya öz ayrışım kullanır. NumPy'ın <code>linalg</code> modülü bu araçları sağlar.",de:"<strong>Lineare Algebra ist die Sprache von Deep Learning.</strong> Jeder Forward-Pass ist eine Matrixmultiplikation, jeder Attention-Score ein Skalarprodukt. NumPys <code>linalg</code>-Modul liefert die Werkzeuge.",es:"<strong>El álgebra lineal es el lenguaje del deep learning.</strong> Cada paso forward es una multiplicación de matrices, cada score de atención un producto punto. El módulo <code>linalg</code> de NumPy da las herramientas."},

  "np.l6.t":  {en:"Statistics & Random",tr:"İstatistik & Rastgele",de:"Statistik & Zufall",es:"Estadísticas y Aleatorio"},
  "np.l6.s":  {en:"mean · std · var · percentile · np.random (normal, uniform, seed, shuffle) · 8 min",tr:"mean · std · var · percentile · np.random (normal, uniform, seed, shuffle) · 8 dk",de:"mean · std · var · Perzentil · np.random (normal, uniform, seed, shuffle) · 8 Min.",es:"mean · std · var · percentil · np.random (normal, uniform, seed, shuffle) · 8 min"},
  "np.l6.p1": {en:"Statistical operations and random number generation are the tools of <strong>EDA and model initialization</strong>. You'll compute dataset statistics, generate weight initializations, and create reproducible experiments with random seeds — all through NumPy.",tr:"İstatistiksel işlemler ve rastgele sayı üretimi <strong>EDA ve model başlatmanın</strong> araçlarıdır. Veri seti istatistikleri hesaplar, ağırlık başlatmaları oluşturur ve rastgele tohumlarla tekrarlanabilir deneyler yaratırsınız — hepsi NumPy ile.",de:"Statistische Operationen und Zufallszahlengenerierung sind die Werkzeuge für <strong>EDA und Modellinitialisierung</strong>. Berechnen Sie Datensatz-Statistiken und erzeugen Sie reproduzierbare Experimente.",es:"Las operaciones estadísticas y la generación de números aleatorios son herramientas de <strong>EDA e inicialización de modelos</strong>. Calcularás estadísticas, generarás inicializaciones de pesos y crearás experimentos reproducibles."},

  "np.l7.t":  {en:"Mathematical Functions",tr:"Matematiksel Fonksiyonlar",de:"Mathematische Funktionen",es:"Funciones Matemáticas"},
  "np.l7.s":  {en:"exp · log · sqrt · sin/cos · clip · round · absolute · 6 min",tr:"exp · log · sqrt · sin/cos · clip · round · absolute · 6 dk",de:"exp · log · sqrt · sin/cos · clip · round · absolute · 6 Min.",es:"exp · log · sqrt · sin/cos · clip · round · absolute · 6 min"},
  "np.l7.p1": {en:"NumPy's mathematical functions are the building blocks of <strong>activation functions, loss functions, and normalization</strong>. Every sigmoid, softmax, and cross-entropy computation uses these primitives.",tr:"NumPy'ın matematiksel fonksiyonları <strong>aktivasyon fonksiyonlarının, kayıp fonksiyonlarının ve normalizasyonun</strong> yapı taşlarıdır. Her sigmoid, softmax ve çapraz entropi hesaplaması bu temelleri kullanır.",de:"NumPys mathematische Funktionen sind die Bausteine von <strong>Aktivierungsfunktionen, Verlustfunktionen und Normalisierung</strong>.",es:"Las funciones matemáticas de NumPy son los bloques de construcción de <strong>funciones de activación, funciones de pérdida y normalización</strong>."},

  "np.l8.t":  {en:"Performance & Memory",tr:"Performans & Bellek",de:"Performance & Speicher",es:"Rendimiento y Memoria"},
  "np.l8.s":  {en:"dtype selection · views vs copies · vectorization vs loops · memory layout · 8 min",tr:"dtype seçimi · view vs kopyalar · vektörizasyon vs döngüler · bellek düzeni · 8 dk",de:"Dtype-Auswahl · Views vs Kopien · Vektorisierung vs Schleifen · Speicherlayout · 8 Min.",es:"selección de dtype · views vs copias · vectorización vs bucles · layout de memoria · 8 min"},
  "np.l8.p1": {en:"Knowing <strong>when NumPy copies data vs creates a view</strong>, choosing the right dtype, and understanding memory layout can make your code 10x faster and use 4x less memory. These micro-optimizations add up when processing millions of text samples.",tr:"NumPy'ın <strong>ne zaman veri kopyaladığını ne zaman view oluşturduğunu</strong> bilmek, doğru dtype'ı seçmek ve bellek düzenini anlamak kodunuzu 10 kat hızlandırabilir ve 4 kat daha az bellek kullandırabilir.",de:"Zu wissen, <strong>wann NumPy Daten kopiert vs eine View erstellt</strong>, den richtigen Dtype zu wählen und das Speicherlayout zu verstehen, kann Code 10x schneller machen und 4x weniger Speicher verbrauchen.",es:"Saber <strong>cuándo NumPy copia datos vs crea una vista</strong>, elegir el dtype correcto y entender el layout de memoria puede hacer tu código 10x más rápido y usar 4x menos memoria."},
};

Object.assign(T, T_LOCAL);
